-- ==============================================================
-- Generated by Vitis HLS v2024.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sikep503_kem_enc_hw_EphemeralKeyGeneration_A_1_Outline_VITIS_LOOP_36_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tmp_323 : IN STD_LOGIC_VECTOR (6 downto 0);
    R_X_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_ce0 : OUT STD_LOGIC;
    R_X_we0 : OUT STD_LOGIC;
    R_X_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_46_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_46_ce0 : OUT STD_LOGIC;
    R_X_46_we0 : OUT STD_LOGIC;
    R_X_46_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_46_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_47_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_47_ce0 : OUT STD_LOGIC;
    R_X_47_we0 : OUT STD_LOGIC;
    R_X_47_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_47_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_48_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_48_ce0 : OUT STD_LOGIC;
    R_X_48_we0 : OUT STD_LOGIC;
    R_X_48_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_48_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_49_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_49_ce0 : OUT STD_LOGIC;
    R_X_49_we0 : OUT STD_LOGIC;
    R_X_49_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_49_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_50_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_50_ce0 : OUT STD_LOGIC;
    R_X_50_we0 : OUT STD_LOGIC;
    R_X_50_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_50_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_51_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_51_ce0 : OUT STD_LOGIC;
    R_X_51_we0 : OUT STD_LOGIC;
    R_X_51_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_51_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_52_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_52_ce0 : OUT STD_LOGIC;
    R_X_52_we0 : OUT STD_LOGIC;
    R_X_52_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_52_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_53_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_53_ce0 : OUT STD_LOGIC;
    R_X_53_we0 : OUT STD_LOGIC;
    R_X_53_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_53_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_54_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_54_ce0 : OUT STD_LOGIC;
    R_X_54_we0 : OUT STD_LOGIC;
    R_X_54_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_54_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_55_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_55_ce0 : OUT STD_LOGIC;
    R_X_55_we0 : OUT STD_LOGIC;
    R_X_55_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_55_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_56_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_56_ce0 : OUT STD_LOGIC;
    R_X_56_we0 : OUT STD_LOGIC;
    R_X_56_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_56_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_57_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_57_ce0 : OUT STD_LOGIC;
    R_X_57_we0 : OUT STD_LOGIC;
    R_X_57_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_57_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_58_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_58_ce0 : OUT STD_LOGIC;
    R_X_58_we0 : OUT STD_LOGIC;
    R_X_58_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_58_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_59_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_59_ce0 : OUT STD_LOGIC;
    R_X_59_we0 : OUT STD_LOGIC;
    R_X_59_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_59_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_X_60_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_X_60_ce0 : OUT STD_LOGIC;
    R_X_60_we0 : OUT STD_LOGIC;
    R_X_60_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_X_60_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_ce0 : OUT STD_LOGIC;
    R_Z_we0 : OUT STD_LOGIC;
    R_Z_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_46_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_46_ce0 : OUT STD_LOGIC;
    R_Z_46_we0 : OUT STD_LOGIC;
    R_Z_46_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_46_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_47_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_47_ce0 : OUT STD_LOGIC;
    R_Z_47_we0 : OUT STD_LOGIC;
    R_Z_47_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_47_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_48_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_48_ce0 : OUT STD_LOGIC;
    R_Z_48_we0 : OUT STD_LOGIC;
    R_Z_48_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_48_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_49_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_49_ce0 : OUT STD_LOGIC;
    R_Z_49_we0 : OUT STD_LOGIC;
    R_Z_49_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_49_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_50_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_50_ce0 : OUT STD_LOGIC;
    R_Z_50_we0 : OUT STD_LOGIC;
    R_Z_50_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_50_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_51_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_51_ce0 : OUT STD_LOGIC;
    R_Z_51_we0 : OUT STD_LOGIC;
    R_Z_51_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_51_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_52_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_52_ce0 : OUT STD_LOGIC;
    R_Z_52_we0 : OUT STD_LOGIC;
    R_Z_52_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_52_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_53_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_53_ce0 : OUT STD_LOGIC;
    R_Z_53_we0 : OUT STD_LOGIC;
    R_Z_53_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_53_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_54_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_54_ce0 : OUT STD_LOGIC;
    R_Z_54_we0 : OUT STD_LOGIC;
    R_Z_54_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_54_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_55_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_55_ce0 : OUT STD_LOGIC;
    R_Z_55_we0 : OUT STD_LOGIC;
    R_Z_55_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_55_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_56_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_56_ce0 : OUT STD_LOGIC;
    R_Z_56_we0 : OUT STD_LOGIC;
    R_Z_56_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_56_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_57_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_57_ce0 : OUT STD_LOGIC;
    R_Z_57_we0 : OUT STD_LOGIC;
    R_Z_57_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_57_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_58_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_58_ce0 : OUT STD_LOGIC;
    R_Z_58_we0 : OUT STD_LOGIC;
    R_Z_58_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_58_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_59_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_59_ce0 : OUT STD_LOGIC;
    R_Z_59_we0 : OUT STD_LOGIC;
    R_Z_59_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_59_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_Z_60_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    R_Z_60_ce0 : OUT STD_LOGIC;
    R_Z_60_we0 : OUT STD_LOGIC;
    R_Z_60_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_Z_60_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_load : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_load_2 : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_1_load : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_1_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_2_load : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_2_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_3_load : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_3_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_4_load : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_4_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_5_load : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_5_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_6_load : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_6_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_7_load : IN STD_LOGIC_VECTOR (63 downto 0);
    A24plus_7_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_load : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_load_2 : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_1_load : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_1_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_2_load : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_2_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_3_load : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_3_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_4_load : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_4_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_5_load : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_5_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_6_load : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_6_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_7_load : IN STD_LOGIC_VECTOR (63 downto 0);
    C24_7_load_1 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of sikep503_kem_enc_hw_EphemeralKeyGeneration_A_1_Outline_VITIS_LOOP_36_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_xDBL_fu_370_ap_start : STD_LOGIC;
    signal grp_xDBL_fu_370_ap_done : STD_LOGIC;
    signal grp_xDBL_fu_370_ap_idle : STD_LOGIC;
    signal grp_xDBL_fu_370_ap_ready : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_0_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_0_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_0_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_0_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_0_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_0_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_0_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_0_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_1_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_1_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_1_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_1_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_1_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_1_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_1_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_1_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_2_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_2_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_2_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_2_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_2_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_2_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_2_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_2_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_3_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_3_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_3_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_3_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_3_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_3_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_3_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_3_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_4_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_4_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_4_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_4_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_4_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_4_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_4_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_4_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_5_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_5_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_5_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_5_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_5_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_5_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_5_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_5_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_6_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_6_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_6_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_6_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_6_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_6_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_6_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_6_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_7_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_7_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_7_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_7_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_X_7_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_X_7_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_7_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_X_7_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_0_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_0_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_0_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_0_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_0_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_0_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_0_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_0_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_1_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_1_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_1_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_1_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_1_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_1_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_1_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_1_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_2_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_2_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_2_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_2_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_2_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_2_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_2_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_2_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_3_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_3_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_3_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_3_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_3_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_3_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_3_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_3_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_4_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_4_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_4_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_4_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_4_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_4_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_4_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_4_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_5_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_5_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_5_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_5_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_5_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_5_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_5_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_5_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_6_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_6_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_6_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_6_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_6_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_6_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_6_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_6_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_7_0_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_7_0_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_7_0_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_7_0_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_Q_Z_7_1_address0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xDBL_fu_370_Q_Z_7_1_ce0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_7_1_we0 : STD_LOGIC;
    signal grp_xDBL_fu_370_Q_Z_7_1_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_xDBL_fu_370_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln36_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_206_fu_168 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal i_228_fu_489_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sikep503_kem_enc_hw_xDBL IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Q_X_0_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_0_0_ce0 : OUT STD_LOGIC;
        Q_X_0_0_we0 : OUT STD_LOGIC;
        Q_X_0_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_0_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_0_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_0_1_ce0 : OUT STD_LOGIC;
        Q_X_0_1_we0 : OUT STD_LOGIC;
        Q_X_0_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_0_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_1_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_1_0_ce0 : OUT STD_LOGIC;
        Q_X_1_0_we0 : OUT STD_LOGIC;
        Q_X_1_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_1_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_1_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_1_1_ce0 : OUT STD_LOGIC;
        Q_X_1_1_we0 : OUT STD_LOGIC;
        Q_X_1_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_1_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_2_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_2_0_ce0 : OUT STD_LOGIC;
        Q_X_2_0_we0 : OUT STD_LOGIC;
        Q_X_2_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_2_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_2_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_2_1_ce0 : OUT STD_LOGIC;
        Q_X_2_1_we0 : OUT STD_LOGIC;
        Q_X_2_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_2_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_3_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_3_0_ce0 : OUT STD_LOGIC;
        Q_X_3_0_we0 : OUT STD_LOGIC;
        Q_X_3_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_3_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_3_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_3_1_ce0 : OUT STD_LOGIC;
        Q_X_3_1_we0 : OUT STD_LOGIC;
        Q_X_3_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_3_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_4_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_4_0_ce0 : OUT STD_LOGIC;
        Q_X_4_0_we0 : OUT STD_LOGIC;
        Q_X_4_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_4_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_4_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_4_1_ce0 : OUT STD_LOGIC;
        Q_X_4_1_we0 : OUT STD_LOGIC;
        Q_X_4_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_4_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_5_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_5_0_ce0 : OUT STD_LOGIC;
        Q_X_5_0_we0 : OUT STD_LOGIC;
        Q_X_5_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_5_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_5_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_5_1_ce0 : OUT STD_LOGIC;
        Q_X_5_1_we0 : OUT STD_LOGIC;
        Q_X_5_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_5_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_6_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_6_0_ce0 : OUT STD_LOGIC;
        Q_X_6_0_we0 : OUT STD_LOGIC;
        Q_X_6_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_6_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_6_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_6_1_ce0 : OUT STD_LOGIC;
        Q_X_6_1_we0 : OUT STD_LOGIC;
        Q_X_6_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_6_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_7_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_7_0_ce0 : OUT STD_LOGIC;
        Q_X_7_0_we0 : OUT STD_LOGIC;
        Q_X_7_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_7_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_X_7_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_X_7_1_ce0 : OUT STD_LOGIC;
        Q_X_7_1_we0 : OUT STD_LOGIC;
        Q_X_7_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_X_7_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_0_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_0_0_ce0 : OUT STD_LOGIC;
        Q_Z_0_0_we0 : OUT STD_LOGIC;
        Q_Z_0_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_0_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_0_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_0_1_ce0 : OUT STD_LOGIC;
        Q_Z_0_1_we0 : OUT STD_LOGIC;
        Q_Z_0_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_0_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_1_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_1_0_ce0 : OUT STD_LOGIC;
        Q_Z_1_0_we0 : OUT STD_LOGIC;
        Q_Z_1_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_1_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_1_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_1_1_ce0 : OUT STD_LOGIC;
        Q_Z_1_1_we0 : OUT STD_LOGIC;
        Q_Z_1_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_1_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_2_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_2_0_ce0 : OUT STD_LOGIC;
        Q_Z_2_0_we0 : OUT STD_LOGIC;
        Q_Z_2_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_2_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_2_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_2_1_ce0 : OUT STD_LOGIC;
        Q_Z_2_1_we0 : OUT STD_LOGIC;
        Q_Z_2_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_2_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_3_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_3_0_ce0 : OUT STD_LOGIC;
        Q_Z_3_0_we0 : OUT STD_LOGIC;
        Q_Z_3_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_3_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_3_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_3_1_ce0 : OUT STD_LOGIC;
        Q_Z_3_1_we0 : OUT STD_LOGIC;
        Q_Z_3_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_3_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_4_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_4_0_ce0 : OUT STD_LOGIC;
        Q_Z_4_0_we0 : OUT STD_LOGIC;
        Q_Z_4_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_4_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_4_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_4_1_ce0 : OUT STD_LOGIC;
        Q_Z_4_1_we0 : OUT STD_LOGIC;
        Q_Z_4_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_4_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_5_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_5_0_ce0 : OUT STD_LOGIC;
        Q_Z_5_0_we0 : OUT STD_LOGIC;
        Q_Z_5_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_5_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_5_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_5_1_ce0 : OUT STD_LOGIC;
        Q_Z_5_1_we0 : OUT STD_LOGIC;
        Q_Z_5_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_5_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_6_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_6_0_ce0 : OUT STD_LOGIC;
        Q_Z_6_0_we0 : OUT STD_LOGIC;
        Q_Z_6_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_6_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_6_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_6_1_ce0 : OUT STD_LOGIC;
        Q_Z_6_1_we0 : OUT STD_LOGIC;
        Q_Z_6_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_6_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_7_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_7_0_ce0 : OUT STD_LOGIC;
        Q_Z_7_0_we0 : OUT STD_LOGIC;
        Q_Z_7_0_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_7_0_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_7_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Q_Z_7_1_ce0 : OUT STD_LOGIC;
        Q_Z_7_1_we0 : OUT STD_LOGIC;
        Q_Z_7_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Q_Z_7_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_0_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_0_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_1_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_1_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_2_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_2_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_3_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_3_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_4_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_4_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_5_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_5_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_6_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_6_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_7_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        A24plus_7_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_0_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_0_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_1_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_1_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_2_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_2_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_3_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_3_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_4_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_4_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_5_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_5_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_6_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_6_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_7_0_0_val : IN STD_LOGIC_VECTOR (63 downto 0);
        C24_7_0_1_val : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_xDBL_fu_370 : component sikep503_kem_enc_hw_xDBL
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xDBL_fu_370_ap_start,
        ap_done => grp_xDBL_fu_370_ap_done,
        ap_idle => grp_xDBL_fu_370_ap_idle,
        ap_ready => grp_xDBL_fu_370_ap_ready,
        Q_X_0_0_address0 => grp_xDBL_fu_370_Q_X_0_0_address0,
        Q_X_0_0_ce0 => grp_xDBL_fu_370_Q_X_0_0_ce0,
        Q_X_0_0_we0 => grp_xDBL_fu_370_Q_X_0_0_we0,
        Q_X_0_0_d0 => grp_xDBL_fu_370_Q_X_0_0_d0,
        Q_X_0_0_q0 => R_X_q0,
        Q_X_0_1_address0 => grp_xDBL_fu_370_Q_X_0_1_address0,
        Q_X_0_1_ce0 => grp_xDBL_fu_370_Q_X_0_1_ce0,
        Q_X_0_1_we0 => grp_xDBL_fu_370_Q_X_0_1_we0,
        Q_X_0_1_d0 => grp_xDBL_fu_370_Q_X_0_1_d0,
        Q_X_0_1_q0 => R_X_46_q0,
        Q_X_1_0_address0 => grp_xDBL_fu_370_Q_X_1_0_address0,
        Q_X_1_0_ce0 => grp_xDBL_fu_370_Q_X_1_0_ce0,
        Q_X_1_0_we0 => grp_xDBL_fu_370_Q_X_1_0_we0,
        Q_X_1_0_d0 => grp_xDBL_fu_370_Q_X_1_0_d0,
        Q_X_1_0_q0 => R_X_47_q0,
        Q_X_1_1_address0 => grp_xDBL_fu_370_Q_X_1_1_address0,
        Q_X_1_1_ce0 => grp_xDBL_fu_370_Q_X_1_1_ce0,
        Q_X_1_1_we0 => grp_xDBL_fu_370_Q_X_1_1_we0,
        Q_X_1_1_d0 => grp_xDBL_fu_370_Q_X_1_1_d0,
        Q_X_1_1_q0 => R_X_48_q0,
        Q_X_2_0_address0 => grp_xDBL_fu_370_Q_X_2_0_address0,
        Q_X_2_0_ce0 => grp_xDBL_fu_370_Q_X_2_0_ce0,
        Q_X_2_0_we0 => grp_xDBL_fu_370_Q_X_2_0_we0,
        Q_X_2_0_d0 => grp_xDBL_fu_370_Q_X_2_0_d0,
        Q_X_2_0_q0 => R_X_49_q0,
        Q_X_2_1_address0 => grp_xDBL_fu_370_Q_X_2_1_address0,
        Q_X_2_1_ce0 => grp_xDBL_fu_370_Q_X_2_1_ce0,
        Q_X_2_1_we0 => grp_xDBL_fu_370_Q_X_2_1_we0,
        Q_X_2_1_d0 => grp_xDBL_fu_370_Q_X_2_1_d0,
        Q_X_2_1_q0 => R_X_50_q0,
        Q_X_3_0_address0 => grp_xDBL_fu_370_Q_X_3_0_address0,
        Q_X_3_0_ce0 => grp_xDBL_fu_370_Q_X_3_0_ce0,
        Q_X_3_0_we0 => grp_xDBL_fu_370_Q_X_3_0_we0,
        Q_X_3_0_d0 => grp_xDBL_fu_370_Q_X_3_0_d0,
        Q_X_3_0_q0 => R_X_51_q0,
        Q_X_3_1_address0 => grp_xDBL_fu_370_Q_X_3_1_address0,
        Q_X_3_1_ce0 => grp_xDBL_fu_370_Q_X_3_1_ce0,
        Q_X_3_1_we0 => grp_xDBL_fu_370_Q_X_3_1_we0,
        Q_X_3_1_d0 => grp_xDBL_fu_370_Q_X_3_1_d0,
        Q_X_3_1_q0 => R_X_52_q0,
        Q_X_4_0_address0 => grp_xDBL_fu_370_Q_X_4_0_address0,
        Q_X_4_0_ce0 => grp_xDBL_fu_370_Q_X_4_0_ce0,
        Q_X_4_0_we0 => grp_xDBL_fu_370_Q_X_4_0_we0,
        Q_X_4_0_d0 => grp_xDBL_fu_370_Q_X_4_0_d0,
        Q_X_4_0_q0 => R_X_53_q0,
        Q_X_4_1_address0 => grp_xDBL_fu_370_Q_X_4_1_address0,
        Q_X_4_1_ce0 => grp_xDBL_fu_370_Q_X_4_1_ce0,
        Q_X_4_1_we0 => grp_xDBL_fu_370_Q_X_4_1_we0,
        Q_X_4_1_d0 => grp_xDBL_fu_370_Q_X_4_1_d0,
        Q_X_4_1_q0 => R_X_54_q0,
        Q_X_5_0_address0 => grp_xDBL_fu_370_Q_X_5_0_address0,
        Q_X_5_0_ce0 => grp_xDBL_fu_370_Q_X_5_0_ce0,
        Q_X_5_0_we0 => grp_xDBL_fu_370_Q_X_5_0_we0,
        Q_X_5_0_d0 => grp_xDBL_fu_370_Q_X_5_0_d0,
        Q_X_5_0_q0 => R_X_55_q0,
        Q_X_5_1_address0 => grp_xDBL_fu_370_Q_X_5_1_address0,
        Q_X_5_1_ce0 => grp_xDBL_fu_370_Q_X_5_1_ce0,
        Q_X_5_1_we0 => grp_xDBL_fu_370_Q_X_5_1_we0,
        Q_X_5_1_d0 => grp_xDBL_fu_370_Q_X_5_1_d0,
        Q_X_5_1_q0 => R_X_56_q0,
        Q_X_6_0_address0 => grp_xDBL_fu_370_Q_X_6_0_address0,
        Q_X_6_0_ce0 => grp_xDBL_fu_370_Q_X_6_0_ce0,
        Q_X_6_0_we0 => grp_xDBL_fu_370_Q_X_6_0_we0,
        Q_X_6_0_d0 => grp_xDBL_fu_370_Q_X_6_0_d0,
        Q_X_6_0_q0 => R_X_57_q0,
        Q_X_6_1_address0 => grp_xDBL_fu_370_Q_X_6_1_address0,
        Q_X_6_1_ce0 => grp_xDBL_fu_370_Q_X_6_1_ce0,
        Q_X_6_1_we0 => grp_xDBL_fu_370_Q_X_6_1_we0,
        Q_X_6_1_d0 => grp_xDBL_fu_370_Q_X_6_1_d0,
        Q_X_6_1_q0 => R_X_58_q0,
        Q_X_7_0_address0 => grp_xDBL_fu_370_Q_X_7_0_address0,
        Q_X_7_0_ce0 => grp_xDBL_fu_370_Q_X_7_0_ce0,
        Q_X_7_0_we0 => grp_xDBL_fu_370_Q_X_7_0_we0,
        Q_X_7_0_d0 => grp_xDBL_fu_370_Q_X_7_0_d0,
        Q_X_7_0_q0 => R_X_59_q0,
        Q_X_7_1_address0 => grp_xDBL_fu_370_Q_X_7_1_address0,
        Q_X_7_1_ce0 => grp_xDBL_fu_370_Q_X_7_1_ce0,
        Q_X_7_1_we0 => grp_xDBL_fu_370_Q_X_7_1_we0,
        Q_X_7_1_d0 => grp_xDBL_fu_370_Q_X_7_1_d0,
        Q_X_7_1_q0 => R_X_60_q0,
        Q_Z_0_0_address0 => grp_xDBL_fu_370_Q_Z_0_0_address0,
        Q_Z_0_0_ce0 => grp_xDBL_fu_370_Q_Z_0_0_ce0,
        Q_Z_0_0_we0 => grp_xDBL_fu_370_Q_Z_0_0_we0,
        Q_Z_0_0_d0 => grp_xDBL_fu_370_Q_Z_0_0_d0,
        Q_Z_0_0_q0 => R_Z_q0,
        Q_Z_0_1_address0 => grp_xDBL_fu_370_Q_Z_0_1_address0,
        Q_Z_0_1_ce0 => grp_xDBL_fu_370_Q_Z_0_1_ce0,
        Q_Z_0_1_we0 => grp_xDBL_fu_370_Q_Z_0_1_we0,
        Q_Z_0_1_d0 => grp_xDBL_fu_370_Q_Z_0_1_d0,
        Q_Z_0_1_q0 => R_Z_46_q0,
        Q_Z_1_0_address0 => grp_xDBL_fu_370_Q_Z_1_0_address0,
        Q_Z_1_0_ce0 => grp_xDBL_fu_370_Q_Z_1_0_ce0,
        Q_Z_1_0_we0 => grp_xDBL_fu_370_Q_Z_1_0_we0,
        Q_Z_1_0_d0 => grp_xDBL_fu_370_Q_Z_1_0_d0,
        Q_Z_1_0_q0 => R_Z_47_q0,
        Q_Z_1_1_address0 => grp_xDBL_fu_370_Q_Z_1_1_address0,
        Q_Z_1_1_ce0 => grp_xDBL_fu_370_Q_Z_1_1_ce0,
        Q_Z_1_1_we0 => grp_xDBL_fu_370_Q_Z_1_1_we0,
        Q_Z_1_1_d0 => grp_xDBL_fu_370_Q_Z_1_1_d0,
        Q_Z_1_1_q0 => R_Z_48_q0,
        Q_Z_2_0_address0 => grp_xDBL_fu_370_Q_Z_2_0_address0,
        Q_Z_2_0_ce0 => grp_xDBL_fu_370_Q_Z_2_0_ce0,
        Q_Z_2_0_we0 => grp_xDBL_fu_370_Q_Z_2_0_we0,
        Q_Z_2_0_d0 => grp_xDBL_fu_370_Q_Z_2_0_d0,
        Q_Z_2_0_q0 => R_Z_49_q0,
        Q_Z_2_1_address0 => grp_xDBL_fu_370_Q_Z_2_1_address0,
        Q_Z_2_1_ce0 => grp_xDBL_fu_370_Q_Z_2_1_ce0,
        Q_Z_2_1_we0 => grp_xDBL_fu_370_Q_Z_2_1_we0,
        Q_Z_2_1_d0 => grp_xDBL_fu_370_Q_Z_2_1_d0,
        Q_Z_2_1_q0 => R_Z_50_q0,
        Q_Z_3_0_address0 => grp_xDBL_fu_370_Q_Z_3_0_address0,
        Q_Z_3_0_ce0 => grp_xDBL_fu_370_Q_Z_3_0_ce0,
        Q_Z_3_0_we0 => grp_xDBL_fu_370_Q_Z_3_0_we0,
        Q_Z_3_0_d0 => grp_xDBL_fu_370_Q_Z_3_0_d0,
        Q_Z_3_0_q0 => R_Z_51_q0,
        Q_Z_3_1_address0 => grp_xDBL_fu_370_Q_Z_3_1_address0,
        Q_Z_3_1_ce0 => grp_xDBL_fu_370_Q_Z_3_1_ce0,
        Q_Z_3_1_we0 => grp_xDBL_fu_370_Q_Z_3_1_we0,
        Q_Z_3_1_d0 => grp_xDBL_fu_370_Q_Z_3_1_d0,
        Q_Z_3_1_q0 => R_Z_52_q0,
        Q_Z_4_0_address0 => grp_xDBL_fu_370_Q_Z_4_0_address0,
        Q_Z_4_0_ce0 => grp_xDBL_fu_370_Q_Z_4_0_ce0,
        Q_Z_4_0_we0 => grp_xDBL_fu_370_Q_Z_4_0_we0,
        Q_Z_4_0_d0 => grp_xDBL_fu_370_Q_Z_4_0_d0,
        Q_Z_4_0_q0 => R_Z_53_q0,
        Q_Z_4_1_address0 => grp_xDBL_fu_370_Q_Z_4_1_address0,
        Q_Z_4_1_ce0 => grp_xDBL_fu_370_Q_Z_4_1_ce0,
        Q_Z_4_1_we0 => grp_xDBL_fu_370_Q_Z_4_1_we0,
        Q_Z_4_1_d0 => grp_xDBL_fu_370_Q_Z_4_1_d0,
        Q_Z_4_1_q0 => R_Z_54_q0,
        Q_Z_5_0_address0 => grp_xDBL_fu_370_Q_Z_5_0_address0,
        Q_Z_5_0_ce0 => grp_xDBL_fu_370_Q_Z_5_0_ce0,
        Q_Z_5_0_we0 => grp_xDBL_fu_370_Q_Z_5_0_we0,
        Q_Z_5_0_d0 => grp_xDBL_fu_370_Q_Z_5_0_d0,
        Q_Z_5_0_q0 => R_Z_55_q0,
        Q_Z_5_1_address0 => grp_xDBL_fu_370_Q_Z_5_1_address0,
        Q_Z_5_1_ce0 => grp_xDBL_fu_370_Q_Z_5_1_ce0,
        Q_Z_5_1_we0 => grp_xDBL_fu_370_Q_Z_5_1_we0,
        Q_Z_5_1_d0 => grp_xDBL_fu_370_Q_Z_5_1_d0,
        Q_Z_5_1_q0 => R_Z_56_q0,
        Q_Z_6_0_address0 => grp_xDBL_fu_370_Q_Z_6_0_address0,
        Q_Z_6_0_ce0 => grp_xDBL_fu_370_Q_Z_6_0_ce0,
        Q_Z_6_0_we0 => grp_xDBL_fu_370_Q_Z_6_0_we0,
        Q_Z_6_0_d0 => grp_xDBL_fu_370_Q_Z_6_0_d0,
        Q_Z_6_0_q0 => R_Z_57_q0,
        Q_Z_6_1_address0 => grp_xDBL_fu_370_Q_Z_6_1_address0,
        Q_Z_6_1_ce0 => grp_xDBL_fu_370_Q_Z_6_1_ce0,
        Q_Z_6_1_we0 => grp_xDBL_fu_370_Q_Z_6_1_we0,
        Q_Z_6_1_d0 => grp_xDBL_fu_370_Q_Z_6_1_d0,
        Q_Z_6_1_q0 => R_Z_58_q0,
        Q_Z_7_0_address0 => grp_xDBL_fu_370_Q_Z_7_0_address0,
        Q_Z_7_0_ce0 => grp_xDBL_fu_370_Q_Z_7_0_ce0,
        Q_Z_7_0_we0 => grp_xDBL_fu_370_Q_Z_7_0_we0,
        Q_Z_7_0_d0 => grp_xDBL_fu_370_Q_Z_7_0_d0,
        Q_Z_7_0_q0 => R_Z_59_q0,
        Q_Z_7_1_address0 => grp_xDBL_fu_370_Q_Z_7_1_address0,
        Q_Z_7_1_ce0 => grp_xDBL_fu_370_Q_Z_7_1_ce0,
        Q_Z_7_1_we0 => grp_xDBL_fu_370_Q_Z_7_1_we0,
        Q_Z_7_1_d0 => grp_xDBL_fu_370_Q_Z_7_1_d0,
        Q_Z_7_1_q0 => R_Z_60_q0,
        A24plus_0_0_0_val => A24plus_load,
        A24plus_0_0_1_val => A24plus_load_2,
        A24plus_1_0_0_val => A24plus_1_load,
        A24plus_1_0_1_val => A24plus_1_load_1,
        A24plus_2_0_0_val => A24plus_2_load,
        A24plus_2_0_1_val => A24plus_2_load_1,
        A24plus_3_0_0_val => A24plus_3_load,
        A24plus_3_0_1_val => A24plus_3_load_1,
        A24plus_4_0_0_val => A24plus_4_load,
        A24plus_4_0_1_val => A24plus_4_load_1,
        A24plus_5_0_0_val => A24plus_5_load,
        A24plus_5_0_1_val => A24plus_5_load_1,
        A24plus_6_0_0_val => A24plus_6_load,
        A24plus_6_0_1_val => A24plus_6_load_1,
        A24plus_7_0_0_val => A24plus_7_load,
        A24plus_7_0_1_val => A24plus_7_load_1,
        C24_0_0_0_val => C24_load,
        C24_0_0_1_val => C24_load_2,
        C24_1_0_0_val => C24_1_load,
        C24_1_0_1_val => C24_1_load_1,
        C24_2_0_0_val => C24_2_load,
        C24_2_0_1_val => C24_2_load_1,
        C24_3_0_0_val => C24_3_load,
        C24_3_0_1_val => C24_3_load_1,
        C24_4_0_0_val => C24_4_load,
        C24_4_0_1_val => C24_4_load_1,
        C24_5_0_0_val => C24_5_load,
        C24_5_0_1_val => C24_5_load_1,
        C24_6_0_0_val => C24_6_load,
        C24_6_0_1_val => C24_6_load_1,
        C24_7_0_0_val => C24_7_load,
        C24_7_0_1_val => C24_7_load_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_xDBL_fu_370_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xDBL_fu_370_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln36_fu_484_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_xDBL_fu_370_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xDBL_fu_370_ap_ready = ap_const_logic_1)) then 
                    grp_xDBL_fu_370_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_206_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_206_fu_168 <= ap_const_lv7_0;
            elsif (((icmp_ln36_fu_484_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_206_fu_168 <= i_228_fu_489_p2;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_xDBL_fu_370_ap_done, ap_CS_fsm_state2, icmp_ln36_fu_484_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln36_fu_484_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_xDBL_fu_370_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    R_X_46_address0 <= grp_xDBL_fu_370_Q_X_0_1_address0;
    R_X_46_ce0 <= grp_xDBL_fu_370_Q_X_0_1_ce0;
    R_X_46_d0 <= grp_xDBL_fu_370_Q_X_0_1_d0;
    R_X_46_we0 <= grp_xDBL_fu_370_Q_X_0_1_we0;
    R_X_47_address0 <= grp_xDBL_fu_370_Q_X_1_0_address0;
    R_X_47_ce0 <= grp_xDBL_fu_370_Q_X_1_0_ce0;
    R_X_47_d0 <= grp_xDBL_fu_370_Q_X_1_0_d0;
    R_X_47_we0 <= grp_xDBL_fu_370_Q_X_1_0_we0;
    R_X_48_address0 <= grp_xDBL_fu_370_Q_X_1_1_address0;
    R_X_48_ce0 <= grp_xDBL_fu_370_Q_X_1_1_ce0;
    R_X_48_d0 <= grp_xDBL_fu_370_Q_X_1_1_d0;
    R_X_48_we0 <= grp_xDBL_fu_370_Q_X_1_1_we0;
    R_X_49_address0 <= grp_xDBL_fu_370_Q_X_2_0_address0;
    R_X_49_ce0 <= grp_xDBL_fu_370_Q_X_2_0_ce0;
    R_X_49_d0 <= grp_xDBL_fu_370_Q_X_2_0_d0;
    R_X_49_we0 <= grp_xDBL_fu_370_Q_X_2_0_we0;
    R_X_50_address0 <= grp_xDBL_fu_370_Q_X_2_1_address0;
    R_X_50_ce0 <= grp_xDBL_fu_370_Q_X_2_1_ce0;
    R_X_50_d0 <= grp_xDBL_fu_370_Q_X_2_1_d0;
    R_X_50_we0 <= grp_xDBL_fu_370_Q_X_2_1_we0;
    R_X_51_address0 <= grp_xDBL_fu_370_Q_X_3_0_address0;
    R_X_51_ce0 <= grp_xDBL_fu_370_Q_X_3_0_ce0;
    R_X_51_d0 <= grp_xDBL_fu_370_Q_X_3_0_d0;
    R_X_51_we0 <= grp_xDBL_fu_370_Q_X_3_0_we0;
    R_X_52_address0 <= grp_xDBL_fu_370_Q_X_3_1_address0;
    R_X_52_ce0 <= grp_xDBL_fu_370_Q_X_3_1_ce0;
    R_X_52_d0 <= grp_xDBL_fu_370_Q_X_3_1_d0;
    R_X_52_we0 <= grp_xDBL_fu_370_Q_X_3_1_we0;
    R_X_53_address0 <= grp_xDBL_fu_370_Q_X_4_0_address0;
    R_X_53_ce0 <= grp_xDBL_fu_370_Q_X_4_0_ce0;
    R_X_53_d0 <= grp_xDBL_fu_370_Q_X_4_0_d0;
    R_X_53_we0 <= grp_xDBL_fu_370_Q_X_4_0_we0;
    R_X_54_address0 <= grp_xDBL_fu_370_Q_X_4_1_address0;
    R_X_54_ce0 <= grp_xDBL_fu_370_Q_X_4_1_ce0;
    R_X_54_d0 <= grp_xDBL_fu_370_Q_X_4_1_d0;
    R_X_54_we0 <= grp_xDBL_fu_370_Q_X_4_1_we0;
    R_X_55_address0 <= grp_xDBL_fu_370_Q_X_5_0_address0;
    R_X_55_ce0 <= grp_xDBL_fu_370_Q_X_5_0_ce0;
    R_X_55_d0 <= grp_xDBL_fu_370_Q_X_5_0_d0;
    R_X_55_we0 <= grp_xDBL_fu_370_Q_X_5_0_we0;
    R_X_56_address0 <= grp_xDBL_fu_370_Q_X_5_1_address0;
    R_X_56_ce0 <= grp_xDBL_fu_370_Q_X_5_1_ce0;
    R_X_56_d0 <= grp_xDBL_fu_370_Q_X_5_1_d0;
    R_X_56_we0 <= grp_xDBL_fu_370_Q_X_5_1_we0;
    R_X_57_address0 <= grp_xDBL_fu_370_Q_X_6_0_address0;
    R_X_57_ce0 <= grp_xDBL_fu_370_Q_X_6_0_ce0;
    R_X_57_d0 <= grp_xDBL_fu_370_Q_X_6_0_d0;
    R_X_57_we0 <= grp_xDBL_fu_370_Q_X_6_0_we0;
    R_X_58_address0 <= grp_xDBL_fu_370_Q_X_6_1_address0;
    R_X_58_ce0 <= grp_xDBL_fu_370_Q_X_6_1_ce0;
    R_X_58_d0 <= grp_xDBL_fu_370_Q_X_6_1_d0;
    R_X_58_we0 <= grp_xDBL_fu_370_Q_X_6_1_we0;
    R_X_59_address0 <= grp_xDBL_fu_370_Q_X_7_0_address0;
    R_X_59_ce0 <= grp_xDBL_fu_370_Q_X_7_0_ce0;
    R_X_59_d0 <= grp_xDBL_fu_370_Q_X_7_0_d0;
    R_X_59_we0 <= grp_xDBL_fu_370_Q_X_7_0_we0;
    R_X_60_address0 <= grp_xDBL_fu_370_Q_X_7_1_address0;
    R_X_60_ce0 <= grp_xDBL_fu_370_Q_X_7_1_ce0;
    R_X_60_d0 <= grp_xDBL_fu_370_Q_X_7_1_d0;
    R_X_60_we0 <= grp_xDBL_fu_370_Q_X_7_1_we0;
    R_X_address0 <= grp_xDBL_fu_370_Q_X_0_0_address0;
    R_X_ce0 <= grp_xDBL_fu_370_Q_X_0_0_ce0;
    R_X_d0 <= grp_xDBL_fu_370_Q_X_0_0_d0;
    R_X_we0 <= grp_xDBL_fu_370_Q_X_0_0_we0;
    R_Z_46_address0 <= grp_xDBL_fu_370_Q_Z_0_1_address0;
    R_Z_46_ce0 <= grp_xDBL_fu_370_Q_Z_0_1_ce0;
    R_Z_46_d0 <= grp_xDBL_fu_370_Q_Z_0_1_d0;
    R_Z_46_we0 <= grp_xDBL_fu_370_Q_Z_0_1_we0;
    R_Z_47_address0 <= grp_xDBL_fu_370_Q_Z_1_0_address0;
    R_Z_47_ce0 <= grp_xDBL_fu_370_Q_Z_1_0_ce0;
    R_Z_47_d0 <= grp_xDBL_fu_370_Q_Z_1_0_d0;
    R_Z_47_we0 <= grp_xDBL_fu_370_Q_Z_1_0_we0;
    R_Z_48_address0 <= grp_xDBL_fu_370_Q_Z_1_1_address0;
    R_Z_48_ce0 <= grp_xDBL_fu_370_Q_Z_1_1_ce0;
    R_Z_48_d0 <= grp_xDBL_fu_370_Q_Z_1_1_d0;
    R_Z_48_we0 <= grp_xDBL_fu_370_Q_Z_1_1_we0;
    R_Z_49_address0 <= grp_xDBL_fu_370_Q_Z_2_0_address0;
    R_Z_49_ce0 <= grp_xDBL_fu_370_Q_Z_2_0_ce0;
    R_Z_49_d0 <= grp_xDBL_fu_370_Q_Z_2_0_d0;
    R_Z_49_we0 <= grp_xDBL_fu_370_Q_Z_2_0_we0;
    R_Z_50_address0 <= grp_xDBL_fu_370_Q_Z_2_1_address0;
    R_Z_50_ce0 <= grp_xDBL_fu_370_Q_Z_2_1_ce0;
    R_Z_50_d0 <= grp_xDBL_fu_370_Q_Z_2_1_d0;
    R_Z_50_we0 <= grp_xDBL_fu_370_Q_Z_2_1_we0;
    R_Z_51_address0 <= grp_xDBL_fu_370_Q_Z_3_0_address0;
    R_Z_51_ce0 <= grp_xDBL_fu_370_Q_Z_3_0_ce0;
    R_Z_51_d0 <= grp_xDBL_fu_370_Q_Z_3_0_d0;
    R_Z_51_we0 <= grp_xDBL_fu_370_Q_Z_3_0_we0;
    R_Z_52_address0 <= grp_xDBL_fu_370_Q_Z_3_1_address0;
    R_Z_52_ce0 <= grp_xDBL_fu_370_Q_Z_3_1_ce0;
    R_Z_52_d0 <= grp_xDBL_fu_370_Q_Z_3_1_d0;
    R_Z_52_we0 <= grp_xDBL_fu_370_Q_Z_3_1_we0;
    R_Z_53_address0 <= grp_xDBL_fu_370_Q_Z_4_0_address0;
    R_Z_53_ce0 <= grp_xDBL_fu_370_Q_Z_4_0_ce0;
    R_Z_53_d0 <= grp_xDBL_fu_370_Q_Z_4_0_d0;
    R_Z_53_we0 <= grp_xDBL_fu_370_Q_Z_4_0_we0;
    R_Z_54_address0 <= grp_xDBL_fu_370_Q_Z_4_1_address0;
    R_Z_54_ce0 <= grp_xDBL_fu_370_Q_Z_4_1_ce0;
    R_Z_54_d0 <= grp_xDBL_fu_370_Q_Z_4_1_d0;
    R_Z_54_we0 <= grp_xDBL_fu_370_Q_Z_4_1_we0;
    R_Z_55_address0 <= grp_xDBL_fu_370_Q_Z_5_0_address0;
    R_Z_55_ce0 <= grp_xDBL_fu_370_Q_Z_5_0_ce0;
    R_Z_55_d0 <= grp_xDBL_fu_370_Q_Z_5_0_d0;
    R_Z_55_we0 <= grp_xDBL_fu_370_Q_Z_5_0_we0;
    R_Z_56_address0 <= grp_xDBL_fu_370_Q_Z_5_1_address0;
    R_Z_56_ce0 <= grp_xDBL_fu_370_Q_Z_5_1_ce0;
    R_Z_56_d0 <= grp_xDBL_fu_370_Q_Z_5_1_d0;
    R_Z_56_we0 <= grp_xDBL_fu_370_Q_Z_5_1_we0;
    R_Z_57_address0 <= grp_xDBL_fu_370_Q_Z_6_0_address0;
    R_Z_57_ce0 <= grp_xDBL_fu_370_Q_Z_6_0_ce0;
    R_Z_57_d0 <= grp_xDBL_fu_370_Q_Z_6_0_d0;
    R_Z_57_we0 <= grp_xDBL_fu_370_Q_Z_6_0_we0;
    R_Z_58_address0 <= grp_xDBL_fu_370_Q_Z_6_1_address0;
    R_Z_58_ce0 <= grp_xDBL_fu_370_Q_Z_6_1_ce0;
    R_Z_58_d0 <= grp_xDBL_fu_370_Q_Z_6_1_d0;
    R_Z_58_we0 <= grp_xDBL_fu_370_Q_Z_6_1_we0;
    R_Z_59_address0 <= grp_xDBL_fu_370_Q_Z_7_0_address0;
    R_Z_59_ce0 <= grp_xDBL_fu_370_Q_Z_7_0_ce0;
    R_Z_59_d0 <= grp_xDBL_fu_370_Q_Z_7_0_d0;
    R_Z_59_we0 <= grp_xDBL_fu_370_Q_Z_7_0_we0;
    R_Z_60_address0 <= grp_xDBL_fu_370_Q_Z_7_1_address0;
    R_Z_60_ce0 <= grp_xDBL_fu_370_Q_Z_7_1_ce0;
    R_Z_60_d0 <= grp_xDBL_fu_370_Q_Z_7_1_d0;
    R_Z_60_we0 <= grp_xDBL_fu_370_Q_Z_7_1_we0;
    R_Z_address0 <= grp_xDBL_fu_370_Q_Z_0_0_address0;
    R_Z_ce0 <= grp_xDBL_fu_370_Q_Z_0_0_ce0;
    R_Z_d0 <= grp_xDBL_fu_370_Q_Z_0_0_d0;
    R_Z_we0 <= grp_xDBL_fu_370_Q_Z_0_0_we0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_xDBL_fu_370_ap_done)
    begin
        if ((grp_xDBL_fu_370_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln36_fu_484_p2)
    begin
        if ((((icmp_ln36_fu_484_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln36_fu_484_p2)
    begin
        if (((icmp_ln36_fu_484_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_xDBL_fu_370_ap_start <= grp_xDBL_fu_370_ap_start_reg;
    i_228_fu_489_p2 <= std_logic_vector(unsigned(i_206_fu_168) + unsigned(ap_const_lv7_1));
    icmp_ln36_fu_484_p2 <= "1" when (i_206_fu_168 = tmp_323) else "0";
end behav;
