-- ==============================================================
-- Generated by Vitis HLS v2024.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sikep503_kem_enc_hw_rdc_mont_4_Pipeline_VITIS_LOOP_299_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    v_026 : IN STD_LOGIC_VECTOR (63 downto 0);
    u_025 : IN STD_LOGIC_VECTOR (63 downto 0);
    i_7 : IN STD_LOGIC_VECTOR (2 downto 0);
    mc_offset1 : IN STD_LOGIC_VECTOR (0 downto 0);
    mc_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mc_ce0 : OUT STD_LOGIC;
    mc_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    add_ln299 : IN STD_LOGIC_VECTOR (3 downto 0);
    empty : IN STD_LOGIC_VECTOR (2 downto 0);
    v_35_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    v_35_out_ap_vld : OUT STD_LOGIC;
    u_29_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    u_29_out_ap_vld : OUT STD_LOGIC;
    t_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    t_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sikep503_kem_enc_hw_rdc_mont_4_Pipeline_VITIS_LOOP_299_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv64_3F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln299_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p503p1_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal p503p1_1_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln299_reg_751 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln300_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln300_reg_760 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln300_reg_760_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln156_fu_325_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln156_reg_772 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln176_fu_393_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln176_reg_777 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln181_fu_425_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln181_reg_783 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln181_15_fu_431_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln181_15_reg_788 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_reg_793 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln301_1_fu_246_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln301_fu_263_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_fu_84 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal t_2_fu_672_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal u_fu_88 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal u_2_fu_679_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal v_fu_92 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal v_2_fu_686_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_96 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln299_3_fu_232_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_j_6 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal mc_ce0_local : STD_LOGIC;
    signal p503p1_1_ce0_local : STD_LOGIC;
    signal albl_fu_183_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln155_8_fu_303_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal albl_fu_183_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln155_fu_281_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal albh_fu_187_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln163_fu_319_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal albh_fu_187_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ahbl_fu_191_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ahbl_fu_191_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln161_fu_297_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ahbh_fu_195_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ahbh_fu_195_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_238_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln299_fu_222_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln301_fu_257_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal al_fu_273_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ah_fu_287_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal bl_fu_277_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bh_fu_309_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal albl_fu_183_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal albh_fu_187_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ahbl_fu_191_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ahbh_fu_195_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_31_fu_341_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln156_32_fu_333_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln156_31_fu_329_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln174_fu_355_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln174_14_fu_359_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln174_fu_363_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln174_15_fu_369_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln156_fu_351_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal temp_fu_373_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_32_fu_379_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_33_fu_397_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln156_33_fu_337_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln181_fu_421_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln156_15_fu_407_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln156_s_fu_411_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln156_14_fu_389_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln181_15_fu_472_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln181_14_fu_469_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal temp_13_fu_475_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tempReg_fu_463_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln_fu_456_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal v_34_fu_485_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln105_59_fu_497_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln105_fu_491_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln105_fu_503_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln105_60_fu_509_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal carry_fu_515_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_534_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln303_3_fu_544_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln155_fu_481_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln303_fu_552_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln_fu_527_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln303_fu_560_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln303_4_fu_556_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln303_fu_566_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln105_fu_523_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tempReg_10_fu_572_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bit_sel_fu_584_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln105_61_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln105_fu_598_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal xor_ln105_s_fu_602_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln105_fu_610_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal u_27_fu_578_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln105_63_fu_630_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln105_62_fu_624_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln105_11_fu_636_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln105_64_fu_642_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_47_fu_648_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_46_fu_616_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_19_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln304_fu_662_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_12_fu_666_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sikep503_kem_enc_hw_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sikep503_kem_enc_hw_rdc_mont_4_Pipeline_VITIS_LOOP_299_3_p503p1_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sikep503_kem_enc_hw_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    p503p1_1_U : component sikep503_kem_enc_hw_rdc_mont_4_Pipeline_VITIS_LOOP_299_3_p503p1_1_ROM_AUTO_1R
    generic map (
        DataWidth => 64,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p503p1_1_address0,
        ce0 => p503p1_1_ce0_local,
        q0 => p503p1_1_q0);

    mul_32ns_32ns_64_1_1_U822 : component sikep503_kem_enc_hw_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => albl_fu_183_p0,
        din1 => albl_fu_183_p1,
        dout => albl_fu_183_p2);

    mul_32ns_32ns_64_1_1_U823 : component sikep503_kem_enc_hw_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => albh_fu_187_p0,
        din1 => albh_fu_187_p1,
        dout => albh_fu_187_p2);

    mul_32ns_32ns_64_1_1_U824 : component sikep503_kem_enc_hw_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => ahbl_fu_191_p0,
        din1 => ahbl_fu_191_p1,
        dout => ahbl_fu_191_p2);

    mul_32ns_32ns_64_1_1_U825 : component sikep503_kem_enc_hw_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => ahbh_fu_195_p0,
        din1 => ahbh_fu_195_p1,
        dout => ahbh_fu_195_p2);

    flow_control_loop_pipe_sequential_init_U : component sikep503_kem_enc_hw_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln299_fu_226_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_96 <= add_ln299_3_fu_232_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_96 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    t_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    t_fu_84 <= ap_const_lv64_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    t_fu_84 <= t_2_fu_672_p3;
                end if;
            end if; 
        end if;
    end process;

    u_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    u_fu_88 <= u_025;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    u_fu_88 <= u_2_fu_679_p3;
                end if;
            end if; 
        end if;
    end process;

    v_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    v_fu_92 <= v_026;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    v_fu_92 <= v_2_fu_686_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln181_15_reg_788 <= add_ln181_15_fu_431_p2;
                add_ln181_reg_783 <= add_ln181_fu_425_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln299_reg_751 <= icmp_ln299_fu_226_p2;
                icmp_ln300_reg_760 <= icmp_ln300_fu_251_p2;
                icmp_ln300_reg_760_pp0_iter1_reg <= icmp_ln300_reg_760;
                tmp_34_reg_793 <= ahbh_fu_195_p2(63 downto 32);
                trunc_ln156_reg_772 <= trunc_ln156_fu_325_p1;
                trunc_ln176_reg_777 <= trunc_ln176_fu_393_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln174_fu_363_p2 <= std_logic_vector(unsigned(zext_ln174_fu_355_p1) + unsigned(zext_ln174_14_fu_359_p1));
    add_ln181_15_fu_431_p2 <= std_logic_vector(unsigned(trunc_ln156_s_fu_411_p4) + unsigned(zext_ln156_14_fu_389_p1));
    add_ln181_fu_425_p2 <= std_logic_vector(unsigned(zext_ln181_fu_421_p1) + unsigned(zext_ln156_15_fu_407_p1));
    add_ln299_3_fu_232_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_6) + unsigned(ap_const_lv3_1));
    add_ln303_fu_560_p2 <= std_logic_vector(unsigned(zext_ln303_fu_552_p1) + unsigned(and_ln_fu_527_p3));
    ah_fu_287_p4 <= mc_q0(63 downto 32);
    ahbh_fu_195_p0 <= zext_ln163_fu_319_p1(32 - 1 downto 0);
    ahbh_fu_195_p1 <= zext_ln161_fu_297_p1(32 - 1 downto 0);
    ahbl_fu_191_p0 <= zext_ln155_8_fu_303_p1(32 - 1 downto 0);
    ahbl_fu_191_p1 <= zext_ln161_fu_297_p1(32 - 1 downto 0);
    al_fu_273_p1 <= mc_q0(32 - 1 downto 0);
    albh_fu_187_p0 <= zext_ln163_fu_319_p1(32 - 1 downto 0);
    albh_fu_187_p1 <= zext_ln155_fu_281_p1(32 - 1 downto 0);
    albl_fu_183_p0 <= zext_ln155_8_fu_303_p1(32 - 1 downto 0);
    albl_fu_183_p1 <= zext_ln155_fu_281_p1(32 - 1 downto 0);
    and_ln105_fu_610_p2 <= (xor_ln303_fu_566_p2 and xor_ln105_s_fu_602_p3);
    and_ln303_3_fu_544_p3 <= (tmp_35_fu_534_p4 & ap_const_lv32_0);
    and_ln_fu_527_p3 <= (tmp_34_reg_793 & ap_const_lv32_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln299_fu_226_p2)
    begin
        if (((icmp_ln299_fu_226_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_96)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_6 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_j_6 <= j_fu_96;
        end if; 
    end process;

    bh_fu_309_p4 <= p503p1_1_q0(63 downto 32);
    bit_sel_fu_584_p3 <= tempReg_10_fu_572_p2(63 downto 63);
    bl_fu_277_p1 <= p503p1_1_q0(32 - 1 downto 0);
    carry_19_fu_656_p2 <= (tmp_47_fu_648_p3 or tmp_46_fu_616_p3);
    carry_fu_515_p3 <= xor_ln105_60_fu_509_p2(63 downto 63);
    icmp_ln299_fu_226_p2 <= "1" when (ap_sig_allocacmp_j_6 = i_7) else "0";
    icmp_ln300_fu_251_p2 <= "1" when (unsigned(zext_ln299_fu_222_p1) < unsigned(add_ln299)) else "0";
    mc_address0 <= zext_ln301_1_fu_246_p1(4 - 1 downto 0);
    mc_ce0 <= mc_ce0_local;

    mc_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mc_ce0_local <= ap_const_logic_1;
        else 
            mc_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln105_11_fu_636_p2 <= (xor_ln105_63_fu_630_p2 or xor_ln105_62_fu_624_p2);
    or_ln105_fu_503_p2 <= (xor_ln105_fu_491_p2 or xor_ln105_59_fu_497_p2);
    p503p1_1_address0 <= zext_ln301_fu_263_p1(3 - 1 downto 0);

    p503p1_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p503p1_1_ce0_local <= ap_const_logic_1;
        else 
            p503p1_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln_fu_456_p3 <= (trunc_ln176_reg_777 & ap_const_lv32_0);
    sub_ln301_fu_257_p2 <= std_logic_vector(unsigned(empty) - unsigned(ap_sig_allocacmp_j_6));
    t_12_fu_666_p2 <= std_logic_vector(unsigned(t_fu_84) + unsigned(zext_ln304_fu_662_p1));
    t_2_fu_672_p3 <= 
        t_12_fu_666_p2 when (icmp_ln300_reg_760_pp0_iter1_reg(0) = '1') else 
        t_fu_84;
    t_out <= t_fu_84;

    t_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln299_reg_751, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((icmp_ln299_reg_751 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            t_out_ap_vld <= ap_const_logic_1;
        else 
            t_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tempReg_10_fu_572_p2 <= std_logic_vector(unsigned(xor_ln303_fu_566_p2) + unsigned(zext_ln105_fu_523_p1));
    tempReg_fu_463_p3 <= (trunc_ln176_reg_777 & trunc_ln156_reg_772);
    temp_13_fu_475_p2 <= std_logic_vector(unsigned(zext_ln181_15_fu_472_p1) + unsigned(zext_ln181_14_fu_469_p1));
    temp_fu_373_p2 <= std_logic_vector(unsigned(zext_ln174_15_fu_369_p1) + unsigned(zext_ln156_fu_351_p1));
    tmp_31_fu_341_p4 <= albl_fu_183_p2(63 downto 32);
    tmp_32_fu_379_p4 <= temp_fu_373_p2(33 downto 32);
    tmp_33_fu_397_p4 <= ahbl_fu_191_p2(63 downto 32);
    tmp_35_fu_534_p4 <= temp_13_fu_475_p2(33 downto 32);
    tmp_46_fu_616_p3 <= and_ln105_fu_610_p2(63 downto 63);
    tmp_47_fu_648_p3 <= xor_ln105_64_fu_642_p2(63 downto 63);
    tmp_s_fu_238_p3 <= (mc_offset1 & ap_sig_allocacmp_j_6);
    trunc_ln105_fu_598_p1 <= tempReg_10_fu_572_p2(63 - 1 downto 0);
    trunc_ln155_fu_481_p1 <= temp_13_fu_475_p2(32 - 1 downto 0);
    trunc_ln156_31_fu_329_p1 <= albh_fu_187_p2(32 - 1 downto 0);
    trunc_ln156_32_fu_333_p1 <= ahbl_fu_191_p2(32 - 1 downto 0);
    trunc_ln156_33_fu_337_p1 <= ahbh_fu_195_p2(32 - 1 downto 0);
    trunc_ln156_fu_325_p1 <= albl_fu_183_p2(32 - 1 downto 0);
    trunc_ln156_s_fu_411_p4 <= albh_fu_187_p2(63 downto 32);
    trunc_ln176_fu_393_p1 <= temp_fu_373_p2(32 - 1 downto 0);
    u_27_fu_578_p2 <= std_logic_vector(unsigned(tempReg_10_fu_572_p2) + unsigned(u_fu_88));
    u_29_out <= u_fu_88;

    u_29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln299_reg_751, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((icmp_ln299_reg_751 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            u_29_out_ap_vld <= ap_const_logic_1;
        else 
            u_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    u_2_fu_679_p3 <= 
        u_27_fu_578_p2 when (icmp_ln300_reg_760_pp0_iter1_reg(0) = '1') else 
        u_fu_88;
    v_2_fu_686_p3 <= 
        v_34_fu_485_p2 when (icmp_ln300_reg_760_pp0_iter1_reg(0) = '1') else 
        v_fu_92;
    v_34_fu_485_p2 <= std_logic_vector(unsigned(tempReg_fu_463_p3) + unsigned(v_fu_92));
    v_35_out <= v_fu_92;

    v_35_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln299_reg_751, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((icmp_ln299_reg_751 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            v_35_out_ap_vld <= ap_const_logic_1;
        else 
            v_35_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln105_59_fu_497_p2 <= (v_fu_92 xor shl_ln_fu_456_p3);
    xor_ln105_60_fu_509_p2 <= (v_34_fu_485_p2 xor or_ln105_fu_503_p2);
    xor_ln105_61_fu_592_p2 <= (bit_sel_fu_584_p3 xor ap_const_lv1_1);
    xor_ln105_62_fu_624_p2 <= (u_27_fu_578_p2 xor tempReg_10_fu_572_p2);
    xor_ln105_63_fu_630_p2 <= (u_fu_88 xor tempReg_10_fu_572_p2);
    xor_ln105_64_fu_642_p2 <= (u_27_fu_578_p2 xor or_ln105_11_fu_636_p2);
    xor_ln105_fu_491_p2 <= (v_34_fu_485_p2 xor shl_ln_fu_456_p3);
    xor_ln105_s_fu_602_p3 <= (xor_ln105_61_fu_592_p2 & trunc_ln105_fu_598_p1);
    xor_ln303_fu_566_p2 <= (zext_ln303_4_fu_556_p1 xor add_ln303_fu_560_p2);
    zext_ln105_fu_523_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(carry_fu_515_p3),64));
    zext_ln155_8_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bl_fu_277_p1),64));
    zext_ln155_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(al_fu_273_p1),64));
    zext_ln156_14_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_fu_379_p4),32));
    zext_ln156_15_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_33_fu_397_p4),33));
    zext_ln156_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_31_fu_341_p4),34));
    zext_ln161_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ah_fu_287_p4),64));
    zext_ln163_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bh_fu_309_p4),64));
    zext_ln174_14_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln156_31_fu_329_p1),33));
    zext_ln174_15_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln174_fu_363_p2),34));
    zext_ln174_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln156_32_fu_333_p1),33));
    zext_ln181_14_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln181_reg_783),34));
    zext_ln181_15_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln181_15_reg_788),34));
    zext_ln181_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln156_33_fu_337_p1),33));
    zext_ln299_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_6),4));
    zext_ln301_1_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_238_p3),64));
    zext_ln301_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln301_fu_257_p2),64));
    zext_ln303_4_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln155_fu_481_p1),64));
    zext_ln303_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln303_3_fu_544_p3),64));
    zext_ln304_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(carry_19_fu_656_p2),64));
end behav;
