set SynModuleInfo {
  {SRCNAME mul_Pipeline_VITIS_LOOP_151_1 MODELNAME mul_Pipeline_VITIS_LOOP_151_1 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_151_1
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_flow_control_loop_pipe_sequential_init RTLNAME test_mul_karatsuba_configurable_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME test_mul_karatsuba_configurable_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_157_2 MODELNAME mul_Pipeline_VITIS_LOOP_157_2 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_157_2}
  {SRCNAME mul_Pipeline_VITIS_LOOP_151_11 MODELNAME mul_Pipeline_VITIS_LOOP_151_11 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_151_11}
  {SRCNAME mul_Pipeline_VITIS_LOOP_157_22 MODELNAME mul_Pipeline_VITIS_LOOP_157_22 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_157_22}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_1 MODELNAME mul_Pipeline_VITIS_LOOP_74_1 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_1
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_partset_128ns_128ns_64ns_32ns_128_1_1 RTLNAME test_mul_karatsuba_configurable_partset_128ns_128ns_64ns_32ns_128_1_1 BINDTYPE op TYPE partset IMPL auto}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_2 MODELNAME mul_Pipeline_VITIS_LOOP_81_2 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_2
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_partselect_64ns_256ns_32ns_64_1_1 RTLNAME test_mul_karatsuba_configurable_partselect_64ns_256ns_32ns_64_1_1 BINDTYPE op TYPE partselect IMPL auto}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_13 MODELNAME mul_Pipeline_VITIS_LOOP_74_13 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_13}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_24 MODELNAME mul_Pipeline_VITIS_LOOP_81_24 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_24}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_1 MODELNAME mul_Pipeline_VITIS_LOOP_56_1 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_1}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_15 MODELNAME mul_Pipeline_VITIS_LOOP_56_15 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_15}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_16 MODELNAME mul_Pipeline_VITIS_LOOP_74_16 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_16}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_27 MODELNAME mul_Pipeline_VITIS_LOOP_81_27 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_27}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_1 MODELNAME mul_Pipeline_VITIS_LOOP_97_1 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_1
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_sparsemux_9_2_64_1_1 RTLNAME test_mul_karatsuba_configurable_sparsemux_9_2_64_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_2 MODELNAME mul_Pipeline_VITIS_LOOP_103_2 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_2}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_3 MODELNAME mul_Pipeline_VITIS_LOOP_113_3 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_3
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_partselect_64ns_1056s_32ns_64_1_1 RTLNAME test_mul_karatsuba_configurable_partselect_64ns_1056s_32ns_64_1_1 BINDTYPE op TYPE partselect IMPL auto}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_151_18 MODELNAME mul_Pipeline_VITIS_LOOP_151_18 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_151_18}
  {SRCNAME mul_Pipeline_VITIS_LOOP_157_29 MODELNAME mul_Pipeline_VITIS_LOOP_157_29 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_157_29}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_110 MODELNAME mul_Pipeline_VITIS_LOOP_74_110 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_110}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_211 MODELNAME mul_Pipeline_VITIS_LOOP_81_211 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_211}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_112 MODELNAME mul_Pipeline_VITIS_LOOP_74_112 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_112}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_213 MODELNAME mul_Pipeline_VITIS_LOOP_81_213 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_213}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_114 MODELNAME mul_Pipeline_VITIS_LOOP_56_114 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_114}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_115 MODELNAME mul_Pipeline_VITIS_LOOP_56_115 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_115}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_116 MODELNAME mul_Pipeline_VITIS_LOOP_74_116 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_116}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_217 MODELNAME mul_Pipeline_VITIS_LOOP_81_217 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_217}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_118 MODELNAME mul_Pipeline_VITIS_LOOP_97_118 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_118}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_219 MODELNAME mul_Pipeline_VITIS_LOOP_103_219 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_219}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_320 MODELNAME mul_Pipeline_VITIS_LOOP_113_320 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_320}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_121 MODELNAME mul_Pipeline_VITIS_LOOP_56_121 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_121}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_122 MODELNAME mul_Pipeline_VITIS_LOOP_56_122 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_122}
  {SRCNAME mul_Pipeline_VITIS_LOOP_151_123 MODELNAME mul_Pipeline_VITIS_LOOP_151_123 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_151_123}
  {SRCNAME mul_Pipeline_VITIS_LOOP_157_224 MODELNAME mul_Pipeline_VITIS_LOOP_157_224 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_157_224
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_sparsemux_7_2_64_1_1 RTLNAME test_mul_karatsuba_configurable_sparsemux_7_2_64_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_125 MODELNAME mul_Pipeline_VITIS_LOOP_74_125 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_125}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_226 MODELNAME mul_Pipeline_VITIS_LOOP_81_226 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_226}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_127 MODELNAME mul_Pipeline_VITIS_LOOP_74_127 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_127}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_228 MODELNAME mul_Pipeline_VITIS_LOOP_81_228 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_228}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_129 MODELNAME mul_Pipeline_VITIS_LOOP_56_129 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_129}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_130 MODELNAME mul_Pipeline_VITIS_LOOP_56_130 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_130}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_131 MODELNAME mul_Pipeline_VITIS_LOOP_74_131 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_131}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_232 MODELNAME mul_Pipeline_VITIS_LOOP_81_232 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_232}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_133 MODELNAME mul_Pipeline_VITIS_LOOP_97_133 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_133}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_234 MODELNAME mul_Pipeline_VITIS_LOOP_103_234 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_234}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_335 MODELNAME mul_Pipeline_VITIS_LOOP_113_335 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_335}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_136 MODELNAME mul_Pipeline_VITIS_LOOP_97_136 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_136}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_237 MODELNAME mul_Pipeline_VITIS_LOOP_103_237 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_237}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_338 MODELNAME mul_Pipeline_VITIS_LOOP_113_338 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_338}
  {SRCNAME mul MODELNAME mul RTLNAME test_mul_karatsuba_configurable_mul
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_mul_128ns_128ns_256_1_1 RTLNAME test_mul_karatsuba_configurable_mul_128ns_128ns_256_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME test_mul_karatsuba_configurable_mul_z1_RAM_AUTO_1R1W RTLNAME test_mul_karatsuba_configurable_mul_z1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME test_mul_karatsuba_configurable_mul_z0_RAM_AUTO_1R1W RTLNAME test_mul_karatsuba_configurable_mul_z0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME test_mul_karatsuba_configurable_mul_z1_3_RAM_AUTO_1R1W RTLNAME test_mul_karatsuba_configurable_mul_z1_3_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME mul.1 MODELNAME mul_1 RTLNAME test_mul_karatsuba_configurable_mul_1}
  {SRCNAME test_mul_karatsuba_configurable MODELNAME test_mul_karatsuba_configurable RTLNAME test_mul_karatsuba_configurable IS_TOP 1
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_control_s_axi RTLNAME test_mul_karatsuba_configurable_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
