// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sikep503_kem_enc_hw_fpadd503_83 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t1_i209_0_address0,
        t1_i209_0_ce0,
        t1_i209_0_q0,
        t1_i209_1_address0,
        t1_i209_1_ce0,
        t1_i209_1_q0,
        t1_i209_2_address0,
        t1_i209_2_ce0,
        t1_i209_2_q0,
        t1_i209_3_address0,
        t1_i209_3_ce0,
        t1_i209_3_q0,
        t1_i209_4_address0,
        t1_i209_4_ce0,
        t1_i209_4_q0,
        t1_i209_5_address0,
        t1_i209_5_ce0,
        t1_i209_5_q0,
        t1_i209_6_address0,
        t1_i209_6_ce0,
        t1_i209_6_q0,
        t1_i209_7_address0,
        t1_i209_7_ce0,
        t1_i209_7_q0,
        t0_i208_0_address0,
        t0_i208_0_ce0,
        t0_i208_0_we0,
        t0_i208_0_d0,
        t0_i208_0_address1,
        t0_i208_0_ce1,
        t0_i208_0_q1,
        t0_i208_1_address0,
        t0_i208_1_ce0,
        t0_i208_1_we0,
        t0_i208_1_d0,
        t0_i208_1_address1,
        t0_i208_1_ce1,
        t0_i208_1_q1,
        t0_i208_2_address0,
        t0_i208_2_ce0,
        t0_i208_2_we0,
        t0_i208_2_d0,
        t0_i208_2_address1,
        t0_i208_2_ce1,
        t0_i208_2_q1,
        t0_i208_3_address0,
        t0_i208_3_ce0,
        t0_i208_3_we0,
        t0_i208_3_d0,
        t0_i208_3_address1,
        t0_i208_3_ce1,
        t0_i208_3_q1,
        t0_i208_4_address0,
        t0_i208_4_ce0,
        t0_i208_4_we0,
        t0_i208_4_d0,
        t0_i208_4_address1,
        t0_i208_4_ce1,
        t0_i208_4_q1,
        t0_i208_5_address0,
        t0_i208_5_ce0,
        t0_i208_5_we0,
        t0_i208_5_d0,
        t0_i208_5_address1,
        t0_i208_5_ce1,
        t0_i208_5_q1,
        t0_i208_6_address0,
        t0_i208_6_ce0,
        t0_i208_6_we0,
        t0_i208_6_d0,
        t0_i208_6_address1,
        t0_i208_6_ce1,
        t0_i208_6_q1,
        t0_i208_7_address0,
        t0_i208_7_ce0,
        t0_i208_7_we0,
        t0_i208_7_d0,
        t0_i208_7_address1,
        t0_i208_7_ce1,
        t0_i208_7_q1
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] t1_i209_0_address0;
output   t1_i209_0_ce0;
input  [63:0] t1_i209_0_q0;
output  [0:0] t1_i209_1_address0;
output   t1_i209_1_ce0;
input  [63:0] t1_i209_1_q0;
output  [0:0] t1_i209_2_address0;
output   t1_i209_2_ce0;
input  [63:0] t1_i209_2_q0;
output  [0:0] t1_i209_3_address0;
output   t1_i209_3_ce0;
input  [63:0] t1_i209_3_q0;
output  [0:0] t1_i209_4_address0;
output   t1_i209_4_ce0;
input  [63:0] t1_i209_4_q0;
output  [0:0] t1_i209_5_address0;
output   t1_i209_5_ce0;
input  [63:0] t1_i209_5_q0;
output  [0:0] t1_i209_6_address0;
output   t1_i209_6_ce0;
input  [63:0] t1_i209_6_q0;
output  [0:0] t1_i209_7_address0;
output   t1_i209_7_ce0;
input  [63:0] t1_i209_7_q0;
output  [0:0] t0_i208_0_address0;
output   t0_i208_0_ce0;
output   t0_i208_0_we0;
output  [63:0] t0_i208_0_d0;
output  [0:0] t0_i208_0_address1;
output   t0_i208_0_ce1;
input  [63:0] t0_i208_0_q1;
output  [0:0] t0_i208_1_address0;
output   t0_i208_1_ce0;
output   t0_i208_1_we0;
output  [63:0] t0_i208_1_d0;
output  [0:0] t0_i208_1_address1;
output   t0_i208_1_ce1;
input  [63:0] t0_i208_1_q1;
output  [0:0] t0_i208_2_address0;
output   t0_i208_2_ce0;
output   t0_i208_2_we0;
output  [63:0] t0_i208_2_d0;
output  [0:0] t0_i208_2_address1;
output   t0_i208_2_ce1;
input  [63:0] t0_i208_2_q1;
output  [0:0] t0_i208_3_address0;
output   t0_i208_3_ce0;
output   t0_i208_3_we0;
output  [63:0] t0_i208_3_d0;
output  [0:0] t0_i208_3_address1;
output   t0_i208_3_ce1;
input  [63:0] t0_i208_3_q1;
output  [0:0] t0_i208_4_address0;
output   t0_i208_4_ce0;
output   t0_i208_4_we0;
output  [63:0] t0_i208_4_d0;
output  [0:0] t0_i208_4_address1;
output   t0_i208_4_ce1;
input  [63:0] t0_i208_4_q1;
output  [0:0] t0_i208_5_address0;
output   t0_i208_5_ce0;
output   t0_i208_5_we0;
output  [63:0] t0_i208_5_d0;
output  [0:0] t0_i208_5_address1;
output   t0_i208_5_ce1;
input  [63:0] t0_i208_5_q1;
output  [0:0] t0_i208_6_address0;
output   t0_i208_6_ce0;
output   t0_i208_6_we0;
output  [63:0] t0_i208_6_d0;
output  [0:0] t0_i208_6_address1;
output   t0_i208_6_ce1;
input  [63:0] t0_i208_6_q1;
output  [0:0] t0_i208_7_address0;
output   t0_i208_7_ce0;
output   t0_i208_7_we0;
output  [63:0] t0_i208_7_d0;
output  [0:0] t0_i208_7_address1;
output   t0_i208_7_ce1;
input  [63:0] t0_i208_7_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] t0_i208_0_address0;
reg t0_i208_0_ce0;
reg t0_i208_0_we0;
reg[63:0] t0_i208_0_d0;
reg[0:0] t0_i208_0_address1;
reg t0_i208_0_ce1;
reg[0:0] t0_i208_1_address0;
reg t0_i208_1_ce0;
reg t0_i208_1_we0;
reg[63:0] t0_i208_1_d0;
reg[0:0] t0_i208_1_address1;
reg t0_i208_1_ce1;
reg[0:0] t0_i208_2_address0;
reg t0_i208_2_ce0;
reg t0_i208_2_we0;
reg[63:0] t0_i208_2_d0;
reg[0:0] t0_i208_2_address1;
reg t0_i208_2_ce1;
reg[0:0] t0_i208_3_address0;
reg t0_i208_3_ce0;
reg t0_i208_3_we0;
reg[63:0] t0_i208_3_d0;
reg[0:0] t0_i208_3_address1;
reg t0_i208_3_ce1;
reg[0:0] t0_i208_4_address0;
reg t0_i208_4_ce0;
reg t0_i208_4_we0;
reg[63:0] t0_i208_4_d0;
reg[0:0] t0_i208_4_address1;
reg t0_i208_4_ce1;
reg[0:0] t0_i208_5_address0;
reg t0_i208_5_ce0;
reg t0_i208_5_we0;
reg[63:0] t0_i208_5_d0;
reg[0:0] t0_i208_5_address1;
reg t0_i208_5_ce1;
reg[0:0] t0_i208_6_address0;
reg t0_i208_6_ce0;
reg t0_i208_6_we0;
reg[63:0] t0_i208_6_d0;
reg[0:0] t0_i208_6_address1;
reg t0_i208_6_ce1;
reg[0:0] t0_i208_7_address0;
reg t0_i208_7_ce0;
reg t0_i208_7_we0;
reg[63:0] t0_i208_7_d0;
reg[0:0] t0_i208_7_address1;
reg t0_i208_7_ce1;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] t1_i209_0_load_reg_292;
wire    ap_CS_fsm_state2;
reg   [63:0] t1_i209_1_load_reg_297;
reg   [63:0] t1_i209_2_load_reg_302;
reg   [63:0] t1_i209_3_load_reg_307;
reg   [63:0] t1_i209_4_load_reg_312;
reg   [63:0] t1_i209_5_load_reg_317;
reg   [63:0] t1_i209_6_load_reg_322;
reg   [63:0] t1_i209_7_load_reg_327;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_done;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_idle;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_ready;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_d0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_done;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_idle;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_ready;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_carry_out;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_carry_out_ap_vld;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_done;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_idle;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_ready;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_ce1;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_address0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_ce0;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_we0;
wire   [63:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_d0;
wire   [0:0] grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_address1;
wire    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_ce1;
reg    grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    t1_i209_0_ce0_local;
reg    t1_i209_1_ce0_local;
reg    t1_i209_2_ce0_local;
reg    t1_i209_3_ce0_local;
reg    t1_i209_4_ce0_local;
reg    t1_i209_5_ce0_local;
reg    t1_i209_6_ce0_local;
reg    t1_i209_7_ce0_local;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start_reg = 1'b0;
#0 grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start_reg = 1'b0;
#0 grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start_reg = 1'b0;
end

sikep503_kem_enc_hw_fpadd503_83_Pipeline_VITIS_LOOP_33_1 grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start),
    .ap_done(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_done),
    .ap_idle(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_idle),
    .ap_ready(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_ready),
    .t0_i208_0_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_address0),
    .t0_i208_0_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_ce0),
    .t0_i208_0_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_we0),
    .t0_i208_0_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_d0),
    .t0_i208_1_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_address0),
    .t0_i208_1_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_ce0),
    .t0_i208_1_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_we0),
    .t0_i208_1_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_d0),
    .t0_i208_2_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_address0),
    .t0_i208_2_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_ce0),
    .t0_i208_2_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_we0),
    .t0_i208_2_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_d0),
    .t0_i208_3_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_address0),
    .t0_i208_3_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_ce0),
    .t0_i208_3_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_we0),
    .t0_i208_3_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_d0),
    .t0_i208_4_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_address0),
    .t0_i208_4_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_ce0),
    .t0_i208_4_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_we0),
    .t0_i208_4_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_d0),
    .t0_i208_5_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_address0),
    .t0_i208_5_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_ce0),
    .t0_i208_5_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_we0),
    .t0_i208_5_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_d0),
    .t0_i208_6_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_address0),
    .t0_i208_6_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_ce0),
    .t0_i208_6_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_we0),
    .t0_i208_6_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_d0),
    .t0_i208_7_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_address0),
    .t0_i208_7_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_ce0),
    .t0_i208_7_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_we0),
    .t0_i208_7_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_d0),
    .t1_i209_0_load(t1_i209_0_load_reg_292),
    .t1_i209_1_load(t1_i209_1_load_reg_297),
    .t1_i209_2_load(t1_i209_2_load_reg_302),
    .t1_i209_3_load(t1_i209_3_load_reg_307),
    .t1_i209_4_load(t1_i209_4_load_reg_312),
    .t1_i209_5_load(t1_i209_5_load_reg_317),
    .t1_i209_6_load(t1_i209_6_load_reg_322),
    .t1_i209_7_load(t1_i209_7_load_reg_327)
);

sikep503_kem_enc_hw_fpadd503_83_Pipeline_VITIS_LOOP_39_2 grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start),
    .ap_done(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_done),
    .ap_idle(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_idle),
    .ap_ready(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_ready),
    .t0_i208_0_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_address0),
    .t0_i208_0_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_ce0),
    .t0_i208_0_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_we0),
    .t0_i208_0_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_d0),
    .t0_i208_0_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_address1),
    .t0_i208_0_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_ce1),
    .t0_i208_0_q1(t0_i208_0_q1),
    .t0_i208_1_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_address0),
    .t0_i208_1_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_ce0),
    .t0_i208_1_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_we0),
    .t0_i208_1_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_d0),
    .t0_i208_1_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_address1),
    .t0_i208_1_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_ce1),
    .t0_i208_1_q1(t0_i208_1_q1),
    .t0_i208_2_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_address0),
    .t0_i208_2_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_ce0),
    .t0_i208_2_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_we0),
    .t0_i208_2_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_d0),
    .t0_i208_2_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_address1),
    .t0_i208_2_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_ce1),
    .t0_i208_2_q1(t0_i208_2_q1),
    .t0_i208_3_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_address0),
    .t0_i208_3_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_ce0),
    .t0_i208_3_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_we0),
    .t0_i208_3_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_d0),
    .t0_i208_3_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_address1),
    .t0_i208_3_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_ce1),
    .t0_i208_3_q1(t0_i208_3_q1),
    .t0_i208_4_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_address0),
    .t0_i208_4_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_ce0),
    .t0_i208_4_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_we0),
    .t0_i208_4_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_d0),
    .t0_i208_4_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_address1),
    .t0_i208_4_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_ce1),
    .t0_i208_4_q1(t0_i208_4_q1),
    .t0_i208_5_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_address0),
    .t0_i208_5_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_ce0),
    .t0_i208_5_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_we0),
    .t0_i208_5_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_d0),
    .t0_i208_5_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_address1),
    .t0_i208_5_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_ce1),
    .t0_i208_5_q1(t0_i208_5_q1),
    .t0_i208_6_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_address0),
    .t0_i208_6_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_ce0),
    .t0_i208_6_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_we0),
    .t0_i208_6_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_d0),
    .t0_i208_6_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_address1),
    .t0_i208_6_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_ce1),
    .t0_i208_6_q1(t0_i208_6_q1),
    .t0_i208_7_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_address0),
    .t0_i208_7_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_ce0),
    .t0_i208_7_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_we0),
    .t0_i208_7_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_d0),
    .t0_i208_7_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_address1),
    .t0_i208_7_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_ce1),
    .t0_i208_7_q1(t0_i208_7_q1),
    .carry_out(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_carry_out),
    .carry_out_ap_vld(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_carry_out_ap_vld)
);

sikep503_kem_enc_hw_fpadd503_83_Pipeline_VITIS_LOOP_46_3 grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start),
    .ap_done(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_done),
    .ap_idle(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_idle),
    .ap_ready(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_ready),
    .t0_i208_0_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_address0),
    .t0_i208_0_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_ce0),
    .t0_i208_0_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_we0),
    .t0_i208_0_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_d0),
    .t0_i208_0_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_address1),
    .t0_i208_0_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_ce1),
    .t0_i208_0_q1(t0_i208_0_q1),
    .t0_i208_1_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_address0),
    .t0_i208_1_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_ce0),
    .t0_i208_1_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_we0),
    .t0_i208_1_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_d0),
    .t0_i208_1_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_address1),
    .t0_i208_1_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_ce1),
    .t0_i208_1_q1(t0_i208_1_q1),
    .t0_i208_2_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_address0),
    .t0_i208_2_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_ce0),
    .t0_i208_2_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_we0),
    .t0_i208_2_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_d0),
    .t0_i208_2_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_address1),
    .t0_i208_2_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_ce1),
    .t0_i208_2_q1(t0_i208_2_q1),
    .t0_i208_3_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_address0),
    .t0_i208_3_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_ce0),
    .t0_i208_3_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_we0),
    .t0_i208_3_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_d0),
    .t0_i208_3_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_address1),
    .t0_i208_3_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_ce1),
    .t0_i208_3_q1(t0_i208_3_q1),
    .t0_i208_4_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_address0),
    .t0_i208_4_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_ce0),
    .t0_i208_4_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_we0),
    .t0_i208_4_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_d0),
    .t0_i208_4_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_address1),
    .t0_i208_4_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_ce1),
    .t0_i208_4_q1(t0_i208_4_q1),
    .t0_i208_5_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_address0),
    .t0_i208_5_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_ce0),
    .t0_i208_5_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_we0),
    .t0_i208_5_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_d0),
    .t0_i208_5_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_address1),
    .t0_i208_5_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_ce1),
    .t0_i208_5_q1(t0_i208_5_q1),
    .t0_i208_6_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_address0),
    .t0_i208_6_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_ce0),
    .t0_i208_6_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_we0),
    .t0_i208_6_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_d0),
    .t0_i208_6_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_address1),
    .t0_i208_6_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_ce1),
    .t0_i208_6_q1(t0_i208_6_q1),
    .t0_i208_7_address0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_address0),
    .t0_i208_7_ce0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_ce0),
    .t0_i208_7_we0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_we0),
    .t0_i208_7_d0(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_d0),
    .t0_i208_7_address1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_address1),
    .t0_i208_7_ce1(grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_ce1),
    .t0_i208_7_q1(t0_i208_7_q1),
    .sext_ln30(grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_carry_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_ready == 1'b1)) begin
            grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start_reg <= 1'b1;
        end else if ((grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_ready == 1'b1)) begin
            grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start_reg <= 1'b1;
        end else if ((grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_ready == 1'b1)) begin
            grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        t1_i209_0_load_reg_292 <= t1_i209_0_q0;
        t1_i209_1_load_reg_297 <= t1_i209_1_q0;
        t1_i209_2_load_reg_302 <= t1_i209_2_q0;
        t1_i209_3_load_reg_307 <= t1_i209_3_q0;
        t1_i209_4_load_reg_312 <= t1_i209_4_q0;
        t1_i209_5_load_reg_317 <= t1_i209_5_q0;
        t1_i209_6_load_reg_322 <= t1_i209_6_q0;
        t1_i209_7_load_reg_327 <= t1_i209_7_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_0_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_0_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_0_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_address0;
    end else begin
        t0_i208_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_0_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_0_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_address1;
    end else begin
        t0_i208_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_0_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_0_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_0_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_ce0;
    end else begin
        t0_i208_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_0_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_0_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_ce1;
    end else begin
        t0_i208_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_0_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_0_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_0_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_d0;
    end else begin
        t0_i208_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_0_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_0_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_0_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_0_we0;
    end else begin
        t0_i208_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_1_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_1_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_1_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_address0;
    end else begin
        t0_i208_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_1_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_1_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_address1;
    end else begin
        t0_i208_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_1_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_1_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_1_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_ce0;
    end else begin
        t0_i208_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_1_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_1_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_ce1;
    end else begin
        t0_i208_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_1_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_1_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_1_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_d0;
    end else begin
        t0_i208_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_1_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_1_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_1_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_1_we0;
    end else begin
        t0_i208_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_2_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_2_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_2_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_address0;
    end else begin
        t0_i208_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_2_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_2_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_address1;
    end else begin
        t0_i208_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_2_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_2_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_2_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_ce0;
    end else begin
        t0_i208_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_2_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_2_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_ce1;
    end else begin
        t0_i208_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_2_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_2_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_2_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_d0;
    end else begin
        t0_i208_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_2_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_2_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_2_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_2_we0;
    end else begin
        t0_i208_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_3_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_3_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_3_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_address0;
    end else begin
        t0_i208_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_3_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_3_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_address1;
    end else begin
        t0_i208_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_3_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_3_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_3_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_ce0;
    end else begin
        t0_i208_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_3_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_3_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_ce1;
    end else begin
        t0_i208_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_3_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_3_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_3_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_d0;
    end else begin
        t0_i208_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_3_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_3_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_3_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_3_we0;
    end else begin
        t0_i208_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_4_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_4_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_4_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_address0;
    end else begin
        t0_i208_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_4_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_4_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_address1;
    end else begin
        t0_i208_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_4_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_4_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_4_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_ce0;
    end else begin
        t0_i208_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_4_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_4_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_ce1;
    end else begin
        t0_i208_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_4_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_4_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_4_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_d0;
    end else begin
        t0_i208_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_4_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_4_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_4_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_4_we0;
    end else begin
        t0_i208_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_5_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_5_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_5_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_address0;
    end else begin
        t0_i208_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_5_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_5_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_address1;
    end else begin
        t0_i208_5_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_5_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_5_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_5_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_ce0;
    end else begin
        t0_i208_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_5_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_5_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_ce1;
    end else begin
        t0_i208_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_5_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_5_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_5_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_d0;
    end else begin
        t0_i208_5_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_5_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_5_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_5_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_5_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_5_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_5_we0;
    end else begin
        t0_i208_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_6_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_6_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_6_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_address0;
    end else begin
        t0_i208_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_6_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_6_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_address1;
    end else begin
        t0_i208_6_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_6_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_6_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_6_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_ce0;
    end else begin
        t0_i208_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_6_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_6_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_ce1;
    end else begin
        t0_i208_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_6_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_6_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_6_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_d0;
    end else begin
        t0_i208_6_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_6_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_6_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_6_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_6_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_6_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_6_we0;
    end else begin
        t0_i208_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_7_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_7_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_7_address0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_address0;
    end else begin
        t0_i208_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_7_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_7_address1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_address1;
    end else begin
        t0_i208_7_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_7_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_7_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_7_ce0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_ce0;
    end else begin
        t0_i208_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_7_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_7_ce1 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_ce1;
    end else begin
        t0_i208_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_7_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_d0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_7_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_7_d0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_d0;
    end else begin
        t0_i208_7_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t0_i208_7_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_t0_i208_7_we0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        t0_i208_7_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_t0_i208_7_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t0_i208_7_we0 = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_t0_i208_7_we0;
    end else begin
        t0_i208_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t1_i209_0_ce0_local = 1'b1;
    end else begin
        t1_i209_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t1_i209_1_ce0_local = 1'b1;
    end else begin
        t1_i209_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t1_i209_2_ce0_local = 1'b1;
    end else begin
        t1_i209_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t1_i209_3_ce0_local = 1'b1;
    end else begin
        t1_i209_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t1_i209_4_ce0_local = 1'b1;
    end else begin
        t1_i209_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t1_i209_5_ce0_local = 1'b1;
    end else begin
        t1_i209_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t1_i209_6_ce0_local = 1'b1;
    end else begin
        t1_i209_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t1_i209_7_ce0_local = 1'b1;
    end else begin
        t1_i209_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start = grp_fpadd503_83_Pipeline_VITIS_LOOP_33_1_fu_160_ap_start_reg;

assign grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start = grp_fpadd503_83_Pipeline_VITIS_LOOP_39_2_fu_196_ap_start_reg;

assign grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start = grp_fpadd503_83_Pipeline_VITIS_LOOP_46_3_fu_219_ap_start_reg;

assign t1_i209_0_address0 = 64'd1;

assign t1_i209_0_ce0 = t1_i209_0_ce0_local;

assign t1_i209_1_address0 = 64'd1;

assign t1_i209_1_ce0 = t1_i209_1_ce0_local;

assign t1_i209_2_address0 = 64'd1;

assign t1_i209_2_ce0 = t1_i209_2_ce0_local;

assign t1_i209_3_address0 = 64'd1;

assign t1_i209_3_ce0 = t1_i209_3_ce0_local;

assign t1_i209_4_address0 = 64'd1;

assign t1_i209_4_ce0 = t1_i209_4_ce0_local;

assign t1_i209_5_address0 = 64'd1;

assign t1_i209_5_ce0 = t1_i209_5_ce0_local;

assign t1_i209_6_address0 = 64'd1;

assign t1_i209_6_ce0 = t1_i209_6_ce0_local;

assign t1_i209_7_address0 = 64'd1;

assign t1_i209_7_ce0 = t1_i209_7_ce0_local;

endmodule //sikep503_kem_enc_hw_fpadd503_83
