// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sikep503_kem_enc_hw_fpadd503_41 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C24_0_address0,
        C24_0_ce0,
        C24_0_we0,
        C24_0_d0,
        C24_0_q0,
        C24_1_address0,
        C24_1_ce0,
        C24_1_we0,
        C24_1_d0,
        C24_1_q0,
        C24_2_address0,
        C24_2_ce0,
        C24_2_we0,
        C24_2_d0,
        C24_2_q0,
        C24_3_address0,
        C24_3_ce0,
        C24_3_we0,
        C24_3_d0,
        C24_3_q0,
        C24_4_address0,
        C24_4_ce0,
        C24_4_we0,
        C24_4_d0,
        C24_4_q0,
        C24_5_address0,
        C24_5_ce0,
        C24_5_we0,
        C24_5_d0,
        C24_5_q0,
        C24_6_address0,
        C24_6_ce0,
        C24_6_we0,
        C24_6_d0,
        C24_6_q0,
        C24_7_address0,
        C24_7_ce0,
        C24_7_we0,
        C24_7_d0,
        C24_7_q0,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] C24_0_address0;
output   C24_0_ce0;
output   C24_0_we0;
output  [63:0] C24_0_d0;
input  [63:0] C24_0_q0;
output  [0:0] C24_1_address0;
output   C24_1_ce0;
output   C24_1_we0;
output  [63:0] C24_1_d0;
input  [63:0] C24_1_q0;
output  [0:0] C24_2_address0;
output   C24_2_ce0;
output   C24_2_we0;
output  [63:0] C24_2_d0;
input  [63:0] C24_2_q0;
output  [0:0] C24_3_address0;
output   C24_3_ce0;
output   C24_3_we0;
output  [63:0] C24_3_d0;
input  [63:0] C24_3_q0;
output  [0:0] C24_4_address0;
output   C24_4_ce0;
output   C24_4_we0;
output  [63:0] C24_4_d0;
input  [63:0] C24_4_q0;
output  [0:0] C24_5_address0;
output   C24_5_ce0;
output   C24_5_we0;
output  [63:0] C24_5_d0;
input  [63:0] C24_5_q0;
output  [0:0] C24_6_address0;
output   C24_6_ce0;
output   C24_6_we0;
output  [63:0] C24_6_d0;
input  [63:0] C24_6_q0;
output  [0:0] C24_7_address0;
output   C24_7_ce0;
output   C24_7_we0;
output  [63:0] C24_7_d0;
input  [63:0] C24_7_q0;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] C24_0_addr_reg_1278;
wire   [0:0] C24_1_addr_reg_1283;
wire   [0:0] C24_2_addr_reg_1288;
wire   [0:0] C24_3_addr_reg_1293;
wire   [0:0] C24_4_addr_reg_1298;
wire   [0:0] C24_5_addr_reg_1303;
wire   [0:0] C24_6_addr_reg_1308;
wire   [0:0] C24_7_addr_reg_1313;
wire    tmp_is_digit_lessthan_ct_fu_188_ap_ready;
wire   [0:0] tmp_is_digit_lessthan_ct_fu_188_ap_return;
wire    tmp_s_is_digit_lessthan_ct_fu_196_ap_ready;
wire   [0:0] tmp_s_is_digit_lessthan_ct_fu_196_ap_return;
wire    borrowReg_is_digit_lessthan_ct_fu_203_ap_ready;
wire   [0:0] borrowReg_is_digit_lessthan_ct_fu_203_ap_return;
wire    tmp_1276_is_digit_lessthan_ct_fu_210_ap_ready;
wire   [0:0] tmp_1276_is_digit_lessthan_ct_fu_210_ap_return;
wire    tmp_1277_is_digit_lessthan_ct_fu_217_ap_ready;
wire   [0:0] tmp_1277_is_digit_lessthan_ct_fu_217_ap_return;
wire    tmp_1278_is_digit_lessthan_ct_fu_223_ap_ready;
wire   [0:0] tmp_1278_is_digit_lessthan_ct_fu_223_ap_return;
wire    tmp_1279_is_digit_lessthan_ct_fu_229_ap_ready;
wire   [0:0] tmp_1279_is_digit_lessthan_ct_fu_229_ap_return;
wire    tmp_1280_is_digit_lessthan_ct_fu_236_ap_ready;
wire   [0:0] tmp_1280_is_digit_lessthan_ct_fu_236_ap_return;
wire    tmp_1281_is_digit_lessthan_ct_fu_242_ap_ready;
wire   [0:0] tmp_1281_is_digit_lessthan_ct_fu_242_ap_return;
wire    tmp_1282_is_digit_lessthan_ct_fu_248_ap_ready;
wire   [0:0] tmp_1282_is_digit_lessthan_ct_fu_248_ap_return;
wire    tmp_1283_is_digit_lessthan_ct_fu_255_ap_ready;
wire   [0:0] tmp_1283_is_digit_lessthan_ct_fu_255_ap_return;
wire    tmp_1284_is_digit_lessthan_ct_fu_261_ap_ready;
wire   [0:0] tmp_1284_is_digit_lessthan_ct_fu_261_ap_return;
wire    tmp_1285_is_digit_lessthan_ct_fu_267_ap_ready;
wire   [0:0] tmp_1285_is_digit_lessthan_ct_fu_267_ap_return;
wire    tmp_1286_is_digit_lessthan_ct_fu_274_ap_ready;
wire   [0:0] tmp_1286_is_digit_lessthan_ct_fu_274_ap_return;
wire    tmp_1287_is_digit_lessthan_ct_fu_280_ap_ready;
wire   [0:0] tmp_1287_is_digit_lessthan_ct_fu_280_ap_return;
wire    tmp_1288_is_digit_lessthan_ct_fu_286_ap_ready;
wire   [0:0] tmp_1288_is_digit_lessthan_ct_fu_286_ap_return;
wire    tmp_1289_is_digit_lessthan_ct_fu_293_ap_ready;
wire   [0:0] tmp_1289_is_digit_lessthan_ct_fu_293_ap_return;
wire    tmp_1290_is_digit_lessthan_ct_fu_299_ap_ready;
wire   [0:0] tmp_1290_is_digit_lessthan_ct_fu_299_ap_return;
wire    tmp_1291_is_digit_lessthan_ct_fu_305_ap_ready;
wire   [0:0] tmp_1291_is_digit_lessthan_ct_fu_305_ap_return;
wire    tmp_1292_is_digit_lessthan_ct_fu_312_ap_ready;
wire   [0:0] tmp_1292_is_digit_lessthan_ct_fu_312_ap_return;
wire    tmp_1293_is_digit_lessthan_ct_fu_318_ap_ready;
wire   [0:0] tmp_1293_is_digit_lessthan_ct_fu_318_ap_return;
wire    tmp_1294_is_digit_lessthan_ct_fu_324_ap_ready;
wire   [0:0] tmp_1294_is_digit_lessthan_ct_fu_324_ap_return;
wire    tmp_1295_is_digit_lessthan_ct_fu_331_ap_ready;
wire   [0:0] tmp_1295_is_digit_lessthan_ct_fu_331_ap_return;
wire    tmp_1296_is_digit_lessthan_ct_fu_338_ap_ready;
wire   [0:0] tmp_1296_is_digit_lessthan_ct_fu_338_ap_return;
wire    tmp_1297_is_digit_lessthan_ct_fu_344_ap_ready;
wire   [0:0] tmp_1297_is_digit_lessthan_ct_fu_344_ap_return;
wire    tmp_1298_is_digit_lessthan_ct_fu_350_ap_ready;
wire   [0:0] tmp_1298_is_digit_lessthan_ct_fu_350_ap_return;
wire    tmp_1299_is_digit_lessthan_ct_fu_356_ap_ready;
wire   [0:0] tmp_1299_is_digit_lessthan_ct_fu_356_ap_return;
wire    tmp_1300_is_digit_lessthan_ct_fu_362_ap_ready;
wire   [0:0] tmp_1300_is_digit_lessthan_ct_fu_362_ap_return;
wire    tmp_1301_is_digit_lessthan_ct_fu_368_ap_ready;
wire   [0:0] tmp_1301_is_digit_lessthan_ct_fu_368_ap_return;
wire    tmp_1302_is_digit_lessthan_ct_fu_374_ap_ready;
wire   [0:0] tmp_1302_is_digit_lessthan_ct_fu_374_ap_return;
wire    tmp_1303_is_digit_lessthan_ct_fu_380_ap_ready;
wire   [0:0] tmp_1303_is_digit_lessthan_ct_fu_380_ap_return;
wire    tmp_1304_is_digit_lessthan_ct_fu_386_ap_ready;
wire   [0:0] tmp_1304_is_digit_lessthan_ct_fu_386_ap_return;
wire    tmp_1305_is_digit_lessthan_ct_fu_392_ap_ready;
wire   [0:0] tmp_1305_is_digit_lessthan_ct_fu_392_ap_return;
wire    tmp_1306_is_digit_lessthan_ct_fu_398_ap_ready;
wire   [0:0] tmp_1306_is_digit_lessthan_ct_fu_398_ap_return;
wire    tmp_1307_is_digit_lessthan_ct_fu_404_ap_ready;
wire   [0:0] tmp_1307_is_digit_lessthan_ct_fu_404_ap_return;
wire    tmp_1308_is_digit_lessthan_ct_fu_410_ap_ready;
wire   [0:0] tmp_1308_is_digit_lessthan_ct_fu_410_ap_return;
wire    ap_CS_fsm_state2;
wire   [63:0] shl_ln33_fu_416_p2;
wire   [63:0] tempReg_1643_fu_435_p2;
wire   [63:0] tempReg_1657_fu_447_p2;
wire   [63:0] zext_ln33_fu_430_p1;
wire   [63:0] add_ln33_191_fu_455_p2;
wire   [63:0] tempReg_1658_fu_548_p2;
wire   [63:0] zext_ln33_85_fu_469_p1;
wire   [63:0] add_ln33_193_fu_556_p2;
wire   [63:0] tempReg_1659_fu_649_p2;
wire   [63:0] zext_ln33_86_fu_570_p1;
wire   [63:0] add_ln33_195_fu_657_p2;
wire   [63:0] tempReg_1660_fu_730_p2;
wire   [63:0] zext_ln33_87_fu_671_p1;
wire   [63:0] add_ln33_197_fu_738_p2;
wire   [63:0] tempReg_1661_fu_811_p2;
wire   [63:0] zext_ln33_88_fu_752_p1;
wire   [63:0] add_ln33_199_fu_819_p2;
wire   [63:0] tempReg_1662_fu_892_p2;
wire   [63:0] zext_ln33_89_fu_833_p1;
wire   [63:0] add_ln33_201_fu_900_p2;
wire   [63:0] add_ln33_s_fu_972_p3;
wire   [63:0] add_ln46_fu_1043_p2;
wire   [63:0] tempReg_1670_fu_1062_p2;
wire   [63:0] zext_ln46_fu_1057_p1;
wire   [63:0] sub_ln46_fu_1070_p2;
wire   [63:0] tempReg_1671_fu_1089_p2;
wire   [63:0] zext_ln46_85_fu_1084_p1;
wire   [63:0] sub_ln46_15_fu_1097_p2;
wire   [63:0] tempReg_1672_fu_1116_p2;
wire   [63:0] zext_ln46_86_fu_1111_p1;
wire   [63:0] add_ln46_172_fu_1132_p2;
wire   [63:0] tempReg_1673_fu_1151_p2;
wire   [63:0] zext_ln46_87_fu_1146_p1;
wire   [63:0] add_ln46_174_fu_1167_p2;
wire   [63:0] tempReg_1674_fu_1186_p2;
wire   [63:0] zext_ln46_88_fu_1181_p1;
wire   [63:0] add_ln46_176_fu_1202_p2;
wire   [63:0] tempReg_1675_fu_1221_p2;
wire   [63:0] zext_ln46_89_fu_1216_p1;
wire   [63:0] add_ln46_178_fu_1237_p2;
reg    C24_0_ce0_local;
reg   [0:0] C24_0_address0_local;
reg    C24_0_we0_local;
reg    C24_1_ce0_local;
reg   [0:0] C24_1_address0_local;
reg    C24_1_we0_local;
reg    C24_2_ce0_local;
reg   [0:0] C24_2_address0_local;
reg    C24_2_we0_local;
reg    C24_3_ce0_local;
reg   [0:0] C24_3_address0_local;
reg    C24_3_we0_local;
reg    C24_4_ce0_local;
reg   [0:0] C24_4_address0_local;
reg    C24_4_we0_local;
reg    C24_5_ce0_local;
reg   [0:0] C24_5_address0_local;
reg    C24_5_we0_local;
reg    C24_6_ce0_local;
reg   [0:0] C24_6_address0_local;
reg    C24_6_we0_local;
reg    C24_7_ce0_local;
reg   [0:0] C24_7_address0_local;
reg    C24_7_we0_local;
wire   [63:0] add_ln46_180_fu_1271_p2;
wire   [0:0] carry_fu_424_p2;
wire   [0:0] carry_663_fu_463_p2;
wire   [0:0] bit_sel1_fu_480_p3;
wire   [0:0] xor_ln95_20_fu_488_p2;
wire   [62:0] trunc_ln95_fu_494_p1;
wire   [63:0] tempReg_1663_fu_474_p2;
wire   [63:0] xor_ln_fu_498_p3;
wire   [63:0] or_ln95_fu_506_p2;
wire   [0:0] tmp_1309_fu_512_p3;
wire   [0:0] xor_ln100_fu_520_p2;
wire   [0:0] and_ln39_fu_526_p2;
wire   [63:0] zext_ln39_fu_443_p1;
wire   [0:0] borrowReg_383_fu_532_p2;
wire   [0:0] carry_664_fu_564_p2;
wire   [0:0] bit_sel_fu_581_p3;
wire   [0:0] xor_ln95_fu_589_p2;
wire   [62:0] trunc_ln95_19_fu_595_p1;
wire   [63:0] tempReg_1664_fu_575_p2;
wire   [63:0] xor_ln95_s_fu_599_p3;
wire   [63:0] or_ln95_288_fu_607_p2;
wire   [0:0] tmp_1310_fu_613_p3;
wire   [0:0] xor_ln100_288_fu_621_p2;
wire   [0:0] and_ln39_85_fu_627_p2;
wire   [63:0] zext_ln39_85_fu_544_p1;
wire   [0:0] borrowReg_384_fu_633_p2;
wire   [0:0] carry_665_fu_665_p2;
wire   [63:0] sub_ln95_fu_682_p2;
wire   [63:0] tempReg_1665_fu_676_p2;
wire   [63:0] or_ln95_289_fu_688_p2;
wire   [0:0] tmp_1311_fu_694_p3;
wire   [0:0] xor_ln100_289_fu_702_p2;
wire   [0:0] and_ln39_86_fu_708_p2;
wire   [63:0] zext_ln39_86_fu_645_p1;
wire   [0:0] borrowReg_385_fu_714_p2;
wire   [0:0] carry_666_fu_746_p2;
wire   [63:0] sub_ln95_252_fu_763_p2;
wire   [63:0] tempReg_1666_fu_757_p2;
wire   [63:0] or_ln95_290_fu_769_p2;
wire   [0:0] tmp_1312_fu_775_p3;
wire   [0:0] xor_ln100_290_fu_783_p2;
wire   [0:0] and_ln39_87_fu_789_p2;
wire   [63:0] zext_ln39_87_fu_726_p1;
wire   [0:0] borrowReg_386_fu_795_p2;
wire   [0:0] carry_667_fu_827_p2;
wire   [63:0] sub_ln95_253_fu_844_p2;
wire   [63:0] tempReg_1667_fu_838_p2;
wire   [63:0] or_ln95_291_fu_850_p2;
wire   [0:0] tmp_1313_fu_856_p3;
wire   [0:0] xor_ln100_291_fu_864_p2;
wire   [0:0] and_ln39_88_fu_870_p2;
wire   [63:0] zext_ln39_88_fu_807_p1;
wire   [0:0] borrowReg_387_fu_876_p2;
wire   [63:0] sub_ln95_254_fu_914_p2;
wire   [63:0] tempReg_1668_fu_908_p2;
wire   [63:0] or_ln95_292_fu_920_p2;
wire   [0:0] tmp_1314_fu_926_p3;
wire   [0:0] xor_ln100_292_fu_934_p2;
wire   [0:0] and_ln39_89_fu_940_p2;
wire   [63:0] zext_ln39_89_fu_888_p1;
wire   [0:0] borrowReg_388_fu_946_p2;
wire   [62:0] trunc_ln33_fu_968_p1;
wire   [0:0] or_ln33_83_fu_962_p2;
wire   [63:0] sub_ln95_255_fu_987_p2;
wire   [63:0] tempReg_1669_fu_981_p2;
wire   [63:0] or_ln95_293_fu_993_p2;
wire   [0:0] tmp_1315_fu_999_p3;
wire   [0:0] xor_ln100_293_fu_1007_p2;
wire   [0:0] and_ln39_90_fu_1013_p2;
wire   [63:0] zext_ln39_90_fu_958_p1;
wire   [0:0] borrowReg_389_fu_1019_p2;
wire   [63:0] select_ln46_fu_1035_p3;
wire   [0:0] carry_668_fu_1051_p2;
wire   [63:0] sub_ln39_fu_538_p2;
wire   [63:0] zext_ln41_fu_1031_p1;
wire   [0:0] carry_669_fu_1078_p2;
wire   [63:0] sub_ln39_71_fu_639_p2;
wire   [0:0] carry_670_fu_1105_p2;
wire   [63:0] sub_ln39_72_fu_720_p2;
wire   [63:0] select_ln46_81_fu_1124_p3;
wire   [0:0] carry_671_fu_1140_p2;
wire   [63:0] sub_ln39_73_fu_801_p2;
wire   [63:0] select_ln46_82_fu_1159_p3;
wire   [0:0] carry_672_fu_1175_p2;
wire   [63:0] sub_ln39_74_fu_882_p2;
wire   [63:0] select_ln46_83_fu_1194_p3;
wire   [0:0] carry_673_fu_1210_p2;
wire   [63:0] sub_ln39_75_fu_952_p2;
wire   [63:0] select_ln46_84_fu_1229_p3;
wire   [54:0] select_ln46_85_fu_1251_p3;
wire   [0:0] carry_674_fu_1245_p2;
wire   [55:0] tmp1_fu_1259_p3;
wire   [63:0] zext_ln46_92_fu_1267_p1;
wire   [63:0] sub_ln39_76_fu_1025_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_is_digit_lessthan_ct_fu_188(
    .ap_ready(tmp_is_digit_lessthan_ct_fu_188_ap_ready),
    .x(C24_0_q0),
    .y(64'd0),
    .ap_return(tmp_is_digit_lessthan_ct_fu_188_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_s_is_digit_lessthan_ct_fu_196(
    .ap_ready(tmp_s_is_digit_lessthan_ct_fu_196_ap_ready),
    .x(shl_ln33_fu_416_p2),
    .y(C24_0_q0),
    .ap_return(tmp_s_is_digit_lessthan_ct_fu_196_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct borrowReg_is_digit_lessthan_ct_fu_203(
    .ap_ready(borrowReg_is_digit_lessthan_ct_fu_203_ap_ready),
    .x(shl_ln33_fu_416_p2),
    .y(64'd18446744073709551614),
    .ap_return(borrowReg_is_digit_lessthan_ct_fu_203_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1276_is_digit_lessthan_ct_fu_210(
    .ap_ready(tmp_1276_is_digit_lessthan_ct_fu_210_ap_ready),
    .x(tempReg_1643_fu_435_p2),
    .y(64'd0),
    .ap_return(tmp_1276_is_digit_lessthan_ct_fu_210_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1277_is_digit_lessthan_ct_fu_217(
    .ap_ready(tmp_1277_is_digit_lessthan_ct_fu_217_ap_ready),
    .x(tempReg_1657_fu_447_p2),
    .y(zext_ln33_fu_430_p1),
    .ap_return(tmp_1277_is_digit_lessthan_ct_fu_217_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1278_is_digit_lessthan_ct_fu_223(
    .ap_ready(tmp_1278_is_digit_lessthan_ct_fu_223_ap_ready),
    .x(add_ln33_191_fu_455_p2),
    .y(tempReg_1657_fu_447_p2),
    .ap_return(tmp_1278_is_digit_lessthan_ct_fu_223_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1279_is_digit_lessthan_ct_fu_229(
    .ap_ready(tmp_1279_is_digit_lessthan_ct_fu_229_ap_ready),
    .x(add_ln33_191_fu_455_p2),
    .y(64'd18446744073709551615),
    .ap_return(tmp_1279_is_digit_lessthan_ct_fu_229_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1280_is_digit_lessthan_ct_fu_236(
    .ap_ready(tmp_1280_is_digit_lessthan_ct_fu_236_ap_ready),
    .x(tempReg_1658_fu_548_p2),
    .y(zext_ln33_85_fu_469_p1),
    .ap_return(tmp_1280_is_digit_lessthan_ct_fu_236_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1281_is_digit_lessthan_ct_fu_242(
    .ap_ready(tmp_1281_is_digit_lessthan_ct_fu_242_ap_ready),
    .x(add_ln33_193_fu_556_p2),
    .y(tempReg_1658_fu_548_p2),
    .ap_return(tmp_1281_is_digit_lessthan_ct_fu_242_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1282_is_digit_lessthan_ct_fu_248(
    .ap_ready(tmp_1282_is_digit_lessthan_ct_fu_248_ap_ready),
    .x(add_ln33_193_fu_556_p2),
    .y(64'd18446744073709551615),
    .ap_return(tmp_1282_is_digit_lessthan_ct_fu_248_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1283_is_digit_lessthan_ct_fu_255(
    .ap_ready(tmp_1283_is_digit_lessthan_ct_fu_255_ap_ready),
    .x(tempReg_1659_fu_649_p2),
    .y(zext_ln33_86_fu_570_p1),
    .ap_return(tmp_1283_is_digit_lessthan_ct_fu_255_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1284_is_digit_lessthan_ct_fu_261(
    .ap_ready(tmp_1284_is_digit_lessthan_ct_fu_261_ap_ready),
    .x(add_ln33_195_fu_657_p2),
    .y(tempReg_1659_fu_649_p2),
    .ap_return(tmp_1284_is_digit_lessthan_ct_fu_261_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1285_is_digit_lessthan_ct_fu_267(
    .ap_ready(tmp_1285_is_digit_lessthan_ct_fu_267_ap_ready),
    .x(add_ln33_195_fu_657_p2),
    .y(64'd6341068275337658367),
    .ap_return(tmp_1285_is_digit_lessthan_ct_fu_267_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1286_is_digit_lessthan_ct_fu_274(
    .ap_ready(tmp_1286_is_digit_lessthan_ct_fu_274_ap_ready),
    .x(tempReg_1660_fu_730_p2),
    .y(zext_ln33_87_fu_671_p1),
    .ap_return(tmp_1286_is_digit_lessthan_ct_fu_274_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1287_is_digit_lessthan_ct_fu_280(
    .ap_ready(tmp_1287_is_digit_lessthan_ct_fu_280_ap_ready),
    .x(add_ln33_197_fu_738_p2),
    .y(tempReg_1660_fu_730_p2),
    .ap_return(tmp_1287_is_digit_lessthan_ct_fu_280_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1288_is_digit_lessthan_ct_fu_286(
    .ap_ready(tmp_1288_is_digit_lessthan_ct_fu_286_ap_ready),
    .x(add_ln33_197_fu_738_p2),
    .y(64'd2742894157933825857),
    .ap_return(tmp_1288_is_digit_lessthan_ct_fu_286_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1289_is_digit_lessthan_ct_fu_293(
    .ap_ready(tmp_1289_is_digit_lessthan_ct_fu_293_ap_ready),
    .x(tempReg_1661_fu_811_p2),
    .y(zext_ln33_88_fu_752_p1),
    .ap_return(tmp_1289_is_digit_lessthan_ct_fu_293_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1290_is_digit_lessthan_ct_fu_299(
    .ap_ready(tmp_1290_is_digit_lessthan_ct_fu_299_ap_ready),
    .x(add_ln33_199_fu_819_p2),
    .y(tempReg_1661_fu_811_p2),
    .ap_return(tmp_1290_is_digit_lessthan_ct_fu_299_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1291_is_digit_lessthan_ct_fu_305(
    .ap_ready(tmp_1291_is_digit_lessthan_ct_fu_305_ap_ready),
    .x(add_ln33_199_fu_819_p2),
    .y(64'd3978910002679970654),
    .ap_return(tmp_1291_is_digit_lessthan_ct_fu_305_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1292_is_digit_lessthan_ct_fu_312(
    .ap_ready(tmp_1292_is_digit_lessthan_ct_fu_312_ap_ready),
    .x(tempReg_1662_fu_892_p2),
    .y(zext_ln33_89_fu_833_p1),
    .ap_return(tmp_1292_is_digit_lessthan_ct_fu_312_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1293_is_digit_lessthan_ct_fu_318(
    .ap_ready(tmp_1293_is_digit_lessthan_ct_fu_318_ap_ready),
    .x(add_ln33_201_fu_900_p2),
    .y(tempReg_1662_fu_892_p2),
    .ap_return(tmp_1293_is_digit_lessthan_ct_fu_318_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1294_is_digit_lessthan_ct_fu_324(
    .ap_ready(tmp_1294_is_digit_lessthan_ct_fu_324_ap_ready),
    .x(add_ln33_201_fu_900_p2),
    .y(64'd13874338639501019552),
    .ap_return(tmp_1294_is_digit_lessthan_ct_fu_324_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1295_is_digit_lessthan_ct_fu_331(
    .ap_ready(tmp_1295_is_digit_lessthan_ct_fu_331_ap_ready),
    .x(add_ln33_s_fu_972_p3),
    .y(64'd36255204122967100),
    .ap_return(tmp_1295_is_digit_lessthan_ct_fu_331_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1296_is_digit_lessthan_ct_fu_338(
    .ap_ready(tmp_1296_is_digit_lessthan_ct_fu_338_ap_ready),
    .x(add_ln46_fu_1043_p2),
    .y(tempReg_1643_fu_435_p2),
    .ap_return(tmp_1296_is_digit_lessthan_ct_fu_338_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1297_is_digit_lessthan_ct_fu_344(
    .ap_ready(tmp_1297_is_digit_lessthan_ct_fu_344_ap_ready),
    .x(tempReg_1670_fu_1062_p2),
    .y(zext_ln46_fu_1057_p1),
    .ap_return(tmp_1297_is_digit_lessthan_ct_fu_344_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1298_is_digit_lessthan_ct_fu_350(
    .ap_ready(tmp_1298_is_digit_lessthan_ct_fu_350_ap_ready),
    .x(sub_ln46_fu_1070_p2),
    .y(tempReg_1670_fu_1062_p2),
    .ap_return(tmp_1298_is_digit_lessthan_ct_fu_350_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1299_is_digit_lessthan_ct_fu_356(
    .ap_ready(tmp_1299_is_digit_lessthan_ct_fu_356_ap_ready),
    .x(tempReg_1671_fu_1089_p2),
    .y(zext_ln46_85_fu_1084_p1),
    .ap_return(tmp_1299_is_digit_lessthan_ct_fu_356_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1300_is_digit_lessthan_ct_fu_362(
    .ap_ready(tmp_1300_is_digit_lessthan_ct_fu_362_ap_ready),
    .x(sub_ln46_15_fu_1097_p2),
    .y(tempReg_1671_fu_1089_p2),
    .ap_return(tmp_1300_is_digit_lessthan_ct_fu_362_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1301_is_digit_lessthan_ct_fu_368(
    .ap_ready(tmp_1301_is_digit_lessthan_ct_fu_368_ap_ready),
    .x(tempReg_1672_fu_1116_p2),
    .y(zext_ln46_86_fu_1111_p1),
    .ap_return(tmp_1301_is_digit_lessthan_ct_fu_368_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1302_is_digit_lessthan_ct_fu_374(
    .ap_ready(tmp_1302_is_digit_lessthan_ct_fu_374_ap_ready),
    .x(add_ln46_172_fu_1132_p2),
    .y(tempReg_1672_fu_1116_p2),
    .ap_return(tmp_1302_is_digit_lessthan_ct_fu_374_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1303_is_digit_lessthan_ct_fu_380(
    .ap_ready(tmp_1303_is_digit_lessthan_ct_fu_380_ap_ready),
    .x(tempReg_1673_fu_1151_p2),
    .y(zext_ln46_87_fu_1146_p1),
    .ap_return(tmp_1303_is_digit_lessthan_ct_fu_380_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1304_is_digit_lessthan_ct_fu_386(
    .ap_ready(tmp_1304_is_digit_lessthan_ct_fu_386_ap_ready),
    .x(add_ln46_174_fu_1167_p2),
    .y(tempReg_1673_fu_1151_p2),
    .ap_return(tmp_1304_is_digit_lessthan_ct_fu_386_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1305_is_digit_lessthan_ct_fu_392(
    .ap_ready(tmp_1305_is_digit_lessthan_ct_fu_392_ap_ready),
    .x(tempReg_1674_fu_1186_p2),
    .y(zext_ln46_88_fu_1181_p1),
    .ap_return(tmp_1305_is_digit_lessthan_ct_fu_392_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1306_is_digit_lessthan_ct_fu_398(
    .ap_ready(tmp_1306_is_digit_lessthan_ct_fu_398_ap_ready),
    .x(add_ln46_176_fu_1202_p2),
    .y(tempReg_1674_fu_1186_p2),
    .ap_return(tmp_1306_is_digit_lessthan_ct_fu_398_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1307_is_digit_lessthan_ct_fu_404(
    .ap_ready(tmp_1307_is_digit_lessthan_ct_fu_404_ap_ready),
    .x(tempReg_1675_fu_1221_p2),
    .y(zext_ln46_89_fu_1216_p1),
    .ap_return(tmp_1307_is_digit_lessthan_ct_fu_404_ap_return),
    .ap_rst(ap_rst)
);

sikep503_kem_enc_hw_is_digit_lessthan_ct tmp_1308_is_digit_lessthan_ct_fu_410(
    .ap_ready(tmp_1308_is_digit_lessthan_ct_fu_410_ap_ready),
    .x(add_ln46_178_fu_1237_p2),
    .y(tempReg_1675_fu_1221_p2),
    .ap_return(tmp_1308_is_digit_lessthan_ct_fu_410_ap_return),
    .ap_rst(ap_rst)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C24_0_address0_local = C24_0_addr_reg_1278;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C24_0_address0_local = 64'd0;
    end else begin
        C24_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        C24_0_ce0_local = 1'b1;
    end else begin
        C24_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        C24_0_we0_local = 1'b1;
    end else begin
        C24_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C24_1_address0_local = C24_1_addr_reg_1283;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C24_1_address0_local = 64'd0;
    end else begin
        C24_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        C24_1_ce0_local = 1'b1;
    end else begin
        C24_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        C24_1_we0_local = 1'b1;
    end else begin
        C24_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C24_2_address0_local = C24_2_addr_reg_1288;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C24_2_address0_local = 64'd0;
    end else begin
        C24_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        C24_2_ce0_local = 1'b1;
    end else begin
        C24_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        C24_2_we0_local = 1'b1;
    end else begin
        C24_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C24_3_address0_local = C24_3_addr_reg_1293;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C24_3_address0_local = 64'd0;
    end else begin
        C24_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        C24_3_ce0_local = 1'b1;
    end else begin
        C24_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        C24_3_we0_local = 1'b1;
    end else begin
        C24_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C24_4_address0_local = C24_4_addr_reg_1298;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C24_4_address0_local = 64'd0;
    end else begin
        C24_4_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        C24_4_ce0_local = 1'b1;
    end else begin
        C24_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        C24_4_we0_local = 1'b1;
    end else begin
        C24_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C24_5_address0_local = C24_5_addr_reg_1303;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C24_5_address0_local = 64'd0;
    end else begin
        C24_5_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        C24_5_ce0_local = 1'b1;
    end else begin
        C24_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        C24_5_we0_local = 1'b1;
    end else begin
        C24_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C24_6_address0_local = C24_6_addr_reg_1308;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C24_6_address0_local = 64'd0;
    end else begin
        C24_6_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        C24_6_ce0_local = 1'b1;
    end else begin
        C24_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        C24_6_we0_local = 1'b1;
    end else begin
        C24_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C24_7_address0_local = C24_7_addr_reg_1313;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        C24_7_address0_local = 64'd0;
    end else begin
        C24_7_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1)))) begin
        C24_7_ce0_local = 1'b1;
    end else begin
        C24_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        C24_7_we0_local = 1'b1;
    end else begin
        C24_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (1'b0 == ap_ce))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C24_0_addr_reg_1278 = 64'd0;

assign C24_0_address0 = C24_0_address0_local;

assign C24_0_ce0 = C24_0_ce0_local;

assign C24_0_d0 = add_ln46_fu_1043_p2;

assign C24_0_we0 = C24_0_we0_local;

assign C24_1_addr_reg_1283 = 64'd0;

assign C24_1_address0 = C24_1_address0_local;

assign C24_1_ce0 = C24_1_ce0_local;

assign C24_1_d0 = sub_ln46_fu_1070_p2;

assign C24_1_we0 = C24_1_we0_local;

assign C24_2_addr_reg_1288 = 64'd0;

assign C24_2_address0 = C24_2_address0_local;

assign C24_2_ce0 = C24_2_ce0_local;

assign C24_2_d0 = sub_ln46_15_fu_1097_p2;

assign C24_2_we0 = C24_2_we0_local;

assign C24_3_addr_reg_1293 = 64'd0;

assign C24_3_address0 = C24_3_address0_local;

assign C24_3_ce0 = C24_3_ce0_local;

assign C24_3_d0 = add_ln46_172_fu_1132_p2;

assign C24_3_we0 = C24_3_we0_local;

assign C24_4_addr_reg_1298 = 64'd0;

assign C24_4_address0 = C24_4_address0_local;

assign C24_4_ce0 = C24_4_ce0_local;

assign C24_4_d0 = add_ln46_174_fu_1167_p2;

assign C24_4_we0 = C24_4_we0_local;

assign C24_5_addr_reg_1303 = 64'd0;

assign C24_5_address0 = C24_5_address0_local;

assign C24_5_ce0 = C24_5_ce0_local;

assign C24_5_d0 = add_ln46_176_fu_1202_p2;

assign C24_5_we0 = C24_5_we0_local;

assign C24_6_addr_reg_1308 = 64'd0;

assign C24_6_address0 = C24_6_address0_local;

assign C24_6_ce0 = C24_6_ce0_local;

assign C24_6_d0 = add_ln46_178_fu_1237_p2;

assign C24_6_we0 = C24_6_we0_local;

assign C24_7_addr_reg_1313 = 64'd0;

assign C24_7_address0 = C24_7_address0_local;

assign C24_7_ce0 = C24_7_ce0_local;

assign C24_7_d0 = add_ln46_180_fu_1271_p2;

assign C24_7_we0 = C24_7_we0_local;

assign add_ln33_191_fu_455_p2 = (C24_1_q0 + tempReg_1657_fu_447_p2);

assign add_ln33_193_fu_556_p2 = (C24_2_q0 + tempReg_1658_fu_548_p2);

assign add_ln33_195_fu_657_p2 = (C24_3_q0 + tempReg_1659_fu_649_p2);

assign add_ln33_197_fu_738_p2 = (C24_4_q0 + tempReg_1660_fu_730_p2);

assign add_ln33_199_fu_819_p2 = (C24_5_q0 + tempReg_1661_fu_811_p2);

assign add_ln33_201_fu_900_p2 = (C24_6_q0 + tempReg_1662_fu_892_p2);

assign add_ln33_s_fu_972_p3 = {{trunc_ln33_fu_968_p1}, {or_ln33_83_fu_962_p2}};

assign add_ln46_172_fu_1132_p2 = (select_ln46_81_fu_1124_p3 + tempReg_1672_fu_1116_p2);

assign add_ln46_174_fu_1167_p2 = (tempReg_1673_fu_1151_p2 + select_ln46_82_fu_1159_p3);

assign add_ln46_176_fu_1202_p2 = (tempReg_1674_fu_1186_p2 + select_ln46_83_fu_1194_p3);

assign add_ln46_178_fu_1237_p2 = (tempReg_1675_fu_1221_p2 + select_ln46_84_fu_1229_p3);

assign add_ln46_180_fu_1271_p2 = (zext_ln46_92_fu_1267_p1 + sub_ln39_76_fu_1025_p2);

assign add_ln46_fu_1043_p2 = (select_ln46_fu_1035_p3 + tempReg_1643_fu_435_p2);

assign and_ln39_85_fu_627_p2 = (xor_ln100_288_fu_621_p2 & borrowReg_383_fu_532_p2);

assign and_ln39_86_fu_708_p2 = (xor_ln100_289_fu_702_p2 & borrowReg_384_fu_633_p2);

assign and_ln39_87_fu_789_p2 = (xor_ln100_290_fu_783_p2 & borrowReg_385_fu_714_p2);

assign and_ln39_88_fu_870_p2 = (xor_ln100_291_fu_864_p2 & borrowReg_386_fu_795_p2);

assign and_ln39_89_fu_940_p2 = (xor_ln100_292_fu_934_p2 & borrowReg_387_fu_876_p2);

assign and_ln39_90_fu_1013_p2 = (xor_ln100_293_fu_1007_p2 & borrowReg_388_fu_946_p2);

assign and_ln39_fu_526_p2 = (xor_ln100_fu_520_p2 & borrowReg_is_digit_lessthan_ct_fu_203_ap_return);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign bit_sel1_fu_480_p3 = add_ln33_191_fu_455_p2[64'd63];

assign bit_sel_fu_581_p3 = add_ln33_193_fu_556_p2[64'd63];

assign borrowReg_383_fu_532_p2 = (tmp_1279_is_digit_lessthan_ct_fu_229_ap_return | and_ln39_fu_526_p2);

assign borrowReg_384_fu_633_p2 = (tmp_1282_is_digit_lessthan_ct_fu_248_ap_return | and_ln39_85_fu_627_p2);

assign borrowReg_385_fu_714_p2 = (tmp_1285_is_digit_lessthan_ct_fu_267_ap_return | and_ln39_86_fu_708_p2);

assign borrowReg_386_fu_795_p2 = (tmp_1288_is_digit_lessthan_ct_fu_286_ap_return | and_ln39_87_fu_789_p2);

assign borrowReg_387_fu_876_p2 = (tmp_1291_is_digit_lessthan_ct_fu_305_ap_return | and_ln39_88_fu_870_p2);

assign borrowReg_388_fu_946_p2 = (tmp_1294_is_digit_lessthan_ct_fu_324_ap_return | and_ln39_89_fu_940_p2);

assign borrowReg_389_fu_1019_p2 = (tmp_1295_is_digit_lessthan_ct_fu_331_ap_return | and_ln39_90_fu_1013_p2);

assign carry_663_fu_463_p2 = (tmp_1278_is_digit_lessthan_ct_fu_223_ap_return | tmp_1277_is_digit_lessthan_ct_fu_217_ap_return);

assign carry_664_fu_564_p2 = (tmp_1281_is_digit_lessthan_ct_fu_242_ap_return | tmp_1280_is_digit_lessthan_ct_fu_236_ap_return);

assign carry_665_fu_665_p2 = (tmp_1284_is_digit_lessthan_ct_fu_261_ap_return | tmp_1283_is_digit_lessthan_ct_fu_255_ap_return);

assign carry_666_fu_746_p2 = (tmp_1287_is_digit_lessthan_ct_fu_280_ap_return | tmp_1286_is_digit_lessthan_ct_fu_274_ap_return);

assign carry_667_fu_827_p2 = (tmp_1290_is_digit_lessthan_ct_fu_299_ap_return | tmp_1289_is_digit_lessthan_ct_fu_293_ap_return);

assign carry_668_fu_1051_p2 = (tmp_1296_is_digit_lessthan_ct_fu_338_ap_return | tmp_1276_is_digit_lessthan_ct_fu_210_ap_return);

assign carry_669_fu_1078_p2 = (tmp_1298_is_digit_lessthan_ct_fu_350_ap_return | tmp_1297_is_digit_lessthan_ct_fu_344_ap_return);

assign carry_670_fu_1105_p2 = (tmp_1300_is_digit_lessthan_ct_fu_362_ap_return | tmp_1299_is_digit_lessthan_ct_fu_356_ap_return);

assign carry_671_fu_1140_p2 = (tmp_1302_is_digit_lessthan_ct_fu_374_ap_return | tmp_1301_is_digit_lessthan_ct_fu_368_ap_return);

assign carry_672_fu_1175_p2 = (tmp_1304_is_digit_lessthan_ct_fu_386_ap_return | tmp_1303_is_digit_lessthan_ct_fu_380_ap_return);

assign carry_673_fu_1210_p2 = (tmp_1306_is_digit_lessthan_ct_fu_398_ap_return | tmp_1305_is_digit_lessthan_ct_fu_392_ap_return);

assign carry_674_fu_1245_p2 = (tmp_1308_is_digit_lessthan_ct_fu_410_ap_return | tmp_1307_is_digit_lessthan_ct_fu_404_ap_return);

assign carry_fu_424_p2 = (tmp_s_is_digit_lessthan_ct_fu_196_ap_return | tmp_is_digit_lessthan_ct_fu_188_ap_return);

assign or_ln33_83_fu_962_p2 = (tmp_1293_is_digit_lessthan_ct_fu_318_ap_return | tmp_1292_is_digit_lessthan_ct_fu_312_ap_return);

assign or_ln95_288_fu_607_p2 = (xor_ln95_s_fu_599_p3 | tempReg_1664_fu_575_p2);

assign or_ln95_289_fu_688_p2 = (tempReg_1665_fu_676_p2 | sub_ln95_fu_682_p2);

assign or_ln95_290_fu_769_p2 = (tempReg_1666_fu_757_p2 | sub_ln95_252_fu_763_p2);

assign or_ln95_291_fu_850_p2 = (tempReg_1667_fu_838_p2 | sub_ln95_253_fu_844_p2);

assign or_ln95_292_fu_920_p2 = (tempReg_1668_fu_908_p2 | sub_ln95_254_fu_914_p2);

assign or_ln95_293_fu_993_p2 = (tempReg_1669_fu_981_p2 | sub_ln95_255_fu_987_p2);

assign or_ln95_fu_506_p2 = (xor_ln_fu_498_p3 | tempReg_1663_fu_474_p2);

assign select_ln46_81_fu_1124_p3 = ((borrowReg_389_fu_1019_p2[0:0] == 1'b1) ? 64'd6341068275337658367 : 64'd0);

assign select_ln46_82_fu_1159_p3 = ((borrowReg_389_fu_1019_p2[0:0] == 1'b1) ? 64'd2742894157933825857 : 64'd0);

assign select_ln46_83_fu_1194_p3 = ((borrowReg_389_fu_1019_p2[0:0] == 1'b1) ? 64'd3978910002679970654 : 64'd0);

assign select_ln46_84_fu_1229_p3 = ((borrowReg_389_fu_1019_p2[0:0] == 1'b1) ? 64'd13874338639501019552 : 64'd0);

assign select_ln46_85_fu_1251_p3 = ((borrowReg_389_fu_1019_p2[0:0] == 1'b1) ? 55'd18127602061483550 : 55'd0);

assign select_ln46_fu_1035_p3 = ((borrowReg_389_fu_1019_p2[0:0] == 1'b1) ? 64'd18446744073709551614 : 64'd0);

assign shl_ln33_fu_416_p2 = C24_0_q0 << 64'd1;

assign sub_ln39_71_fu_639_p2 = (tempReg_1664_fu_575_p2 - zext_ln39_85_fu_544_p1);

assign sub_ln39_72_fu_720_p2 = (tempReg_1665_fu_676_p2 - zext_ln39_86_fu_645_p1);

assign sub_ln39_73_fu_801_p2 = (tempReg_1666_fu_757_p2 - zext_ln39_87_fu_726_p1);

assign sub_ln39_74_fu_882_p2 = (tempReg_1667_fu_838_p2 - zext_ln39_88_fu_807_p1);

assign sub_ln39_75_fu_952_p2 = (tempReg_1668_fu_908_p2 - zext_ln39_89_fu_888_p1);

assign sub_ln39_76_fu_1025_p2 = (tempReg_1669_fu_981_p2 - zext_ln39_90_fu_958_p1);

assign sub_ln39_fu_538_p2 = (tempReg_1663_fu_474_p2 - zext_ln39_fu_443_p1);

assign sub_ln46_15_fu_1097_p2 = (tempReg_1671_fu_1089_p2 - zext_ln41_fu_1031_p1);

assign sub_ln46_fu_1070_p2 = (tempReg_1670_fu_1062_p2 - zext_ln41_fu_1031_p1);

assign sub_ln95_252_fu_763_p2 = (64'd2742894157933825857 - add_ln33_197_fu_738_p2);

assign sub_ln95_253_fu_844_p2 = (64'd3978910002679970654 - add_ln33_199_fu_819_p2);

assign sub_ln95_254_fu_914_p2 = ($signed(64'd13874338639501019552) - $signed(add_ln33_201_fu_900_p2));

assign sub_ln95_255_fu_987_p2 = (64'd36255204122967100 - add_ln33_s_fu_972_p3);

assign sub_ln95_fu_682_p2 = (64'd6341068275337658367 - add_ln33_195_fu_657_p2);

assign tempReg_1643_fu_435_p2 = (shl_ln33_fu_416_p2 + 64'd2);

assign tempReg_1657_fu_447_p2 = (C24_1_q0 + zext_ln33_fu_430_p1);

assign tempReg_1658_fu_548_p2 = (C24_2_q0 + zext_ln33_85_fu_469_p1);

assign tempReg_1659_fu_649_p2 = (C24_3_q0 + zext_ln33_86_fu_570_p1);

assign tempReg_1660_fu_730_p2 = (C24_4_q0 + zext_ln33_87_fu_671_p1);

assign tempReg_1661_fu_811_p2 = (C24_5_q0 + zext_ln33_88_fu_752_p1);

assign tempReg_1662_fu_892_p2 = (C24_6_q0 + zext_ln33_89_fu_833_p1);

assign tempReg_1663_fu_474_p2 = (add_ln33_191_fu_455_p2 + 64'd1);

assign tempReg_1664_fu_575_p2 = (add_ln33_193_fu_556_p2 + 64'd1);

assign tempReg_1665_fu_676_p2 = ($signed(add_ln33_195_fu_657_p2) + $signed(64'd12105675798371893249));

assign tempReg_1666_fu_757_p2 = ($signed(add_ln33_197_fu_738_p2) + $signed(64'd15703849915775725759));

assign tempReg_1667_fu_838_p2 = ($signed(add_ln33_199_fu_819_p2) + $signed(64'd14467834071029580962));

assign tempReg_1668_fu_908_p2 = (add_ln33_201_fu_900_p2 + 64'd4572405434208532064);

assign tempReg_1669_fu_981_p2 = ($signed(add_ln33_s_fu_972_p3) + $signed(64'd18410488869586584516));

assign tempReg_1670_fu_1062_p2 = (sub_ln39_fu_538_p2 + zext_ln46_fu_1057_p1);

assign tempReg_1671_fu_1089_p2 = (sub_ln39_71_fu_639_p2 + zext_ln46_85_fu_1084_p1);

assign tempReg_1672_fu_1116_p2 = (sub_ln39_72_fu_720_p2 + zext_ln46_86_fu_1111_p1);

assign tempReg_1673_fu_1151_p2 = (sub_ln39_73_fu_801_p2 + zext_ln46_87_fu_1146_p1);

assign tempReg_1674_fu_1186_p2 = (sub_ln39_74_fu_882_p2 + zext_ln46_88_fu_1181_p1);

assign tempReg_1675_fu_1221_p2 = (sub_ln39_75_fu_952_p2 + zext_ln46_89_fu_1216_p1);

assign tmp1_fu_1259_p3 = {{select_ln46_85_fu_1251_p3}, {carry_674_fu_1245_p2}};

assign tmp_1309_fu_512_p3 = or_ln95_fu_506_p2[32'd63];

assign tmp_1310_fu_613_p3 = or_ln95_288_fu_607_p2[32'd63];

assign tmp_1311_fu_694_p3 = or_ln95_289_fu_688_p2[32'd63];

assign tmp_1312_fu_775_p3 = or_ln95_290_fu_769_p2[32'd63];

assign tmp_1313_fu_856_p3 = or_ln95_291_fu_850_p2[32'd63];

assign tmp_1314_fu_926_p3 = or_ln95_292_fu_920_p2[32'd63];

assign tmp_1315_fu_999_p3 = or_ln95_293_fu_993_p2[32'd63];

assign trunc_ln33_fu_968_p1 = C24_7_q0[62:0];

assign trunc_ln95_19_fu_595_p1 = add_ln33_193_fu_556_p2[62:0];

assign trunc_ln95_fu_494_p1 = add_ln33_191_fu_455_p2[62:0];

assign xor_ln100_288_fu_621_p2 = (tmp_1310_fu_613_p3 ^ 1'd1);

assign xor_ln100_289_fu_702_p2 = (tmp_1311_fu_694_p3 ^ 1'd1);

assign xor_ln100_290_fu_783_p2 = (tmp_1312_fu_775_p3 ^ 1'd1);

assign xor_ln100_291_fu_864_p2 = (tmp_1313_fu_856_p3 ^ 1'd1);

assign xor_ln100_292_fu_934_p2 = (tmp_1314_fu_926_p3 ^ 1'd1);

assign xor_ln100_293_fu_1007_p2 = (tmp_1315_fu_999_p3 ^ 1'd1);

assign xor_ln100_fu_520_p2 = (tmp_1309_fu_512_p3 ^ 1'd1);

assign xor_ln95_20_fu_488_p2 = (bit_sel1_fu_480_p3 ^ 1'd1);

assign xor_ln95_fu_589_p2 = (bit_sel_fu_581_p3 ^ 1'd1);

assign xor_ln95_s_fu_599_p3 = {{xor_ln95_fu_589_p2}, {trunc_ln95_19_fu_595_p1}};

assign xor_ln_fu_498_p3 = {{xor_ln95_20_fu_488_p2}, {trunc_ln95_fu_494_p1}};

assign zext_ln33_85_fu_469_p1 = carry_663_fu_463_p2;

assign zext_ln33_86_fu_570_p1 = carry_664_fu_564_p2;

assign zext_ln33_87_fu_671_p1 = carry_665_fu_665_p2;

assign zext_ln33_88_fu_752_p1 = carry_666_fu_746_p2;

assign zext_ln33_89_fu_833_p1 = carry_667_fu_827_p2;

assign zext_ln33_fu_430_p1 = carry_fu_424_p2;

assign zext_ln39_85_fu_544_p1 = borrowReg_383_fu_532_p2;

assign zext_ln39_86_fu_645_p1 = borrowReg_384_fu_633_p2;

assign zext_ln39_87_fu_726_p1 = borrowReg_385_fu_714_p2;

assign zext_ln39_88_fu_807_p1 = borrowReg_386_fu_795_p2;

assign zext_ln39_89_fu_888_p1 = borrowReg_387_fu_876_p2;

assign zext_ln39_90_fu_958_p1 = borrowReg_388_fu_946_p2;

assign zext_ln39_fu_443_p1 = borrowReg_is_digit_lessthan_ct_fu_203_ap_return;

assign zext_ln41_fu_1031_p1 = borrowReg_389_fu_1019_p2;

assign zext_ln46_85_fu_1084_p1 = carry_669_fu_1078_p2;

assign zext_ln46_86_fu_1111_p1 = carry_670_fu_1105_p2;

assign zext_ln46_87_fu_1146_p1 = carry_671_fu_1140_p2;

assign zext_ln46_88_fu_1181_p1 = carry_672_fu_1175_p2;

assign zext_ln46_89_fu_1216_p1 = carry_673_fu_1210_p2;

assign zext_ln46_92_fu_1267_p1 = tmp1_fu_1259_p3;

assign zext_ln46_fu_1057_p1 = carry_668_fu_1051_p2;

endmodule //sikep503_kem_enc_hw_fpadd503_41
