// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sikep503_kem_enc_hw_mul_148 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_0_address0,
        A_0_ce0,
        A_0_q0,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        A_2_address0,
        A_2_ce0,
        A_2_q0,
        A_3_address0,
        A_3_ce0,
        A_3_q0,
        A_4_address0,
        A_4_ce0,
        A_4_q0,
        A_5_address0,
        A_5_ce0,
        A_5_q0,
        A_6_address0,
        A_6_ce0,
        A_6_q0,
        A_7_address0,
        A_7_ce0,
        A_7_q0,
        b_0_address0,
        b_0_ce0,
        b_0_q0,
        b_1_address0,
        b_1_ce0,
        b_1_q0,
        b_2_address0,
        b_2_ce0,
        b_2_q0,
        b_3_address0,
        b_3_ce0,
        b_3_q0,
        b_4_address0,
        b_4_ce0,
        b_4_q0,
        b_5_address0,
        b_5_ce0,
        b_5_q0,
        b_6_address0,
        b_6_ce0,
        b_6_q0,
        b_7_address0,
        b_7_ce0,
        b_7_q0,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] A_0_address0;
output   A_0_ce0;
input  [63:0] A_0_q0;
output  [0:0] A_1_address0;
output   A_1_ce0;
input  [63:0] A_1_q0;
output  [0:0] A_2_address0;
output   A_2_ce0;
input  [63:0] A_2_q0;
output  [0:0] A_3_address0;
output   A_3_ce0;
input  [63:0] A_3_q0;
output  [0:0] A_4_address0;
output   A_4_ce0;
input  [63:0] A_4_q0;
output  [0:0] A_5_address0;
output   A_5_ce0;
input  [63:0] A_5_q0;
output  [0:0] A_6_address0;
output   A_6_ce0;
input  [63:0] A_6_q0;
output  [0:0] A_7_address0;
output   A_7_ce0;
input  [63:0] A_7_q0;
output  [0:0] b_0_address0;
output   b_0_ce0;
input  [63:0] b_0_q0;
output  [0:0] b_1_address0;
output   b_1_ce0;
input  [63:0] b_1_q0;
output  [0:0] b_2_address0;
output   b_2_ce0;
input  [63:0] b_2_q0;
output  [0:0] b_3_address0;
output   b_3_ce0;
input  [63:0] b_3_q0;
output  [0:0] b_4_address0;
output   b_4_ce0;
input  [63:0] b_4_q0;
output  [0:0] b_5_address0;
output   b_5_ce0;
input  [63:0] b_5_q0;
output  [0:0] b_6_address0;
output   b_6_ce0;
input  [63:0] b_6_q0;
output  [0:0] b_7_address0;
output   b_7_ce0;
input  [63:0] b_7_q0;
output  [63:0] ap_return_0;
output  [63:0] ap_return_1;
output  [63:0] ap_return_2;
output  [63:0] ap_return_3;
output  [63:0] ap_return_4;
output  [63:0] ap_return_5;
output  [63:0] ap_return_6;
output  [63:0] ap_return_7;
output  [63:0] ap_return_8;
output  [63:0] ap_return_9;
output  [63:0] ap_return_10;
output  [63:0] ap_return_11;
output  [63:0] ap_return_12;
output  [63:0] ap_return_13;
output  [63:0] ap_return_14;
output  [63:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_11001;
wire   [255:0] grp_fu_424_p2;
reg   [255:0] z0_reg_2079;
wire    ap_block_pp0_stage1_11001;
wire   [255:0] grp_fu_428_p2;
reg   [255:0] z2_256_reg_2085;
wire   [127:0] grp_fu_384_p2;
reg   [127:0] z0_161_reg_2091;
wire   [129:0] grp_fu_400_p2;
reg   [129:0] z2_248_reg_2097;
wire   [65:0] sa_fu_668_p2;
reg   [65:0] sa_reg_2103;
wire   [65:0] sb_fu_682_p2;
reg   [65:0] sb_reg_2108;
wire   [63:0] w_472_fu_688_p1;
reg   [63:0] w_472_reg_2113;
reg   [63:0] w_472_reg_2113_pp0_iter1_reg;
wire   [255:0] z0_168_fu_432_p2;
reg   [255:0] z0_168_reg_2118;
reg   [255:0] z0_168_reg_2118_pp0_iter1_reg;
wire   [255:0] z2_257_fu_436_p2;
reg   [255:0] z2_257_reg_2125;
reg   [255:0] z2_257_reg_2125_pp0_iter1_reg;
wire   [127:0] z0_162_fu_388_p2;
reg   [127:0] z0_162_reg_2132;
wire   [129:0] z2_250_fu_404_p2;
reg   [129:0] z2_250_reg_2138;
wire   [65:0] sa_211_fu_832_p2;
reg   [65:0] sa_211_reg_2144;
wire   [65:0] sb_211_fu_846_p2;
reg   [65:0] sb_211_reg_2149;
wire   [127:0] a0_133_fu_892_p1;
reg   [127:0] a0_133_reg_2154;
wire   [127:0] b0_133_fu_896_p1;
reg   [127:0] b0_133_reg_2159;
wire   [127:0] z0_163_fu_392_p2;
reg   [127:0] z0_163_reg_2164;
wire   [129:0] z2_fu_408_p2;
reg   [129:0] z2_reg_2170;
wire   [65:0] sa_213_fu_976_p2;
reg   [65:0] sa_213_reg_2176;
wire   [65:0] sb_213_fu_990_p2;
reg   [65:0] sb_213_reg_2181;
wire   [127:0] a0_135_fu_1036_p1;
reg   [127:0] a0_135_reg_2186;
wire   [127:0] b0_135_fu_1040_p1;
reg   [127:0] b0_135_reg_2191;
wire   [1:0] tmp_479_fu_1044_p4;
reg   [1:0] tmp_479_reg_2196;
wire   [1:0] tmp_480_fu_1054_p4;
reg   [1:0] tmp_480_reg_2201;
wire   [63:0] a0_136_fu_1092_p1;
reg   [63:0] a0_136_reg_2206;
wire   [63:0] b0_136_fu_1096_p1;
reg   [63:0] b0_136_reg_2212;
reg   [64:0] a1_67_reg_2218;
reg   [64:0] b1_67_reg_2224;
wire   [131:0] mul_ln174_fu_412_p2;
reg   [131:0] mul_ln174_reg_2230;
wire   [130:0] add_ln174_fu_1134_p2;
reg   [130:0] add_ln174_reg_2235;
wire   [256:0] add_ln169_fu_1146_p2;
reg   [256:0] add_ln169_reg_2240;
wire   [131:0] mul_ln174_49_fu_416_p2;
reg   [131:0] mul_ln174_49_reg_2245;
wire   [130:0] add_ln174_98_fu_1166_p2;
reg   [130:0] add_ln174_98_reg_2250;
wire   [256:0] add_ln169_65_fu_1178_p2;
reg   [256:0] add_ln169_65_reg_2255;
reg   [255:0] z0_169_reg_2260;
wire   [257:0] or_ln175_132_fu_1244_p2;
reg   [257:0] or_ln175_132_reg_2266;
reg   [0:0] tmp_476_reg_2272;
reg   [255:0] z0_170_reg_2278;
wire   [3:0] z2_260_fu_1272_p2;
reg   [3:0] z2_260_reg_2284;
reg   [127:0] z0_165_reg_2290;
wire   [128:0] z2_255_fu_396_p2;
reg   [128:0] z2_255_reg_2295;
reg   [129:0] mul_ln174_51_reg_2300;
wire   [128:0] add_ln174_100_fu_1324_p2;
reg   [128:0] add_ln174_100_reg_2305;
wire   [511:0] z0_167_fu_1413_p2;
reg   [511:0] z0_167_reg_2310;
wire   [259:0] z1e_65_fu_1478_p2;
reg   [259:0] z1e_65_reg_2315;
wire   [511:0] z1e_67_fu_1655_p2;
reg   [511:0] z1e_67_reg_2320;
wire   [512:0] add_ln169_68_fu_1669_p2;
reg   [512:0] add_ln169_68_reg_2325;
reg   [63:0] w_486_reg_2330;
reg   [63:0] w_487_reg_2335;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
reg    A_0_ce0_local;
reg    A_1_ce0_local;
reg    A_2_ce0_local;
reg    A_3_ce0_local;
reg    A_4_ce0_local;
reg    A_5_ce0_local;
reg    A_6_ce0_local;
reg    A_7_ce0_local;
reg    b_0_ce0_local;
reg    b_1_ce0_local;
reg    b_2_ce0_local;
reg    b_3_ce0_local;
reg    b_4_ce0_local;
reg    b_5_ce0_local;
reg    b_6_ce0_local;
reg    b_7_ce0_local;
reg   [63:0] grp_fu_384_p0;
wire   [127:0] zext_ln121_296_fu_645_p1;
wire   [127:0] zext_ln121_314_fu_1290_p1;
reg   [63:0] grp_fu_384_p1;
wire   [127:0] zext_ln121_295_fu_640_p1;
wire   [127:0] zext_ln121_313_fu_1286_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] z0_162_fu_388_p0;
wire   [63:0] z0_162_fu_388_p1;
wire   [63:0] z0_163_fu_392_p0;
wire   [63:0] z0_163_fu_392_p1;
wire   [64:0] z2_255_fu_396_p0;
wire   [64:0] z2_255_fu_396_p1;
reg   [64:0] grp_fu_400_p0;
wire   [129:0] zext_ln121_298_fu_655_p1;
wire   [129:0] zext_ln174_464_fu_1315_p1;
reg   [64:0] grp_fu_400_p1;
wire   [129:0] zext_ln121_297_fu_650_p1;
wire   [129:0] zext_ln174_463_fu_1310_p1;
wire   [64:0] z2_250_fu_404_p0;
wire   [64:0] z2_250_fu_404_p1;
wire   [64:0] z2_fu_408_p0;
wire   [64:0] z2_fu_408_p1;
wire   [65:0] mul_ln174_fu_412_p0;
wire   [65:0] mul_ln174_fu_412_p1;
wire   [65:0] mul_ln174_49_fu_416_p0;
wire   [65:0] mul_ln174_49_fu_416_p1;
wire   [65:0] mul_ln174_50_fu_420_p0;
wire   [65:0] mul_ln174_50_fu_420_p1;
reg   [127:0] grp_fu_424_p0;
wire   [255:0] zext_ln121_294_fu_575_p1;
wire   [255:0] zext_ln121_307_fu_1188_p1;
reg   [127:0] grp_fu_424_p1;
wire   [255:0] zext_ln121_fu_570_p1;
wire   [255:0] zext_ln121_305_fu_1184_p1;
reg   [127:0] grp_fu_428_p0;
wire   [255:0] zext_ln136_fu_565_p1;
wire   [255:0] zext_ln121_312_fu_1262_p1;
reg   [127:0] grp_fu_428_p1;
wire   [255:0] zext_ln135_fu_552_p1;
wire   [255:0] zext_ln121_311_fu_1258_p1;
wire   [127:0] z0_168_fu_432_p0;
wire   [127:0] z0_168_fu_432_p1;
wire   [127:0] z2_257_fu_436_p0;
wire   [127:0] z2_257_fu_436_p1;
wire   [127:0] a1_66_fu_544_p3;
wire   [127:0] b1_66_fu_557_p3;
wire   [127:0] a0_129_fu_440_p3;
wire   [127:0] b0_129_fu_448_p3;
wire   [128:0] zext_ln147_136_fu_584_p1;
wire   [128:0] zext_ln147_fu_580_p1;
wire   [128:0] zext_ln148_136_fu_604_p1;
wire   [128:0] zext_ln148_fu_600_p1;
wire   [128:0] sa_217_fu_594_p2;
wire   [128:0] sb_217_fu_614_p2;
wire   [63:0] a0_130_fu_588_p2;
wire   [63:0] b0_130_fu_608_p2;
wire   [64:0] a1_s_fu_620_p4;
wire   [64:0] b1_s_fu_630_p4;
wire   [65:0] zext_ln147_137_fu_664_p1;
wire   [65:0] zext_ln147_113_fu_660_p1;
wire   [65:0] zext_ln148_137_fu_678_p1;
wire   [65:0] zext_ln148_113_fu_674_p1;
wire   [127:0] a0_131_fu_692_p3;
wire   [127:0] b0_131_fu_700_p3;
wire   [127:0] a1_39_fu_708_p3;
wire   [127:0] b1_39_fu_716_p3;
wire   [128:0] zext_ln147_114_fu_744_p1;
wire   [128:0] zext_ln147_138_fu_748_p1;
wire   [128:0] zext_ln148_114_fu_764_p1;
wire   [128:0] zext_ln148_138_fu_768_p1;
wire   [128:0] sa_218_fu_758_p2;
wire   [128:0] sb_218_fu_778_p2;
wire   [63:0] a0_132_fu_752_p2;
wire   [63:0] b0_132_fu_772_p2;
wire   [64:0] a1_40_fu_784_p4;
wire   [64:0] b1_40_fu_794_p4;
wire   [65:0] zext_ln147_139_fu_828_p1;
wire   [65:0] zext_ln147_115_fu_824_p1;
wire   [65:0] zext_ln148_139_fu_842_p1;
wire   [65:0] zext_ln148_115_fu_838_p1;
wire   [255:0] a0_fu_456_p5;
wire   [255:0] a1_fu_500_p5;
wire   [191:0] a1_cast_fu_512_p4;
wire   [191:0] a0_cast_fu_468_p4;
wire   [256:0] zext_ln147_140_fu_856_p1;
wire   [256:0] zext_ln147_116_fu_852_p1;
wire   [255:0] b0_fu_478_p5;
wire   [255:0] b1_fu_522_p5;
wire   [191:0] b1_cast_fu_534_p4;
wire   [191:0] b0_cast_fu_490_p4;
wire   [256:0] zext_ln148_140_fu_876_p1;
wire   [256:0] zext_ln148_116_fu_872_p1;
wire   [191:0] add_ln147_fu_860_p2;
wire   [191:0] add_ln148_fu_880_p2;
wire   [63:0] a0_134_fu_908_p4;
wire   [63:0] b0_134_fu_918_p4;
wire   [256:0] sa_219_fu_866_p2;
wire   [64:0] tmp_471_fu_938_p4;
wire   [256:0] sb_219_fu_886_p2;
wire   [64:0] tmp_472_fu_953_p4;
wire   [65:0] zext_ln147_141_fu_972_p1;
wire   [65:0] zext_ln147_117_fu_968_p1;
wire   [65:0] zext_ln148_141_fu_986_p1;
wire   [65:0] zext_ln148_117_fu_982_p1;
wire   [128:0] tmp_477_fu_996_p4;
wire   [129:0] zext_ln147_142_fu_1006_p1;
wire   [129:0] zext_ln121_306_fu_900_p1;
wire   [128:0] tmp_478_fu_1016_p4;
wire   [129:0] zext_ln148_142_fu_1026_p1;
wire   [129:0] zext_ln121_308_fu_904_p1;
wire   [129:0] sa_220_fu_1010_p2;
wire   [129:0] sb_220_fu_1030_p2;
wire   [128:0] zext_ln147_143_fu_1068_p1;
wire   [128:0] zext_ln147_118_fu_1064_p1;
wire   [128:0] zext_ln148_143_fu_1082_p1;
wire   [128:0] zext_ln148_118_fu_1078_p1;
wire   [128:0] sa_221_fu_1072_p2;
wire   [128:0] sb_221_fu_1086_p2;
wire   [130:0] zext_ln174_449_fu_1131_p1;
wire   [130:0] zext_ln174_448_fu_1128_p1;
wire   [256:0] zext_ln168_fu_1143_p1;
wire   [256:0] zext_ln167_fu_1140_p1;
wire   [130:0] zext_ln174_455_fu_1163_p1;
wire   [130:0] zext_ln174_454_fu_1160_p1;
wire   [256:0] zext_ln168_65_fu_1175_p1;
wire   [256:0] zext_ln167_49_fu_1172_p1;
wire   [131:0] mul_ln174_50_fu_420_p2;
wire   [130:0] zext_ln174_461_fu_1207_p1;
wire   [130:0] zext_ln174_460_fu_1204_p1;
wire   [130:0] add_ln174_99_fu_1210_p2;
wire   [132:0] zext_ln174_459_fu_1200_p1;
wire   [132:0] zext_ln174_462_fu_1216_p1;
wire   [132:0] sub_ln174_50_fu_1220_p2;
wire   [196:0] tmp_475_fu_1226_p3;
wire  signed [257:0] sext_ln175_66_fu_1234_p1;
wire   [257:0] res_318_fu_1238_p3;
wire   [1:0] z2_260_fu_1272_p0;
wire   [1:0] z2_260_fu_1272_p1;
wire   [64:0] zext_ln147_119_fu_1294_p1;
wire   [64:0] zext_ln148_119_fu_1302_p1;
wire   [64:0] sa_216_fu_1297_p2;
wire   [64:0] sb_216_fu_1305_p2;
wire   [128:0] zext_ln174_466_fu_1320_p1;
wire   [132:0] zext_ln174_447_fu_1330_p1;
wire   [132:0] zext_ln174_450_fu_1333_p1;
wire   [132:0] sub_ln174_fu_1336_p2;
wire   [196:0] tmp_470_fu_1342_p3;
wire  signed [257:0] sext_ln175_fu_1350_p1;
wire   [257:0] res_fu_1354_p3;
wire   [0:0] tmp_fu_1366_p3;
wire   [257:0] or_ln175_fu_1360_p2;
wire   [258:0] res_316_fu_1374_p3;
wire  signed [259:0] sext_ln172_fu_1382_p1;
wire   [259:0] zext_ln169_fu_1386_p1;
wire   [259:0] z1e_fu_1389_p2;
wire   [387:0] shl_ln_fu_1395_p3;
wire  signed [511:0] sext_ln138_fu_1403_p1;
wire   [511:0] z0_166_fu_1407_p3;
wire   [132:0] zext_ln174_453_fu_1419_p1;
wire   [132:0] zext_ln174_456_fu_1422_p1;
wire   [132:0] sub_ln174_49_fu_1425_p2;
wire   [196:0] tmp_s_fu_1431_p3;
wire  signed [257:0] sext_ln175_65_fu_1439_p1;
wire   [257:0] res_50_fu_1443_p3;
wire   [0:0] tmp_473_fu_1455_p3;
wire   [257:0] or_ln175_130_fu_1449_p2;
wire   [258:0] res_317_fu_1463_p3;
wire  signed [259:0] sext_ln172_33_fu_1471_p1;
wire   [259:0] zext_ln169_65_fu_1475_p1;
wire   [387:0] shl_ln174_s_fu_1484_p3;
wire  signed [511:0] sext_ln139_fu_1492_p1;
wire   [511:0] z2_258_fu_1496_p3;
wire   [130:0] zext_ln174_465_fu_1514_p1;
wire   [130:0] zext_ln174_467_fu_1517_p1;
wire   [130:0] sub_ln174_51_fu_1520_p2;
wire   [194:0] tmp_481_fu_1526_p3;
wire  signed [256:0] sext_ln175_67_fu_1534_p1;
wire   [256:0] res_52_fu_1538_p3;
wire   [0:0] tmp_482_fu_1550_p3;
wire   [256:0] or_ln175_133_fu_1544_p2;
wire   [257:0] res_320_fu_1558_p3;
wire   [255:0] zext_ln168_66_fu_1570_p1;
wire   [255:0] add_ln169_66_fu_1573_p2;
wire  signed [258:0] sext_ln172_34_fu_1566_p1;
wire   [258:0] zext_ln169_66_fu_1578_p1;
wire   [258:0] z1e_66_fu_1582_p2;
wire   [131:0] trunc_ln175_17_fu_1588_p1;
wire   [259:0] shl_ln175_s_fu_1592_p3;
wire   [259:0] res_53_fu_1600_p3;
wire   [126:0] tmp_483_fu_1612_p4;
wire   [259:0] or_ln175_134_fu_1606_p2;
wire   [386:0] tmp_484_fu_1622_p3;
wire   [258:0] res_319_fu_1508_p3;
wire  signed [383:0] sext_ln168_fu_1637_p1;
wire   [384:0] zext_ln168_67_fu_1641_p1;
wire   [384:0] zext_ln167_50_fu_1634_p1;
wire   [384:0] add_ln169_67_fu_1645_p2;
wire  signed [511:0] res_321_fu_1630_p1;
wire   [511:0] zext_ln169_67_fu_1651_p1;
wire   [511:0] z2_259_fu_1502_p2;
wire   [512:0] zext_ln168_68_fu_1665_p1;
wire   [512:0] zext_ln167_51_fu_1661_p1;
wire   [127:0] trunc_ln174_fu_1695_p1;
wire   [255:0] trunc_ln175_fu_1705_p1;
wire   [514:0] res_54_fu_1723_p4;
wire   [639:0] shl_ln174_16_fu_1716_p3;
wire  signed [639:0] sext_ln174_fu_1730_p1;
wire   [639:0] res_322_fu_1734_p2;
wire   [639:0] zext_ln169_68_fu_1740_p1;
wire   [639:0] z1e_68_fu_1743_p2;
wire   [383:0] tmp_474_fu_1708_p3;
wire   [383:0] tmp_184_fu_1698_p3;
wire   [383:0] or_ln174_fu_1757_p2;
wire   [895:0] tmp_191_fu_1763_p3;
wire   [895:0] shl_ln174_17_fu_1749_p3;
wire   [895:0] or_ln175_136_fu_1770_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire   [131:0] mul_ln174_49_fu_416_p00;
wire   [131:0] mul_ln174_49_fu_416_p10;
wire   [131:0] mul_ln174_50_fu_420_p00;
wire   [131:0] mul_ln174_50_fu_420_p10;
wire   [131:0] mul_ln174_fu_412_p00;
wire   [131:0] mul_ln174_fu_412_p10;
wire   [127:0] z0_162_fu_388_p00;
wire   [127:0] z0_162_fu_388_p10;
wire   [127:0] z0_163_fu_392_p00;
wire   [127:0] z0_163_fu_392_p10;
wire   [255:0] z0_168_fu_432_p00;
wire   [255:0] z0_168_fu_432_p10;
wire   [129:0] z2_250_fu_404_p00;
wire   [129:0] z2_250_fu_404_p10;
wire   [128:0] z2_255_fu_396_p00;
wire   [128:0] z2_255_fu_396_p10;
wire   [255:0] z2_257_fu_436_p00;
wire   [255:0] z2_257_fu_436_p10;
wire   [3:0] z2_260_fu_1272_p00;
wire   [3:0] z2_260_fu_1272_p10;
wire   [129:0] z2_fu_408_p00;
wire   [129:0] z2_fu_408_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

sikep503_kem_enc_hw_mul_64ns_64ns_128_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 128 ))
mul_64ns_64ns_128_1_1_U1036(
    .din0(grp_fu_384_p0),
    .din1(grp_fu_384_p1),
    .dout(grp_fu_384_p2)
);

sikep503_kem_enc_hw_mul_64ns_64ns_128_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 128 ))
mul_64ns_64ns_128_1_1_U1037(
    .din0(z0_162_fu_388_p0),
    .din1(z0_162_fu_388_p1),
    .dout(z0_162_fu_388_p2)
);

sikep503_kem_enc_hw_mul_64ns_64ns_128_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 128 ))
mul_64ns_64ns_128_1_1_U1038(
    .din0(z0_163_fu_392_p0),
    .din1(z0_163_fu_392_p1),
    .dout(z0_163_fu_392_p2)
);

sikep503_kem_enc_hw_mul_65ns_65ns_129_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 65 ),
    .dout_WIDTH( 129 ))
mul_65ns_65ns_129_1_1_U1039(
    .din0(z2_255_fu_396_p0),
    .din1(z2_255_fu_396_p1),
    .dout(z2_255_fu_396_p2)
);

sikep503_kem_enc_hw_mul_65ns_65ns_130_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 65 ),
    .dout_WIDTH( 130 ))
mul_65ns_65ns_130_1_1_U1040(
    .din0(grp_fu_400_p0),
    .din1(grp_fu_400_p1),
    .dout(grp_fu_400_p2)
);

sikep503_kem_enc_hw_mul_65ns_65ns_130_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 65 ),
    .dout_WIDTH( 130 ))
mul_65ns_65ns_130_1_1_U1041(
    .din0(z2_250_fu_404_p0),
    .din1(z2_250_fu_404_p1),
    .dout(z2_250_fu_404_p2)
);

sikep503_kem_enc_hw_mul_65ns_65ns_130_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 65 ),
    .dout_WIDTH( 130 ))
mul_65ns_65ns_130_1_1_U1042(
    .din0(z2_fu_408_p0),
    .din1(z2_fu_408_p1),
    .dout(z2_fu_408_p2)
);

sikep503_kem_enc_hw_mul_66ns_66ns_132_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 66 ),
    .din1_WIDTH( 66 ),
    .dout_WIDTH( 132 ))
mul_66ns_66ns_132_1_1_U1043(
    .din0(mul_ln174_fu_412_p0),
    .din1(mul_ln174_fu_412_p1),
    .dout(mul_ln174_fu_412_p2)
);

sikep503_kem_enc_hw_mul_66ns_66ns_132_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 66 ),
    .din1_WIDTH( 66 ),
    .dout_WIDTH( 132 ))
mul_66ns_66ns_132_1_1_U1044(
    .din0(mul_ln174_49_fu_416_p0),
    .din1(mul_ln174_49_fu_416_p1),
    .dout(mul_ln174_49_fu_416_p2)
);

sikep503_kem_enc_hw_mul_66ns_66ns_132_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 66 ),
    .din1_WIDTH( 66 ),
    .dout_WIDTH( 132 ))
mul_66ns_66ns_132_1_1_U1045(
    .din0(mul_ln174_50_fu_420_p0),
    .din1(mul_ln174_50_fu_420_p1),
    .dout(mul_ln174_50_fu_420_p2)
);

sikep503_kem_enc_hw_mul_128ns_128ns_256_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 128 ),
    .din1_WIDTH( 128 ),
    .dout_WIDTH( 256 ))
mul_128ns_128ns_256_1_1_U1046(
    .din0(grp_fu_424_p0),
    .din1(grp_fu_424_p1),
    .dout(grp_fu_424_p2)
);

sikep503_kem_enc_hw_mul_128ns_128ns_256_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 128 ),
    .din1_WIDTH( 128 ),
    .dout_WIDTH( 256 ))
mul_128ns_128ns_256_1_1_U1047(
    .din0(grp_fu_428_p0),
    .din1(grp_fu_428_p1),
    .dout(grp_fu_428_p2)
);

sikep503_kem_enc_hw_mul_128ns_128ns_256_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 128 ),
    .din1_WIDTH( 128 ),
    .dout_WIDTH( 256 ))
mul_128ns_128ns_256_1_1_U1048(
    .din0(z0_168_fu_432_p0),
    .din1(z0_168_fu_432_p1),
    .dout(z0_168_fu_432_p2)
);

sikep503_kem_enc_hw_mul_128ns_128ns_256_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 128 ),
    .din1_WIDTH( 128 ),
    .dout_WIDTH( 256 ))
mul_128ns_128ns_256_1_1_U1049(
    .din0(z2_257_fu_436_p0),
    .din1(z2_257_fu_436_p1),
    .dout(z2_257_fu_436_p2)
);

sikep503_kem_enc_hw_mul_2ns_2ns_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2ns_4_1_1_U1050(
    .din0(z2_260_fu_1272_p0),
    .din1(z2_260_fu_1272_p1),
    .dout(z2_260_fu_1272_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a0_133_reg_2154 <= a0_133_fu_892_p1;
        a0_135_reg_2186 <= a0_135_fu_1036_p1;
        a0_136_reg_2206 <= a0_136_fu_1092_p1;
        a1_67_reg_2218 <= {{sa_221_fu_1072_p2[128:64]}};
        add_ln169_68_reg_2325 <= add_ln169_68_fu_1669_p2;
        b0_133_reg_2159 <= b0_133_fu_896_p1;
        b0_135_reg_2191 <= b0_135_fu_1040_p1;
        b0_136_reg_2212 <= b0_136_fu_1096_p1;
        b1_67_reg_2224 <= {{sb_221_fu_1086_p2[128:64]}};
        sa_211_reg_2144 <= sa_211_fu_832_p2;
        sa_213_reg_2176 <= sa_213_fu_976_p2;
        sa_reg_2103 <= sa_fu_668_p2;
        sb_211_reg_2149 <= sb_211_fu_846_p2;
        sb_213_reg_2181 <= sb_213_fu_990_p2;
        sb_reg_2108 <= sb_fu_682_p2;
        tmp_479_reg_2196 <= {{sa_220_fu_1010_p2[129:128]}};
        tmp_480_reg_2201 <= {{sb_220_fu_1030_p2[129:128]}};
        w_472_reg_2113 <= w_472_fu_688_p1;
        w_472_reg_2113_pp0_iter1_reg <= w_472_reg_2113;
        w_486_reg_2330 <= {{z2_259_fu_1502_p2[447:384]}};
        w_487_reg_2335 <= {{z2_259_fu_1502_p2[511:448]}};
        z0_162_reg_2132 <= z0_162_fu_388_p2;
        z0_163_reg_2164 <= z0_163_fu_392_p2;
        z0_167_reg_2310 <= z0_167_fu_1413_p2;
        z0_168_reg_2118 <= z0_168_fu_432_p2;
        z0_168_reg_2118_pp0_iter1_reg <= z0_168_reg_2118;
        z1e_65_reg_2315 <= z1e_65_fu_1478_p2;
        z1e_67_reg_2320 <= z1e_67_fu_1655_p2;
        z2_250_reg_2138 <= z2_250_fu_404_p2;
        z2_257_reg_2125 <= z2_257_fu_436_p2;
        z2_257_reg_2125_pp0_iter1_reg <= z2_257_reg_2125;
        z2_reg_2170 <= z2_fu_408_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln169_65_reg_2255 <= add_ln169_65_fu_1178_p2;
        add_ln169_reg_2240 <= add_ln169_fu_1146_p2;
        add_ln174_100_reg_2305 <= add_ln174_100_fu_1324_p2;
        add_ln174_98_reg_2250 <= add_ln174_98_fu_1166_p2;
        add_ln174_reg_2235 <= add_ln174_fu_1134_p2;
        mul_ln174_49_reg_2245 <= mul_ln174_49_fu_416_p2;
        mul_ln174_reg_2230 <= mul_ln174_fu_412_p2;
        or_ln175_132_reg_2266 <= or_ln175_132_fu_1244_p2;
        tmp_476_reg_2272 <= sub_ln174_50_fu_1220_p2[32'd132];
        z2_255_reg_2295 <= z2_255_fu_396_p2;
        z2_260_reg_2284 <= z2_260_fu_1272_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln174_51_reg_2300 <= grp_fu_400_p2;
        z0_165_reg_2290 <= grp_fu_384_p2;
        z0_169_reg_2260 <= grp_fu_424_p2;
        z0_170_reg_2278 <= grp_fu_428_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        z0_161_reg_2091 <= grp_fu_384_p2;
        z0_reg_2079 <= grp_fu_424_p2;
        z2_248_reg_2097 <= grp_fu_400_p2;
        z2_256_reg_2085 <= grp_fu_428_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_0_ce0_local = 1'b1;
    end else begin
        A_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_1_ce0_local = 1'b1;
    end else begin
        A_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_2_ce0_local = 1'b1;
    end else begin
        A_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_3_ce0_local = 1'b1;
    end else begin
        A_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_4_ce0_local = 1'b1;
    end else begin
        A_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_5_ce0_local = 1'b1;
    end else begin
        A_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_6_ce0_local = 1'b1;
    end else begin
        A_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_7_ce0_local = 1'b1;
    end else begin
        A_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_0_ce0_local = 1'b1;
    end else begin
        b_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_1_ce0_local = 1'b1;
    end else begin
        b_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_2_ce0_local = 1'b1;
    end else begin
        b_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_3_ce0_local = 1'b1;
    end else begin
        b_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_4_ce0_local = 1'b1;
    end else begin
        b_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_5_ce0_local = 1'b1;
    end else begin
        b_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_6_ce0_local = 1'b1;
    end else begin
        b_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_7_ce0_local = 1'b1;
    end else begin
        b_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_384_p0 = zext_ln121_314_fu_1290_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_384_p0 = zext_ln121_296_fu_645_p1;
    end else begin
        grp_fu_384_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_384_p1 = zext_ln121_313_fu_1286_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_384_p1 = zext_ln121_295_fu_640_p1;
    end else begin
        grp_fu_384_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_400_p0 = zext_ln174_464_fu_1315_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_400_p0 = zext_ln121_298_fu_655_p1;
    end else begin
        grp_fu_400_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_400_p1 = zext_ln174_463_fu_1310_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_400_p1 = zext_ln121_297_fu_650_p1;
    end else begin
        grp_fu_400_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_424_p0 = zext_ln121_307_fu_1188_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_424_p0 = zext_ln121_294_fu_575_p1;
    end else begin
        grp_fu_424_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_424_p1 = zext_ln121_305_fu_1184_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_424_p1 = zext_ln121_fu_570_p1;
    end else begin
        grp_fu_424_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_428_p0 = zext_ln121_312_fu_1262_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_428_p0 = zext_ln136_fu_565_p1;
    end else begin
        grp_fu_428_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_428_p1 = zext_ln121_311_fu_1258_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_428_p1 = zext_ln135_fu_552_p1;
    end else begin
        grp_fu_428_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_0_address0 = 64'd0;

assign A_0_ce0 = A_0_ce0_local;

assign A_1_address0 = 64'd0;

assign A_1_ce0 = A_1_ce0_local;

assign A_2_address0 = 64'd0;

assign A_2_ce0 = A_2_ce0_local;

assign A_3_address0 = 64'd0;

assign A_3_ce0 = A_3_ce0_local;

assign A_4_address0 = 64'd0;

assign A_4_ce0 = A_4_ce0_local;

assign A_5_address0 = 64'd0;

assign A_5_ce0 = A_5_ce0_local;

assign A_6_address0 = 64'd0;

assign A_6_ce0 = A_6_ce0_local;

assign A_7_address0 = 64'd0;

assign A_7_ce0 = A_7_ce0_local;

assign a0_129_fu_440_p3 = {{A_1_q0}, {A_0_q0}};

assign a0_130_fu_588_p2 = (A_2_q0 + A_0_q0);

assign a0_131_fu_692_p3 = {{A_5_q0}, {A_4_q0}};

assign a0_132_fu_752_p2 = (A_4_q0 + A_6_q0);

assign a0_133_fu_892_p1 = add_ln147_fu_860_p2[127:0];

assign a0_134_fu_908_p4 = {{add_ln147_fu_860_p2[191:128]}};

assign a0_135_fu_1036_p1 = sa_220_fu_1010_p2[127:0];

assign a0_136_fu_1092_p1 = sa_221_fu_1072_p2[63:0];

assign a0_cast_fu_468_p4 = {{{A_2_q0}, {A_1_q0}}, {A_0_q0}};

assign a0_fu_456_p5 = {{{{A_3_q0}, {A_2_q0}}, {A_1_q0}}, {A_0_q0}};

assign a1_39_fu_708_p3 = {{A_7_q0}, {A_6_q0}};

assign a1_40_fu_784_p4 = {{sa_218_fu_758_p2[128:64]}};

assign a1_66_fu_544_p3 = {{A_3_q0}, {A_2_q0}};

assign a1_cast_fu_512_p4 = {{{A_6_q0}, {A_5_q0}}, {A_4_q0}};

assign a1_fu_500_p5 = {{{{A_7_q0}, {A_6_q0}}, {A_5_q0}}, {A_4_q0}};

assign a1_s_fu_620_p4 = {{sa_217_fu_594_p2[128:64]}};

assign add_ln147_fu_860_p2 = (a1_cast_fu_512_p4 + a0_cast_fu_468_p4);

assign add_ln148_fu_880_p2 = (b1_cast_fu_534_p4 + b0_cast_fu_490_p4);

assign add_ln169_65_fu_1178_p2 = (zext_ln168_65_fu_1175_p1 + zext_ln167_49_fu_1172_p1);

assign add_ln169_66_fu_1573_p2 = (zext_ln168_66_fu_1570_p1 + z0_170_reg_2278);

assign add_ln169_67_fu_1645_p2 = (zext_ln168_67_fu_1641_p1 + zext_ln167_50_fu_1634_p1);

assign add_ln169_68_fu_1669_p2 = (zext_ln168_68_fu_1665_p1 + zext_ln167_51_fu_1661_p1);

assign add_ln169_fu_1146_p2 = (zext_ln168_fu_1143_p1 + zext_ln167_fu_1140_p1);

assign add_ln174_100_fu_1324_p2 = (z2_255_fu_396_p2 + zext_ln174_466_fu_1320_p1);

assign add_ln174_98_fu_1166_p2 = (zext_ln174_455_fu_1163_p1 + zext_ln174_454_fu_1160_p1);

assign add_ln174_99_fu_1210_p2 = (zext_ln174_461_fu_1207_p1 + zext_ln174_460_fu_1204_p1);

assign add_ln174_fu_1134_p2 = (zext_ln174_449_fu_1131_p1 + zext_ln174_448_fu_1128_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = w_472_reg_2113_pp0_iter1_reg;

assign ap_return_1 = {{or_ln175_136_fu_1770_p2[127:64]}};

assign ap_return_10 = {{or_ln175_136_fu_1770_p2[703:640]}};

assign ap_return_11 = {{or_ln175_136_fu_1770_p2[767:704]}};

assign ap_return_12 = {{or_ln175_136_fu_1770_p2[831:768]}};

assign ap_return_13 = {{or_ln175_136_fu_1770_p2[895:832]}};

assign ap_return_14 = w_486_reg_2330;

assign ap_return_15 = w_487_reg_2335;

assign ap_return_2 = {{or_ln175_136_fu_1770_p2[191:128]}};

assign ap_return_3 = {{or_ln175_136_fu_1770_p2[255:192]}};

assign ap_return_4 = {{or_ln175_136_fu_1770_p2[319:256]}};

assign ap_return_5 = {{or_ln175_136_fu_1770_p2[383:320]}};

assign ap_return_6 = {{or_ln175_136_fu_1770_p2[447:384]}};

assign ap_return_7 = {{or_ln175_136_fu_1770_p2[511:448]}};

assign ap_return_8 = {{or_ln175_136_fu_1770_p2[575:512]}};

assign ap_return_9 = {{or_ln175_136_fu_1770_p2[639:576]}};

assign b0_129_fu_448_p3 = {{b_1_q0}, {b_0_q0}};

assign b0_130_fu_608_p2 = (b_2_q0 + b_0_q0);

assign b0_131_fu_700_p3 = {{b_5_q0}, {b_4_q0}};

assign b0_132_fu_772_p2 = (b_4_q0 + b_6_q0);

assign b0_133_fu_896_p1 = add_ln148_fu_880_p2[127:0];

assign b0_134_fu_918_p4 = {{add_ln148_fu_880_p2[191:128]}};

assign b0_135_fu_1040_p1 = sb_220_fu_1030_p2[127:0];

assign b0_136_fu_1096_p1 = sb_221_fu_1086_p2[63:0];

assign b0_cast_fu_490_p4 = {{{b_2_q0}, {b_1_q0}}, {b_0_q0}};

assign b0_fu_478_p5 = {{{{b_3_q0}, {b_2_q0}}, {b_1_q0}}, {b_0_q0}};

assign b1_39_fu_716_p3 = {{b_7_q0}, {b_6_q0}};

assign b1_40_fu_794_p4 = {{sb_218_fu_778_p2[128:64]}};

assign b1_66_fu_557_p3 = {{b_3_q0}, {b_2_q0}};

assign b1_cast_fu_534_p4 = {{{b_6_q0}, {b_5_q0}}, {b_4_q0}};

assign b1_fu_522_p5 = {{{{b_7_q0}, {b_6_q0}}, {b_5_q0}}, {b_4_q0}};

assign b1_s_fu_630_p4 = {{sb_217_fu_614_p2[128:64]}};

assign b_0_address0 = 64'd0;

assign b_0_ce0 = b_0_ce0_local;

assign b_1_address0 = 64'd0;

assign b_1_ce0 = b_1_ce0_local;

assign b_2_address0 = 64'd0;

assign b_2_ce0 = b_2_ce0_local;

assign b_3_address0 = 64'd0;

assign b_3_ce0 = b_3_ce0_local;

assign b_4_address0 = 64'd0;

assign b_4_ce0 = b_4_ce0_local;

assign b_5_address0 = 64'd0;

assign b_5_ce0 = b_5_ce0_local;

assign b_6_address0 = 64'd0;

assign b_6_ce0 = b_6_ce0_local;

assign b_7_address0 = 64'd0;

assign b_7_ce0 = b_7_ce0_local;

assign mul_ln174_49_fu_416_p0 = mul_ln174_49_fu_416_p00;

assign mul_ln174_49_fu_416_p00 = sb_211_reg_2149;

assign mul_ln174_49_fu_416_p1 = mul_ln174_49_fu_416_p10;

assign mul_ln174_49_fu_416_p10 = sa_211_reg_2144;

assign mul_ln174_50_fu_420_p0 = mul_ln174_50_fu_420_p00;

assign mul_ln174_50_fu_420_p00 = sb_213_reg_2181;

assign mul_ln174_50_fu_420_p1 = mul_ln174_50_fu_420_p10;

assign mul_ln174_50_fu_420_p10 = sa_213_reg_2176;

assign mul_ln174_fu_412_p0 = mul_ln174_fu_412_p00;

assign mul_ln174_fu_412_p00 = sb_reg_2108;

assign mul_ln174_fu_412_p1 = mul_ln174_fu_412_p10;

assign mul_ln174_fu_412_p10 = sa_reg_2103;

assign or_ln174_fu_1757_p2 = (tmp_474_fu_1708_p3 | tmp_184_fu_1698_p3);

assign or_ln175_130_fu_1449_p2 = (sext_ln175_65_fu_1439_p1 | res_50_fu_1443_p3);

assign or_ln175_132_fu_1244_p2 = (sext_ln175_66_fu_1234_p1 | res_318_fu_1238_p3);

assign or_ln175_133_fu_1544_p2 = (sext_ln175_67_fu_1534_p1 | res_52_fu_1538_p3);

assign or_ln175_134_fu_1606_p2 = (shl_ln175_s_fu_1592_p3 | res_53_fu_1600_p3);

assign or_ln175_136_fu_1770_p2 = (tmp_191_fu_1763_p3 | shl_ln174_17_fu_1749_p3);

assign or_ln175_fu_1360_p2 = (sext_ln175_fu_1350_p1 | res_fu_1354_p3);

assign res_316_fu_1374_p3 = {{tmp_fu_1366_p3}, {or_ln175_fu_1360_p2}};

assign res_317_fu_1463_p3 = {{tmp_473_fu_1455_p3}, {or_ln175_130_fu_1449_p2}};

assign res_318_fu_1238_p3 = {{z2_reg_2170}, {z0_163_reg_2164}};

assign res_319_fu_1508_p3 = {{tmp_476_reg_2272}, {or_ln175_132_reg_2266}};

assign res_320_fu_1558_p3 = {{tmp_482_fu_1550_p3}, {or_ln175_133_fu_1544_p2}};

assign res_321_fu_1630_p1 = $signed(tmp_484_fu_1622_p3);

assign res_322_fu_1734_p2 = (shl_ln174_16_fu_1716_p3 | sext_ln174_fu_1730_p1);

assign res_50_fu_1443_p3 = {{z2_250_reg_2138}, {z0_162_reg_2132}};

assign res_52_fu_1538_p3 = {{z2_255_reg_2295}, {z0_165_reg_2290}};

assign res_53_fu_1600_p3 = {{z2_260_reg_2284}, {z0_170_reg_2278}};

assign res_54_fu_1723_p4 = {{{tmp_476_reg_2272}, {or_ln175_132_reg_2266}}, {z0_169_reg_2260}};

assign res_fu_1354_p3 = {{z2_248_reg_2097}, {z0_161_reg_2091}};

assign sa_211_fu_832_p2 = (zext_ln147_139_fu_828_p1 + zext_ln147_115_fu_824_p1);

assign sa_213_fu_976_p2 = (zext_ln147_141_fu_972_p1 + zext_ln147_117_fu_968_p1);

assign sa_216_fu_1297_p2 = (a1_67_reg_2218 + zext_ln147_119_fu_1294_p1);

assign sa_217_fu_594_p2 = (zext_ln147_136_fu_584_p1 + zext_ln147_fu_580_p1);

assign sa_218_fu_758_p2 = (zext_ln147_114_fu_744_p1 + zext_ln147_138_fu_748_p1);

assign sa_219_fu_866_p2 = (zext_ln147_140_fu_856_p1 + zext_ln147_116_fu_852_p1);

assign sa_220_fu_1010_p2 = (zext_ln147_142_fu_1006_p1 + zext_ln121_306_fu_900_p1);

assign sa_221_fu_1072_p2 = (zext_ln147_143_fu_1068_p1 + zext_ln147_118_fu_1064_p1);

assign sa_fu_668_p2 = (zext_ln147_137_fu_664_p1 + zext_ln147_113_fu_660_p1);

assign sb_211_fu_846_p2 = (zext_ln148_139_fu_842_p1 + zext_ln148_115_fu_838_p1);

assign sb_213_fu_990_p2 = (zext_ln148_141_fu_986_p1 + zext_ln148_117_fu_982_p1);

assign sb_216_fu_1305_p2 = (b1_67_reg_2224 + zext_ln148_119_fu_1302_p1);

assign sb_217_fu_614_p2 = (zext_ln148_136_fu_604_p1 + zext_ln148_fu_600_p1);

assign sb_218_fu_778_p2 = (zext_ln148_114_fu_764_p1 + zext_ln148_138_fu_768_p1);

assign sb_219_fu_886_p2 = (zext_ln148_140_fu_876_p1 + zext_ln148_116_fu_872_p1);

assign sb_220_fu_1030_p2 = (zext_ln148_142_fu_1026_p1 + zext_ln121_308_fu_904_p1);

assign sb_221_fu_1086_p2 = (zext_ln148_143_fu_1082_p1 + zext_ln148_118_fu_1078_p1);

assign sb_fu_682_p2 = (zext_ln148_137_fu_678_p1 + zext_ln148_113_fu_674_p1);

assign sext_ln138_fu_1403_p1 = $signed(shl_ln_fu_1395_p3);

assign sext_ln139_fu_1492_p1 = $signed(shl_ln174_s_fu_1484_p3);

assign sext_ln168_fu_1637_p1 = $signed(res_319_fu_1508_p3);

assign sext_ln172_33_fu_1471_p1 = $signed(res_317_fu_1463_p3);

assign sext_ln172_34_fu_1566_p1 = $signed(res_320_fu_1558_p3);

assign sext_ln172_fu_1382_p1 = $signed(res_316_fu_1374_p3);

assign sext_ln174_fu_1730_p1 = $signed(res_54_fu_1723_p4);

assign sext_ln175_65_fu_1439_p1 = $signed(tmp_s_fu_1431_p3);

assign sext_ln175_66_fu_1234_p1 = $signed(tmp_475_fu_1226_p3);

assign sext_ln175_67_fu_1534_p1 = $signed(tmp_481_fu_1526_p3);

assign sext_ln175_fu_1350_p1 = $signed(tmp_470_fu_1342_p3);

assign shl_ln174_16_fu_1716_p3 = {{z1e_67_reg_2320}, {128'd0}};

assign shl_ln174_17_fu_1749_p3 = {{z1e_68_fu_1743_p2}, {256'd0}};

assign shl_ln174_s_fu_1484_p3 = {{z1e_65_fu_1478_p2}, {128'd0}};

assign shl_ln175_s_fu_1592_p3 = {{trunc_ln175_17_fu_1588_p1}, {128'd0}};

assign shl_ln_fu_1395_p3 = {{z1e_fu_1389_p2}, {128'd0}};

assign sub_ln174_49_fu_1425_p2 = (zext_ln174_453_fu_1419_p1 - zext_ln174_456_fu_1422_p1);

assign sub_ln174_50_fu_1220_p2 = (zext_ln174_459_fu_1200_p1 - zext_ln174_462_fu_1216_p1);

assign sub_ln174_51_fu_1520_p2 = (zext_ln174_465_fu_1514_p1 - zext_ln174_467_fu_1517_p1);

assign sub_ln174_fu_1336_p2 = (zext_ln174_447_fu_1330_p1 - zext_ln174_450_fu_1333_p1);

assign tmp_184_fu_1698_p3 = {{trunc_ln174_fu_1695_p1}, {z0_168_reg_2118_pp0_iter1_reg}};

assign tmp_191_fu_1763_p3 = {{or_ln174_fu_1757_p2}, {z0_167_reg_2310}};

assign tmp_470_fu_1342_p3 = {{sub_ln174_fu_1336_p2}, {64'd0}};

assign tmp_471_fu_938_p4 = {{sa_219_fu_866_p2[256:192]}};

assign tmp_472_fu_953_p4 = {{sb_219_fu_886_p2[256:192]}};

assign tmp_473_fu_1455_p3 = sub_ln174_49_fu_1425_p2[32'd132];

assign tmp_474_fu_1708_p3 = {{trunc_ln175_fu_1705_p1}, {128'd0}};

assign tmp_475_fu_1226_p3 = {{sub_ln174_50_fu_1220_p2}, {64'd0}};

assign tmp_477_fu_996_p4 = {{sa_219_fu_866_p2[256:128]}};

assign tmp_478_fu_1016_p4 = {{sb_219_fu_886_p2[256:128]}};

assign tmp_479_fu_1044_p4 = {{sa_220_fu_1010_p2[129:128]}};

assign tmp_480_fu_1054_p4 = {{sb_220_fu_1030_p2[129:128]}};

assign tmp_481_fu_1526_p3 = {{sub_ln174_51_fu_1520_p2}, {64'd0}};

assign tmp_482_fu_1550_p3 = sub_ln174_51_fu_1520_p2[32'd130];

assign tmp_483_fu_1612_p4 = {{z1e_66_fu_1582_p2[258:132]}};

assign tmp_484_fu_1622_p3 = {{tmp_483_fu_1612_p4}, {or_ln175_134_fu_1606_p2}};

assign tmp_fu_1366_p3 = sub_ln174_fu_1336_p2[32'd132];

assign tmp_s_fu_1431_p3 = {{sub_ln174_49_fu_1425_p2}, {64'd0}};

assign trunc_ln174_fu_1695_p1 = z2_257_reg_2125_pp0_iter1_reg[127:0];

assign trunc_ln175_17_fu_1588_p1 = z1e_66_fu_1582_p2[131:0];

assign trunc_ln175_fu_1705_p1 = z1e_65_reg_2315[255:0];

assign w_472_fu_688_p1 = grp_fu_424_p2[63:0];

assign z0_162_fu_388_p0 = z0_162_fu_388_p00;

assign z0_162_fu_388_p00 = b0_132_fu_772_p2;

assign z0_162_fu_388_p1 = z0_162_fu_388_p10;

assign z0_162_fu_388_p10 = a0_132_fu_752_p2;

assign z0_163_fu_392_p0 = z0_163_fu_392_p00;

assign z0_163_fu_392_p00 = b0_134_fu_918_p4;

assign z0_163_fu_392_p1 = z0_163_fu_392_p10;

assign z0_163_fu_392_p10 = a0_134_fu_908_p4;

assign z0_166_fu_1407_p3 = {{z2_256_reg_2085}, {z0_reg_2079}};

assign z0_167_fu_1413_p2 = (z0_166_fu_1407_p3 | sext_ln138_fu_1403_p1);

assign z0_168_fu_432_p0 = z0_168_fu_432_p00;

assign z0_168_fu_432_p00 = b0_131_fu_700_p3;

assign z0_168_fu_432_p1 = z0_168_fu_432_p10;

assign z0_168_fu_432_p10 = a0_131_fu_692_p3;

assign z1e_65_fu_1478_p2 = ($signed(sext_ln172_33_fu_1471_p1) - $signed(zext_ln169_65_fu_1475_p1));

assign z1e_66_fu_1582_p2 = ($signed(sext_ln172_34_fu_1566_p1) - $signed(zext_ln169_66_fu_1578_p1));

assign z1e_67_fu_1655_p2 = ($signed(res_321_fu_1630_p1) - $signed(zext_ln169_67_fu_1651_p1));

assign z1e_68_fu_1743_p2 = (res_322_fu_1734_p2 - zext_ln169_68_fu_1740_p1);

assign z1e_fu_1389_p2 = ($signed(sext_ln172_fu_1382_p1) - $signed(zext_ln169_fu_1386_p1));

assign z2_250_fu_404_p0 = z2_250_fu_404_p00;

assign z2_250_fu_404_p00 = b1_40_fu_794_p4;

assign z2_250_fu_404_p1 = z2_250_fu_404_p10;

assign z2_250_fu_404_p10 = a1_40_fu_784_p4;

assign z2_255_fu_396_p0 = z2_255_fu_396_p00;

assign z2_255_fu_396_p00 = b1_67_reg_2224;

assign z2_255_fu_396_p1 = z2_255_fu_396_p10;

assign z2_255_fu_396_p10 = a1_67_reg_2218;

assign z2_257_fu_436_p0 = z2_257_fu_436_p00;

assign z2_257_fu_436_p00 = b1_39_fu_716_p3;

assign z2_257_fu_436_p1 = z2_257_fu_436_p10;

assign z2_257_fu_436_p10 = a1_39_fu_708_p3;

assign z2_258_fu_1496_p3 = {{z2_257_reg_2125}, {z0_168_reg_2118}};

assign z2_259_fu_1502_p2 = (z2_258_fu_1496_p3 | sext_ln139_fu_1492_p1);

assign z2_260_fu_1272_p0 = z2_260_fu_1272_p00;

assign z2_260_fu_1272_p00 = tmp_480_reg_2201;

assign z2_260_fu_1272_p1 = z2_260_fu_1272_p10;

assign z2_260_fu_1272_p10 = tmp_479_reg_2196;

assign z2_fu_408_p0 = z2_fu_408_p00;

assign z2_fu_408_p00 = tmp_472_fu_953_p4;

assign z2_fu_408_p1 = z2_fu_408_p10;

assign z2_fu_408_p10 = tmp_471_fu_938_p4;

assign zext_ln121_294_fu_575_p1 = b0_129_fu_448_p3;

assign zext_ln121_295_fu_640_p1 = a0_130_fu_588_p2;

assign zext_ln121_296_fu_645_p1 = b0_130_fu_608_p2;

assign zext_ln121_297_fu_650_p1 = a1_s_fu_620_p4;

assign zext_ln121_298_fu_655_p1 = b1_s_fu_630_p4;

assign zext_ln121_305_fu_1184_p1 = a0_133_reg_2154;

assign zext_ln121_306_fu_900_p1 = a0_133_fu_892_p1;

assign zext_ln121_307_fu_1188_p1 = b0_133_reg_2159;

assign zext_ln121_308_fu_904_p1 = b0_133_fu_896_p1;

assign zext_ln121_311_fu_1258_p1 = a0_135_reg_2186;

assign zext_ln121_312_fu_1262_p1 = b0_135_reg_2191;

assign zext_ln121_313_fu_1286_p1 = a0_136_reg_2206;

assign zext_ln121_314_fu_1290_p1 = b0_136_reg_2212;

assign zext_ln121_fu_570_p1 = a0_129_fu_440_p3;

assign zext_ln135_fu_552_p1 = a1_66_fu_544_p3;

assign zext_ln136_fu_565_p1 = b1_66_fu_557_p3;

assign zext_ln147_113_fu_660_p1 = a0_130_fu_588_p2;

assign zext_ln147_114_fu_744_p1 = a0_131_fu_692_p3;

assign zext_ln147_115_fu_824_p1 = a0_132_fu_752_p2;

assign zext_ln147_116_fu_852_p1 = a0_fu_456_p5;

assign zext_ln147_117_fu_968_p1 = a0_134_fu_908_p4;

assign zext_ln147_118_fu_1064_p1 = a0_135_fu_1036_p1;

assign zext_ln147_119_fu_1294_p1 = a0_136_reg_2206;

assign zext_ln147_136_fu_584_p1 = a1_66_fu_544_p3;

assign zext_ln147_137_fu_664_p1 = a1_s_fu_620_p4;

assign zext_ln147_138_fu_748_p1 = a1_39_fu_708_p3;

assign zext_ln147_139_fu_828_p1 = a1_40_fu_784_p4;

assign zext_ln147_140_fu_856_p1 = a1_fu_500_p5;

assign zext_ln147_141_fu_972_p1 = tmp_471_fu_938_p4;

assign zext_ln147_142_fu_1006_p1 = tmp_477_fu_996_p4;

assign zext_ln147_143_fu_1068_p1 = tmp_479_fu_1044_p4;

assign zext_ln147_fu_580_p1 = a0_129_fu_440_p3;

assign zext_ln148_113_fu_674_p1 = b0_130_fu_608_p2;

assign zext_ln148_114_fu_764_p1 = b0_131_fu_700_p3;

assign zext_ln148_115_fu_838_p1 = b0_132_fu_772_p2;

assign zext_ln148_116_fu_872_p1 = b0_fu_478_p5;

assign zext_ln148_117_fu_982_p1 = b0_134_fu_918_p4;

assign zext_ln148_118_fu_1078_p1 = b0_135_fu_1040_p1;

assign zext_ln148_119_fu_1302_p1 = b0_136_reg_2212;

assign zext_ln148_136_fu_604_p1 = b1_66_fu_557_p3;

assign zext_ln148_137_fu_678_p1 = b1_s_fu_630_p4;

assign zext_ln148_138_fu_768_p1 = b1_39_fu_716_p3;

assign zext_ln148_139_fu_842_p1 = b1_40_fu_794_p4;

assign zext_ln148_140_fu_876_p1 = b1_fu_522_p5;

assign zext_ln148_141_fu_986_p1 = tmp_472_fu_953_p4;

assign zext_ln148_142_fu_1026_p1 = tmp_478_fu_1016_p4;

assign zext_ln148_143_fu_1082_p1 = tmp_480_fu_1054_p4;

assign zext_ln148_fu_600_p1 = b0_129_fu_448_p3;

assign zext_ln167_49_fu_1172_p1 = z0_168_reg_2118;

assign zext_ln167_50_fu_1634_p1 = z0_169_reg_2260;

assign zext_ln167_51_fu_1661_p1 = z0_167_fu_1413_p2;

assign zext_ln167_fu_1140_p1 = z0_reg_2079;

assign zext_ln168_65_fu_1175_p1 = z2_257_reg_2125;

assign zext_ln168_66_fu_1570_p1 = z2_260_reg_2284;

assign zext_ln168_67_fu_1641_p1 = $unsigned(sext_ln168_fu_1637_p1);

assign zext_ln168_68_fu_1665_p1 = z2_259_fu_1502_p2;

assign zext_ln168_fu_1143_p1 = z2_256_reg_2085;

assign zext_ln169_65_fu_1475_p1 = add_ln169_65_reg_2255;

assign zext_ln169_66_fu_1578_p1 = add_ln169_66_fu_1573_p2;

assign zext_ln169_67_fu_1651_p1 = add_ln169_67_fu_1645_p2;

assign zext_ln169_68_fu_1740_p1 = add_ln169_68_reg_2325;

assign zext_ln169_fu_1386_p1 = add_ln169_reg_2240;

assign zext_ln174_447_fu_1330_p1 = mul_ln174_reg_2230;

assign zext_ln174_448_fu_1128_p1 = z0_161_reg_2091;

assign zext_ln174_449_fu_1131_p1 = z2_248_reg_2097;

assign zext_ln174_450_fu_1333_p1 = add_ln174_reg_2235;

assign zext_ln174_453_fu_1419_p1 = mul_ln174_49_reg_2245;

assign zext_ln174_454_fu_1160_p1 = z0_162_reg_2132;

assign zext_ln174_455_fu_1163_p1 = z2_250_reg_2138;

assign zext_ln174_456_fu_1422_p1 = add_ln174_98_reg_2250;

assign zext_ln174_459_fu_1200_p1 = mul_ln174_50_fu_420_p2;

assign zext_ln174_460_fu_1204_p1 = z0_163_reg_2164;

assign zext_ln174_461_fu_1207_p1 = z2_reg_2170;

assign zext_ln174_462_fu_1216_p1 = add_ln174_99_fu_1210_p2;

assign zext_ln174_463_fu_1310_p1 = sa_216_fu_1297_p2;

assign zext_ln174_464_fu_1315_p1 = sb_216_fu_1305_p2;

assign zext_ln174_465_fu_1514_p1 = mul_ln174_51_reg_2300;

assign zext_ln174_466_fu_1320_p1 = grp_fu_384_p2;

assign zext_ln174_467_fu_1517_p1 = add_ln174_100_reg_2305;

endmodule //sikep503_kem_enc_hw_mul_148
