// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sikep503_kem_enc_hw_fp2sqr503_mont_40 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        R_X_address0,
        R_X_ce0,
        R_X_q0,
        R_X_address1,
        R_X_ce1,
        R_X_q1,
        A24plus_0_address0,
        A24plus_0_ce0,
        A24plus_0_we0,
        A24plus_0_d0,
        A24plus_0_q0,
        A24plus_1_address0,
        A24plus_1_ce0,
        A24plus_1_we0,
        A24plus_1_d0,
        A24plus_1_q0,
        A24plus_2_address0,
        A24plus_2_ce0,
        A24plus_2_we0,
        A24plus_2_d0,
        A24plus_2_q0,
        A24plus_3_address0,
        A24plus_3_ce0,
        A24plus_3_we0,
        A24plus_3_d0,
        A24plus_3_q0,
        A24plus_4_address0,
        A24plus_4_ce0,
        A24plus_4_we0,
        A24plus_4_d0,
        A24plus_4_q0,
        A24plus_5_address0,
        A24plus_5_ce0,
        A24plus_5_we0,
        A24plus_5_d0,
        A24plus_5_q0,
        A24plus_6_address0,
        A24plus_6_ce0,
        A24plus_6_we0,
        A24plus_6_d0,
        A24plus_6_q0,
        A24plus_7_address0,
        A24plus_7_ce0,
        A24plus_7_we0,
        A24plus_7_d0,
        A24plus_7_q0
);

parameter    ap_ST_fsm_state1 = 30'd1;
parameter    ap_ST_fsm_state2 = 30'd2;
parameter    ap_ST_fsm_state3 = 30'd4;
parameter    ap_ST_fsm_state4 = 30'd8;
parameter    ap_ST_fsm_state5 = 30'd16;
parameter    ap_ST_fsm_state6 = 30'd32;
parameter    ap_ST_fsm_state7 = 30'd64;
parameter    ap_ST_fsm_state8 = 30'd128;
parameter    ap_ST_fsm_state9 = 30'd256;
parameter    ap_ST_fsm_state10 = 30'd512;
parameter    ap_ST_fsm_state11 = 30'd1024;
parameter    ap_ST_fsm_state12 = 30'd2048;
parameter    ap_ST_fsm_state13 = 30'd4096;
parameter    ap_ST_fsm_state14 = 30'd8192;
parameter    ap_ST_fsm_state15 = 30'd16384;
parameter    ap_ST_fsm_state16 = 30'd32768;
parameter    ap_ST_fsm_state17 = 30'd65536;
parameter    ap_ST_fsm_state18 = 30'd131072;
parameter    ap_ST_fsm_state19 = 30'd262144;
parameter    ap_ST_fsm_state20 = 30'd524288;
parameter    ap_ST_fsm_state21 = 30'd1048576;
parameter    ap_ST_fsm_state22 = 30'd2097152;
parameter    ap_ST_fsm_state23 = 30'd4194304;
parameter    ap_ST_fsm_state24 = 30'd8388608;
parameter    ap_ST_fsm_state25 = 30'd16777216;
parameter    ap_ST_fsm_state26 = 30'd33554432;
parameter    ap_ST_fsm_state27 = 30'd67108864;
parameter    ap_ST_fsm_state28 = 30'd134217728;
parameter    ap_ST_fsm_state29 = 30'd268435456;
parameter    ap_ST_fsm_state30 = 30'd536870912;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] R_X_address0;
output   R_X_ce0;
input  [63:0] R_X_q0;
output  [3:0] R_X_address1;
output   R_X_ce1;
input  [63:0] R_X_q1;
output  [0:0] A24plus_0_address0;
output   A24plus_0_ce0;
output   A24plus_0_we0;
output  [63:0] A24plus_0_d0;
input  [63:0] A24plus_0_q0;
output  [0:0] A24plus_1_address0;
output   A24plus_1_ce0;
output   A24plus_1_we0;
output  [63:0] A24plus_1_d0;
input  [63:0] A24plus_1_q0;
output  [0:0] A24plus_2_address0;
output   A24plus_2_ce0;
output   A24plus_2_we0;
output  [63:0] A24plus_2_d0;
input  [63:0] A24plus_2_q0;
output  [0:0] A24plus_3_address0;
output   A24plus_3_ce0;
output   A24plus_3_we0;
output  [63:0] A24plus_3_d0;
input  [63:0] A24plus_3_q0;
output  [0:0] A24plus_4_address0;
output   A24plus_4_ce0;
output   A24plus_4_we0;
output  [63:0] A24plus_4_d0;
input  [63:0] A24plus_4_q0;
output  [0:0] A24plus_5_address0;
output   A24plus_5_ce0;
output   A24plus_5_we0;
output  [63:0] A24plus_5_d0;
input  [63:0] A24plus_5_q0;
output  [0:0] A24plus_6_address0;
output   A24plus_6_ce0;
output   A24plus_6_we0;
output  [63:0] A24plus_6_d0;
input  [63:0] A24plus_6_q0;
output  [0:0] A24plus_7_address0;
output   A24plus_7_ce0;
output   A24plus_7_we0;
output  [63:0] A24plus_7_d0;
input  [63:0] A24plus_7_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] R_X_address0;
reg R_X_ce0;
reg[3:0] R_X_address1;
reg R_X_ce1;
reg[0:0] A24plus_0_address0;
reg A24plus_0_ce0;
reg A24plus_0_we0;
reg[63:0] A24plus_0_d0;
reg[0:0] A24plus_1_address0;
reg A24plus_1_ce0;
reg A24plus_1_we0;
reg[63:0] A24plus_1_d0;
reg[0:0] A24plus_2_address0;
reg A24plus_2_ce0;
reg A24plus_2_we0;
reg[63:0] A24plus_2_d0;
reg[0:0] A24plus_3_address0;
reg A24plus_3_ce0;
reg A24plus_3_we0;
reg[63:0] A24plus_3_d0;
reg[0:0] A24plus_4_address0;
reg A24plus_4_ce0;
reg A24plus_4_we0;
reg[63:0] A24plus_4_d0;
reg[0:0] A24plus_5_address0;
reg A24plus_5_ce0;
reg A24plus_5_we0;
reg[63:0] A24plus_5_d0;
reg[0:0] A24plus_6_address0;
reg A24plus_6_ce0;
reg A24plus_6_we0;
reg[63:0] A24plus_6_d0;
reg[0:0] A24plus_7_address0;
reg A24plus_7_ce0;
reg A24plus_7_we0;
reg[63:0] A24plus_7_d0;

(* fsm_encoding = "none" *) reg   [29:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] t2_reg_189;
wire    ap_CS_fsm_state24;
reg   [63:0] t2_1_reg_194;
reg   [63:0] t2_2_reg_199;
reg   [63:0] t2_3_reg_204;
reg   [63:0] t2_4_reg_209;
reg   [63:0] t2_5_reg_214;
reg   [63:0] t2_6_reg_219;
reg   [63:0] t2_7_reg_224;
reg   [3:0] temp_address0;
reg    temp_ce0;
reg    temp_we0;
reg   [63:0] temp_d0;
wire   [63:0] temp_q0;
reg   [3:0] temp_8_address0;
reg    temp_8_ce0;
reg    temp_8_we0;
reg   [63:0] temp_8_d0;
wire   [63:0] temp_8_q0;
reg   [2:0] t1_address0;
reg    t1_ce0;
reg    t1_we0;
wire   [63:0] t1_q0;
reg   [2:0] t3_address0;
reg    t3_ce0;
reg    t3_we0;
wire   [63:0] t3_q0;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_done;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_idle;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_ready;
wire   [3:0] grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_address0;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_ce0;
wire   [3:0] grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_address1;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_ce1;
wire   [2:0] grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_address0;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_ce0;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_we0;
wire   [63:0] grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_d0;
wire    grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start;
wire    grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_done;
wire    grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_idle;
wire    grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_ready;
wire   [3:0] grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_address0;
wire    grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_ce0;
wire    grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_we0;
wire   [63:0] grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_d0;
wire    grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start;
wire    grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_done;
wire    grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_idle;
wire    grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_ready;
wire   [3:0] grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_address0;
wire    grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_ce0;
wire    grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_we0;
wire   [63:0] grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_d0;
wire    grp_fpsub503_95_fu_76_ap_start;
wire    grp_fpsub503_95_fu_76_ap_done;
wire    grp_fpsub503_95_fu_76_ap_idle;
wire    grp_fpsub503_95_fu_76_ap_ready;
wire   [3:0] grp_fpsub503_95_fu_76_R_X_address0;
wire    grp_fpsub503_95_fu_76_R_X_ce0;
wire   [3:0] grp_fpsub503_95_fu_76_R_X_address1;
wire    grp_fpsub503_95_fu_76_R_X_ce1;
wire   [63:0] grp_fpsub503_95_fu_76_ap_return_0;
wire   [63:0] grp_fpsub503_95_fu_76_ap_return_1;
wire   [63:0] grp_fpsub503_95_fu_76_ap_return_2;
wire   [63:0] grp_fpsub503_95_fu_76_ap_return_3;
wire   [63:0] grp_fpsub503_95_fu_76_ap_return_4;
wire   [63:0] grp_fpsub503_95_fu_76_ap_return_5;
wire   [63:0] grp_fpsub503_95_fu_76_ap_return_6;
wire   [63:0] grp_fpsub503_95_fu_76_ap_return_7;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_done;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_idle;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_ready;
wire   [3:0] grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_R_X_address0;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_R_X_ce0;
wire   [2:0] grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_address0;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_ce0;
wire    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_we0;
wire   [63:0] grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_d0;
wire    grp_mp_mul_3_fu_89_ap_start;
wire    grp_mp_mul_3_fu_89_ap_done;
wire    grp_mp_mul_3_fu_89_ap_idle;
wire    grp_mp_mul_3_fu_89_ap_ready;
wire   [2:0] grp_mp_mul_3_fu_89_a_address0;
wire    grp_mp_mul_3_fu_89_a_ce0;
wire   [3:0] grp_mp_mul_3_fu_89_c_address0;
wire    grp_mp_mul_3_fu_89_c_ce0;
wire    grp_mp_mul_3_fu_89_c_we0;
wire   [63:0] grp_mp_mul_3_fu_89_c_d0;
wire    grp_rdc_mont_86220_fu_103_ap_start;
wire    grp_rdc_mont_86220_fu_103_ap_done;
wire    grp_rdc_mont_86220_fu_103_ap_idle;
wire    grp_rdc_mont_86220_fu_103_ap_ready;
wire   [3:0] grp_rdc_mont_86220_fu_103_ma_address0;
wire    grp_rdc_mont_86220_fu_103_ma_ce0;
wire   [0:0] grp_rdc_mont_86220_fu_103_t1_i_0_address0;
wire    grp_rdc_mont_86220_fu_103_t1_i_0_ce0;
wire    grp_rdc_mont_86220_fu_103_t1_i_0_we0;
wire   [63:0] grp_rdc_mont_86220_fu_103_t1_i_0_d0;
wire   [0:0] grp_rdc_mont_86220_fu_103_t1_i_1_address0;
wire    grp_rdc_mont_86220_fu_103_t1_i_1_ce0;
wire    grp_rdc_mont_86220_fu_103_t1_i_1_we0;
wire   [63:0] grp_rdc_mont_86220_fu_103_t1_i_1_d0;
wire   [0:0] grp_rdc_mont_86220_fu_103_t1_i_2_address0;
wire    grp_rdc_mont_86220_fu_103_t1_i_2_ce0;
wire    grp_rdc_mont_86220_fu_103_t1_i_2_we0;
wire   [63:0] grp_rdc_mont_86220_fu_103_t1_i_2_d0;
wire   [0:0] grp_rdc_mont_86220_fu_103_t1_i_3_address0;
wire    grp_rdc_mont_86220_fu_103_t1_i_3_ce0;
wire    grp_rdc_mont_86220_fu_103_t1_i_3_we0;
wire   [63:0] grp_rdc_mont_86220_fu_103_t1_i_3_d0;
wire   [0:0] grp_rdc_mont_86220_fu_103_t1_i_4_address0;
wire    grp_rdc_mont_86220_fu_103_t1_i_4_ce0;
wire    grp_rdc_mont_86220_fu_103_t1_i_4_we0;
wire   [63:0] grp_rdc_mont_86220_fu_103_t1_i_4_d0;
wire   [0:0] grp_rdc_mont_86220_fu_103_t1_i_5_address0;
wire    grp_rdc_mont_86220_fu_103_t1_i_5_ce0;
wire    grp_rdc_mont_86220_fu_103_t1_i_5_we0;
wire   [63:0] grp_rdc_mont_86220_fu_103_t1_i_5_d0;
wire   [0:0] grp_rdc_mont_86220_fu_103_t1_i_6_address0;
wire    grp_rdc_mont_86220_fu_103_t1_i_6_ce0;
wire    grp_rdc_mont_86220_fu_103_t1_i_6_we0;
wire   [63:0] grp_rdc_mont_86220_fu_103_t1_i_6_d0;
wire   [0:0] grp_rdc_mont_86220_fu_103_t1_i_7_address0;
wire    grp_rdc_mont_86220_fu_103_t1_i_7_ce0;
wire    grp_rdc_mont_86220_fu_103_t1_i_7_we0;
wire   [63:0] grp_rdc_mont_86220_fu_103_t1_i_7_d0;
wire    grp_mp_mul_97_fu_126_ap_start;
wire    grp_mp_mul_97_fu_126_ap_done;
wire    grp_mp_mul_97_fu_126_ap_idle;
wire    grp_mp_mul_97_fu_126_ap_ready;
wire   [2:0] grp_mp_mul_97_fu_126_a_address0;
wire    grp_mp_mul_97_fu_126_a_ce0;
wire   [3:0] grp_mp_mul_97_fu_126_R_X_address0;
wire    grp_mp_mul_97_fu_126_R_X_ce0;
wire   [3:0] grp_mp_mul_97_fu_126_c_address0;
wire    grp_mp_mul_97_fu_126_c_ce0;
wire    grp_mp_mul_97_fu_126_c_we0;
wire   [63:0] grp_mp_mul_97_fu_126_c_d0;
wire    grp_rdc_mont_88_fu_134_ap_start;
wire    grp_rdc_mont_88_fu_134_ap_done;
wire    grp_rdc_mont_88_fu_134_ap_idle;
wire    grp_rdc_mont_88_fu_134_ap_ready;
wire   [3:0] grp_rdc_mont_88_fu_134_ma_address0;
wire    grp_rdc_mont_88_fu_134_ma_ce0;
wire   [0:0] grp_rdc_mont_88_fu_134_t1_i_0_address0;
wire    grp_rdc_mont_88_fu_134_t1_i_0_ce0;
wire    grp_rdc_mont_88_fu_134_t1_i_0_we0;
wire   [63:0] grp_rdc_mont_88_fu_134_t1_i_0_d0;
wire   [0:0] grp_rdc_mont_88_fu_134_t1_i_1_address0;
wire    grp_rdc_mont_88_fu_134_t1_i_1_ce0;
wire    grp_rdc_mont_88_fu_134_t1_i_1_we0;
wire   [63:0] grp_rdc_mont_88_fu_134_t1_i_1_d0;
wire   [0:0] grp_rdc_mont_88_fu_134_t1_i_2_address0;
wire    grp_rdc_mont_88_fu_134_t1_i_2_ce0;
wire    grp_rdc_mont_88_fu_134_t1_i_2_we0;
wire   [63:0] grp_rdc_mont_88_fu_134_t1_i_2_d0;
wire   [0:0] grp_rdc_mont_88_fu_134_t1_i_3_address0;
wire    grp_rdc_mont_88_fu_134_t1_i_3_ce0;
wire    grp_rdc_mont_88_fu_134_t1_i_3_we0;
wire   [63:0] grp_rdc_mont_88_fu_134_t1_i_3_d0;
wire   [0:0] grp_rdc_mont_88_fu_134_t1_i_4_address0;
wire    grp_rdc_mont_88_fu_134_t1_i_4_ce0;
wire    grp_rdc_mont_88_fu_134_t1_i_4_we0;
wire   [63:0] grp_rdc_mont_88_fu_134_t1_i_4_d0;
wire   [0:0] grp_rdc_mont_88_fu_134_t1_i_5_address0;
wire    grp_rdc_mont_88_fu_134_t1_i_5_ce0;
wire    grp_rdc_mont_88_fu_134_t1_i_5_we0;
wire   [63:0] grp_rdc_mont_88_fu_134_t1_i_5_d0;
wire   [0:0] grp_rdc_mont_88_fu_134_t1_i_6_address0;
wire    grp_rdc_mont_88_fu_134_t1_i_6_ce0;
wire    grp_rdc_mont_88_fu_134_t1_i_6_we0;
wire   [63:0] grp_rdc_mont_88_fu_134_t1_i_6_d0;
wire   [0:0] grp_rdc_mont_88_fu_134_t1_i_7_address0;
wire    grp_rdc_mont_88_fu_134_t1_i_7_ce0;
wire    grp_rdc_mont_88_fu_134_t1_i_7_we0;
wire   [63:0] grp_rdc_mont_88_fu_134_t1_i_7_d0;
reg    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start_reg;
reg    grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start_reg;
reg    grp_fpsub503_95_fu_76_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [29:0] ap_NS_fsm;
wire    ap_NS_fsm_state9;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg    grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start_reg;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
reg    grp_mp_mul_3_fu_89_ap_start_reg;
reg    grp_rdc_mont_86220_fu_103_ap_start_reg;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
reg    grp_mp_mul_97_fu_126_ap_start_reg;
reg    grp_rdc_mont_88_fu_134_ap_start_reg;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_block_state26_on_subcall_done;
reg    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
reg    ap_block_state28_on_subcall_done;
reg    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 30'd1;
#0 grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start_reg = 1'b0;
#0 grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start_reg = 1'b0;
#0 grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start_reg = 1'b0;
#0 grp_fpsub503_95_fu_76_ap_start_reg = 1'b0;
#0 grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start_reg = 1'b0;
#0 grp_mp_mul_3_fu_89_ap_start_reg = 1'b0;
#0 grp_rdc_mont_86220_fu_103_ap_start_reg = 1'b0;
#0 grp_mp_mul_97_fu_126_ap_start_reg = 1'b0;
#0 grp_rdc_mont_88_fu_134_ap_start_reg = 1'b0;
end

sikep503_kem_enc_hw_fp2sqr503_mont_40_temp_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
temp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_address0),
    .ce0(temp_ce0),
    .we0(temp_we0),
    .d0(temp_d0),
    .q0(temp_q0)
);

sikep503_kem_enc_hw_fp2sqr503_mont_40_temp_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
temp_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_8_address0),
    .ce0(temp_8_ce0),
    .we0(temp_8_we0),
    .d0(temp_8_d0),
    .q0(temp_8_q0)
);

sikep503_kem_enc_hw_fp2sqr503_mont_40_t1_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
t1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(t1_address0),
    .ce0(t1_ce0),
    .we0(t1_we0),
    .d0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_d0),
    .q0(t1_q0)
);

sikep503_kem_enc_hw_fp2sqr503_mont_40_t1_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
t3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(t3_address0),
    .ce0(t3_ce0),
    .we0(t3_we0),
    .d0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_d0),
    .q0(t3_q0)
);

sikep503_kem_enc_hw_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1 grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start),
    .ap_done(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_done),
    .ap_idle(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_idle),
    .ap_ready(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_ready),
    .R_X_address0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_address0),
    .R_X_ce0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_ce0),
    .R_X_q0(R_X_q0),
    .R_X_address1(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_address1),
    .R_X_ce1(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_ce1),
    .R_X_q1(R_X_q1),
    .t1_address0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_address0),
    .t1_ce0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_ce0),
    .t1_we0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_we0),
    .t1_d0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_d0)
);

sikep503_kem_enc_hw_fp2sqr503_mont_40_Pipeline_3 grp_fp2sqr503_mont_40_Pipeline_3_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start),
    .ap_done(grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_done),
    .ap_idle(grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_idle),
    .ap_ready(grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_ready),
    .temp_8_address0(grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_address0),
    .temp_8_ce0(grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_ce0),
    .temp_8_we0(grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_we0),
    .temp_8_d0(grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_d0)
);

sikep503_kem_enc_hw_fp2sqr503_mont_40_Pipeline_4 grp_fp2sqr503_mont_40_Pipeline_4_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start),
    .ap_done(grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_done),
    .ap_idle(grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_idle),
    .ap_ready(grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_ready),
    .temp_address0(grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_address0),
    .temp_ce0(grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_ce0),
    .temp_we0(grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_we0),
    .temp_d0(grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_d0)
);

sikep503_kem_enc_hw_fpsub503_95 grp_fpsub503_95_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fpsub503_95_fu_76_ap_start),
    .ap_done(grp_fpsub503_95_fu_76_ap_done),
    .ap_idle(grp_fpsub503_95_fu_76_ap_idle),
    .ap_ready(grp_fpsub503_95_fu_76_ap_ready),
    .R_X_address0(grp_fpsub503_95_fu_76_R_X_address0),
    .R_X_ce0(grp_fpsub503_95_fu_76_R_X_ce0),
    .R_X_q0(R_X_q0),
    .R_X_address1(grp_fpsub503_95_fu_76_R_X_address1),
    .R_X_ce1(grp_fpsub503_95_fu_76_R_X_ce1),
    .R_X_q1(R_X_q1),
    .ap_return_0(grp_fpsub503_95_fu_76_ap_return_0),
    .ap_return_1(grp_fpsub503_95_fu_76_ap_return_1),
    .ap_return_2(grp_fpsub503_95_fu_76_ap_return_2),
    .ap_return_3(grp_fpsub503_95_fu_76_ap_return_3),
    .ap_return_4(grp_fpsub503_95_fu_76_ap_return_4),
    .ap_return_5(grp_fpsub503_95_fu_76_ap_return_5),
    .ap_return_6(grp_fpsub503_95_fu_76_ap_return_6),
    .ap_return_7(grp_fpsub503_95_fu_76_ap_return_7)
);

sikep503_kem_enc_hw_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157 grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start),
    .ap_done(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_done),
    .ap_idle(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_idle),
    .ap_ready(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_ready),
    .R_X_address0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_R_X_address0),
    .R_X_ce0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_R_X_ce0),
    .R_X_q0(R_X_q0),
    .t3_address0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_address0),
    .t3_ce0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_ce0),
    .t3_we0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_we0),
    .t3_d0(grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_d0)
);

sikep503_kem_enc_hw_mp_mul_3 grp_mp_mul_3_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mp_mul_3_fu_89_ap_start),
    .ap_done(grp_mp_mul_3_fu_89_ap_done),
    .ap_idle(grp_mp_mul_3_fu_89_ap_idle),
    .ap_ready(grp_mp_mul_3_fu_89_ap_ready),
    .a_address0(grp_mp_mul_3_fu_89_a_address0),
    .a_ce0(grp_mp_mul_3_fu_89_a_ce0),
    .a_q0(t1_q0),
    .b_read(t2_reg_189),
    .b_read_70(t2_1_reg_194),
    .b_read_71(t2_2_reg_199),
    .b_read_72(t2_3_reg_204),
    .b_read_73(t2_4_reg_209),
    .b_read_74(t2_5_reg_214),
    .b_read_75(t2_6_reg_219),
    .b_read_76(t2_7_reg_224),
    .c_address0(grp_mp_mul_3_fu_89_c_address0),
    .c_ce0(grp_mp_mul_3_fu_89_c_ce0),
    .c_we0(grp_mp_mul_3_fu_89_c_we0),
    .c_d0(grp_mp_mul_3_fu_89_c_d0)
);

sikep503_kem_enc_hw_rdc_mont_86220 grp_rdc_mont_86220_fu_103(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rdc_mont_86220_fu_103_ap_start),
    .ap_done(grp_rdc_mont_86220_fu_103_ap_done),
    .ap_idle(grp_rdc_mont_86220_fu_103_ap_idle),
    .ap_ready(grp_rdc_mont_86220_fu_103_ap_ready),
    .ma_address0(grp_rdc_mont_86220_fu_103_ma_address0),
    .ma_ce0(grp_rdc_mont_86220_fu_103_ma_ce0),
    .ma_q0(temp_8_q0),
    .t1_i_0_address0(grp_rdc_mont_86220_fu_103_t1_i_0_address0),
    .t1_i_0_ce0(grp_rdc_mont_86220_fu_103_t1_i_0_ce0),
    .t1_i_0_we0(grp_rdc_mont_86220_fu_103_t1_i_0_we0),
    .t1_i_0_d0(grp_rdc_mont_86220_fu_103_t1_i_0_d0),
    .t1_i_0_q0(A24plus_0_q0),
    .t1_i_1_address0(grp_rdc_mont_86220_fu_103_t1_i_1_address0),
    .t1_i_1_ce0(grp_rdc_mont_86220_fu_103_t1_i_1_ce0),
    .t1_i_1_we0(grp_rdc_mont_86220_fu_103_t1_i_1_we0),
    .t1_i_1_d0(grp_rdc_mont_86220_fu_103_t1_i_1_d0),
    .t1_i_1_q0(A24plus_1_q0),
    .t1_i_2_address0(grp_rdc_mont_86220_fu_103_t1_i_2_address0),
    .t1_i_2_ce0(grp_rdc_mont_86220_fu_103_t1_i_2_ce0),
    .t1_i_2_we0(grp_rdc_mont_86220_fu_103_t1_i_2_we0),
    .t1_i_2_d0(grp_rdc_mont_86220_fu_103_t1_i_2_d0),
    .t1_i_2_q0(A24plus_2_q0),
    .t1_i_3_address0(grp_rdc_mont_86220_fu_103_t1_i_3_address0),
    .t1_i_3_ce0(grp_rdc_mont_86220_fu_103_t1_i_3_ce0),
    .t1_i_3_we0(grp_rdc_mont_86220_fu_103_t1_i_3_we0),
    .t1_i_3_d0(grp_rdc_mont_86220_fu_103_t1_i_3_d0),
    .t1_i_3_q0(A24plus_3_q0),
    .t1_i_4_address0(grp_rdc_mont_86220_fu_103_t1_i_4_address0),
    .t1_i_4_ce0(grp_rdc_mont_86220_fu_103_t1_i_4_ce0),
    .t1_i_4_we0(grp_rdc_mont_86220_fu_103_t1_i_4_we0),
    .t1_i_4_d0(grp_rdc_mont_86220_fu_103_t1_i_4_d0),
    .t1_i_4_q0(A24plus_4_q0),
    .t1_i_5_address0(grp_rdc_mont_86220_fu_103_t1_i_5_address0),
    .t1_i_5_ce0(grp_rdc_mont_86220_fu_103_t1_i_5_ce0),
    .t1_i_5_we0(grp_rdc_mont_86220_fu_103_t1_i_5_we0),
    .t1_i_5_d0(grp_rdc_mont_86220_fu_103_t1_i_5_d0),
    .t1_i_5_q0(A24plus_5_q0),
    .t1_i_6_address0(grp_rdc_mont_86220_fu_103_t1_i_6_address0),
    .t1_i_6_ce0(grp_rdc_mont_86220_fu_103_t1_i_6_ce0),
    .t1_i_6_we0(grp_rdc_mont_86220_fu_103_t1_i_6_we0),
    .t1_i_6_d0(grp_rdc_mont_86220_fu_103_t1_i_6_d0),
    .t1_i_6_q0(A24plus_6_q0),
    .t1_i_7_address0(grp_rdc_mont_86220_fu_103_t1_i_7_address0),
    .t1_i_7_ce0(grp_rdc_mont_86220_fu_103_t1_i_7_ce0),
    .t1_i_7_we0(grp_rdc_mont_86220_fu_103_t1_i_7_we0),
    .t1_i_7_d0(grp_rdc_mont_86220_fu_103_t1_i_7_d0),
    .t1_i_7_q0(A24plus_7_q0)
);

sikep503_kem_enc_hw_mp_mul_97 grp_mp_mul_97_fu_126(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mp_mul_97_fu_126_ap_start),
    .ap_done(grp_mp_mul_97_fu_126_ap_done),
    .ap_idle(grp_mp_mul_97_fu_126_ap_idle),
    .ap_ready(grp_mp_mul_97_fu_126_ap_ready),
    .a_address0(grp_mp_mul_97_fu_126_a_address0),
    .a_ce0(grp_mp_mul_97_fu_126_a_ce0),
    .a_q0(t3_q0),
    .R_X_address0(grp_mp_mul_97_fu_126_R_X_address0),
    .R_X_ce0(grp_mp_mul_97_fu_126_R_X_ce0),
    .R_X_q0(R_X_q0),
    .c_address0(grp_mp_mul_97_fu_126_c_address0),
    .c_ce0(grp_mp_mul_97_fu_126_c_ce0),
    .c_we0(grp_mp_mul_97_fu_126_c_we0),
    .c_d0(grp_mp_mul_97_fu_126_c_d0)
);

sikep503_kem_enc_hw_rdc_mont_88 grp_rdc_mont_88_fu_134(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rdc_mont_88_fu_134_ap_start),
    .ap_done(grp_rdc_mont_88_fu_134_ap_done),
    .ap_idle(grp_rdc_mont_88_fu_134_ap_idle),
    .ap_ready(grp_rdc_mont_88_fu_134_ap_ready),
    .ma_address0(grp_rdc_mont_88_fu_134_ma_address0),
    .ma_ce0(grp_rdc_mont_88_fu_134_ma_ce0),
    .ma_q0(temp_q0),
    .t1_i_0_address0(grp_rdc_mont_88_fu_134_t1_i_0_address0),
    .t1_i_0_ce0(grp_rdc_mont_88_fu_134_t1_i_0_ce0),
    .t1_i_0_we0(grp_rdc_mont_88_fu_134_t1_i_0_we0),
    .t1_i_0_d0(grp_rdc_mont_88_fu_134_t1_i_0_d0),
    .t1_i_0_q0(A24plus_0_q0),
    .t1_i_1_address0(grp_rdc_mont_88_fu_134_t1_i_1_address0),
    .t1_i_1_ce0(grp_rdc_mont_88_fu_134_t1_i_1_ce0),
    .t1_i_1_we0(grp_rdc_mont_88_fu_134_t1_i_1_we0),
    .t1_i_1_d0(grp_rdc_mont_88_fu_134_t1_i_1_d0),
    .t1_i_1_q0(A24plus_1_q0),
    .t1_i_2_address0(grp_rdc_mont_88_fu_134_t1_i_2_address0),
    .t1_i_2_ce0(grp_rdc_mont_88_fu_134_t1_i_2_ce0),
    .t1_i_2_we0(grp_rdc_mont_88_fu_134_t1_i_2_we0),
    .t1_i_2_d0(grp_rdc_mont_88_fu_134_t1_i_2_d0),
    .t1_i_2_q0(A24plus_2_q0),
    .t1_i_3_address0(grp_rdc_mont_88_fu_134_t1_i_3_address0),
    .t1_i_3_ce0(grp_rdc_mont_88_fu_134_t1_i_3_ce0),
    .t1_i_3_we0(grp_rdc_mont_88_fu_134_t1_i_3_we0),
    .t1_i_3_d0(grp_rdc_mont_88_fu_134_t1_i_3_d0),
    .t1_i_3_q0(A24plus_3_q0),
    .t1_i_4_address0(grp_rdc_mont_88_fu_134_t1_i_4_address0),
    .t1_i_4_ce0(grp_rdc_mont_88_fu_134_t1_i_4_ce0),
    .t1_i_4_we0(grp_rdc_mont_88_fu_134_t1_i_4_we0),
    .t1_i_4_d0(grp_rdc_mont_88_fu_134_t1_i_4_d0),
    .t1_i_4_q0(A24plus_4_q0),
    .t1_i_5_address0(grp_rdc_mont_88_fu_134_t1_i_5_address0),
    .t1_i_5_ce0(grp_rdc_mont_88_fu_134_t1_i_5_ce0),
    .t1_i_5_we0(grp_rdc_mont_88_fu_134_t1_i_5_we0),
    .t1_i_5_d0(grp_rdc_mont_88_fu_134_t1_i_5_d0),
    .t1_i_5_q0(A24plus_5_q0),
    .t1_i_6_address0(grp_rdc_mont_88_fu_134_t1_i_6_address0),
    .t1_i_6_ce0(grp_rdc_mont_88_fu_134_t1_i_6_ce0),
    .t1_i_6_we0(grp_rdc_mont_88_fu_134_t1_i_6_we0),
    .t1_i_6_d0(grp_rdc_mont_88_fu_134_t1_i_6_d0),
    .t1_i_6_q0(A24plus_6_q0),
    .t1_i_7_address0(grp_rdc_mont_88_fu_134_t1_i_7_address0),
    .t1_i_7_ce0(grp_rdc_mont_88_fu_134_t1_i_7_ce0),
    .t1_i_7_we0(grp_rdc_mont_88_fu_134_t1_i_7_we0),
    .t1_i_7_d0(grp_rdc_mont_88_fu_134_t1_i_7_d0),
    .t1_i_7_q0(A24plus_7_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_ready == 1'b1)) begin
            grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_ready == 1'b1)) begin
            grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_ready == 1'b1)) begin
            grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_ready == 1'b1)) begin
            grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fpsub503_95_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state9) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_fpsub503_95_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_fpsub503_95_fu_76_ap_ready == 1'b1)) begin
            grp_fpsub503_95_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mp_mul_3_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            grp_mp_mul_3_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_mp_mul_3_fu_89_ap_ready == 1'b1)) begin
            grp_mp_mul_3_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mp_mul_97_fu_126_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state27)) begin
            grp_mp_mul_97_fu_126_ap_start_reg <= 1'b1;
        end else if ((grp_mp_mul_97_fu_126_ap_ready == 1'b1)) begin
            grp_mp_mul_97_fu_126_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rdc_mont_86220_fu_103_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state27)) begin
            grp_rdc_mont_86220_fu_103_ap_start_reg <= 1'b1;
        end else if ((grp_rdc_mont_86220_fu_103_ap_ready == 1'b1)) begin
            grp_rdc_mont_86220_fu_103_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rdc_mont_88_fu_134_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state29)) begin
            grp_rdc_mont_88_fu_134_ap_start_reg <= 1'b1;
        end else if ((grp_rdc_mont_88_fu_134_ap_ready == 1'b1)) begin
            grp_rdc_mont_88_fu_134_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        t2_1_reg_194 <= grp_fpsub503_95_fu_76_ap_return_1;
        t2_2_reg_199 <= grp_fpsub503_95_fu_76_ap_return_2;
        t2_3_reg_204 <= grp_fpsub503_95_fu_76_ap_return_3;
        t2_4_reg_209 <= grp_fpsub503_95_fu_76_ap_return_4;
        t2_5_reg_214 <= grp_fpsub503_95_fu_76_ap_return_5;
        t2_6_reg_219 <= grp_fpsub503_95_fu_76_ap_return_6;
        t2_7_reg_224 <= grp_fpsub503_95_fu_76_ap_return_7;
        t2_reg_189 <= grp_fpsub503_95_fu_76_ap_return_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_0_address0 = grp_rdc_mont_88_fu_134_t1_i_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_0_address0 = grp_rdc_mont_86220_fu_103_t1_i_0_address0;
    end else begin
        A24plus_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_0_ce0 = grp_rdc_mont_88_fu_134_t1_i_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_0_ce0 = grp_rdc_mont_86220_fu_103_t1_i_0_ce0;
    end else begin
        A24plus_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_0_d0 = grp_rdc_mont_88_fu_134_t1_i_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_0_d0 = grp_rdc_mont_86220_fu_103_t1_i_0_d0;
    end else begin
        A24plus_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_0_we0 = grp_rdc_mont_88_fu_134_t1_i_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_0_we0 = grp_rdc_mont_86220_fu_103_t1_i_0_we0;
    end else begin
        A24plus_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_1_address0 = grp_rdc_mont_88_fu_134_t1_i_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_1_address0 = grp_rdc_mont_86220_fu_103_t1_i_1_address0;
    end else begin
        A24plus_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_1_ce0 = grp_rdc_mont_88_fu_134_t1_i_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_1_ce0 = grp_rdc_mont_86220_fu_103_t1_i_1_ce0;
    end else begin
        A24plus_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_1_d0 = grp_rdc_mont_88_fu_134_t1_i_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_1_d0 = grp_rdc_mont_86220_fu_103_t1_i_1_d0;
    end else begin
        A24plus_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_1_we0 = grp_rdc_mont_88_fu_134_t1_i_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_1_we0 = grp_rdc_mont_86220_fu_103_t1_i_1_we0;
    end else begin
        A24plus_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_2_address0 = grp_rdc_mont_88_fu_134_t1_i_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_2_address0 = grp_rdc_mont_86220_fu_103_t1_i_2_address0;
    end else begin
        A24plus_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_2_ce0 = grp_rdc_mont_88_fu_134_t1_i_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_2_ce0 = grp_rdc_mont_86220_fu_103_t1_i_2_ce0;
    end else begin
        A24plus_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_2_d0 = grp_rdc_mont_88_fu_134_t1_i_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_2_d0 = grp_rdc_mont_86220_fu_103_t1_i_2_d0;
    end else begin
        A24plus_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_2_we0 = grp_rdc_mont_88_fu_134_t1_i_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_2_we0 = grp_rdc_mont_86220_fu_103_t1_i_2_we0;
    end else begin
        A24plus_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_3_address0 = grp_rdc_mont_88_fu_134_t1_i_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_3_address0 = grp_rdc_mont_86220_fu_103_t1_i_3_address0;
    end else begin
        A24plus_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_3_ce0 = grp_rdc_mont_88_fu_134_t1_i_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_3_ce0 = grp_rdc_mont_86220_fu_103_t1_i_3_ce0;
    end else begin
        A24plus_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_3_d0 = grp_rdc_mont_88_fu_134_t1_i_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_3_d0 = grp_rdc_mont_86220_fu_103_t1_i_3_d0;
    end else begin
        A24plus_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_3_we0 = grp_rdc_mont_88_fu_134_t1_i_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_3_we0 = grp_rdc_mont_86220_fu_103_t1_i_3_we0;
    end else begin
        A24plus_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_4_address0 = grp_rdc_mont_88_fu_134_t1_i_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_4_address0 = grp_rdc_mont_86220_fu_103_t1_i_4_address0;
    end else begin
        A24plus_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_4_ce0 = grp_rdc_mont_88_fu_134_t1_i_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_4_ce0 = grp_rdc_mont_86220_fu_103_t1_i_4_ce0;
    end else begin
        A24plus_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_4_d0 = grp_rdc_mont_88_fu_134_t1_i_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_4_d0 = grp_rdc_mont_86220_fu_103_t1_i_4_d0;
    end else begin
        A24plus_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_4_we0 = grp_rdc_mont_88_fu_134_t1_i_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_4_we0 = grp_rdc_mont_86220_fu_103_t1_i_4_we0;
    end else begin
        A24plus_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_5_address0 = grp_rdc_mont_88_fu_134_t1_i_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_5_address0 = grp_rdc_mont_86220_fu_103_t1_i_5_address0;
    end else begin
        A24plus_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_5_ce0 = grp_rdc_mont_88_fu_134_t1_i_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_5_ce0 = grp_rdc_mont_86220_fu_103_t1_i_5_ce0;
    end else begin
        A24plus_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_5_d0 = grp_rdc_mont_88_fu_134_t1_i_5_d0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_5_d0 = grp_rdc_mont_86220_fu_103_t1_i_5_d0;
    end else begin
        A24plus_5_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_5_we0 = grp_rdc_mont_88_fu_134_t1_i_5_we0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_5_we0 = grp_rdc_mont_86220_fu_103_t1_i_5_we0;
    end else begin
        A24plus_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_6_address0 = grp_rdc_mont_88_fu_134_t1_i_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_6_address0 = grp_rdc_mont_86220_fu_103_t1_i_6_address0;
    end else begin
        A24plus_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_6_ce0 = grp_rdc_mont_88_fu_134_t1_i_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_6_ce0 = grp_rdc_mont_86220_fu_103_t1_i_6_ce0;
    end else begin
        A24plus_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_6_d0 = grp_rdc_mont_88_fu_134_t1_i_6_d0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_6_d0 = grp_rdc_mont_86220_fu_103_t1_i_6_d0;
    end else begin
        A24plus_6_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_6_we0 = grp_rdc_mont_88_fu_134_t1_i_6_we0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_6_we0 = grp_rdc_mont_86220_fu_103_t1_i_6_we0;
    end else begin
        A24plus_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_7_address0 = grp_rdc_mont_88_fu_134_t1_i_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_7_address0 = grp_rdc_mont_86220_fu_103_t1_i_7_address0;
    end else begin
        A24plus_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_7_ce0 = grp_rdc_mont_88_fu_134_t1_i_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_7_ce0 = grp_rdc_mont_86220_fu_103_t1_i_7_ce0;
    end else begin
        A24plus_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_7_d0 = grp_rdc_mont_88_fu_134_t1_i_7_d0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_7_d0 = grp_rdc_mont_86220_fu_103_t1_i_7_d0;
    end else begin
        A24plus_7_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        A24plus_7_we0 = grp_rdc_mont_88_fu_134_t1_i_7_we0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        A24plus_7_we0 = grp_rdc_mont_86220_fu_103_t1_i_7_we0;
    end else begin
        A24plus_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        R_X_address0 = grp_mp_mul_97_fu_126_R_X_address0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        R_X_address0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_R_X_address0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        R_X_address0 = grp_fpsub503_95_fu_76_R_X_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        R_X_address0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_address0;
    end else begin
        R_X_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        R_X_address1 = grp_fpsub503_95_fu_76_R_X_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        R_X_address1 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_address1;
    end else begin
        R_X_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        R_X_ce0 = grp_mp_mul_97_fu_126_R_X_ce0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        R_X_ce0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_R_X_ce0;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        R_X_ce0 = grp_fpsub503_95_fu_76_R_X_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        R_X_ce0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_ce0;
    end else begin
        R_X_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        R_X_ce1 = grp_fpsub503_95_fu_76_R_X_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        R_X_ce1 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_R_X_ce1;
    end else begin
        R_X_ce1 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state26_on_subcall_done)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state28_on_subcall_done)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_rdc_mont_88_fu_134_ap_done == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_rdc_mont_88_fu_134_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_rdc_mont_88_fu_134_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        t1_address0 = grp_mp_mul_3_fu_89_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        t1_address0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_address0;
    end else begin
        t1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        t1_ce0 = grp_mp_mul_3_fu_89_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        t1_ce0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_ce0;
    end else begin
        t1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        t1_we0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_t1_we0;
    end else begin
        t1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        t3_address0 = grp_mp_mul_97_fu_126_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        t3_address0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_address0;
    end else begin
        t3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        t3_ce0 = grp_mp_mul_97_fu_126_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        t3_ce0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_ce0;
    end else begin
        t3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        t3_we0 = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_t3_we0;
    end else begin
        t3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        temp_8_address0 = grp_rdc_mont_86220_fu_103_ma_address0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        temp_8_address0 = grp_mp_mul_3_fu_89_c_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_8_address0 = grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_address0;
    end else begin
        temp_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        temp_8_ce0 = grp_rdc_mont_86220_fu_103_ma_ce0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        temp_8_ce0 = grp_mp_mul_3_fu_89_c_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_8_ce0 = grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_ce0;
    end else begin
        temp_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        temp_8_d0 = grp_mp_mul_3_fu_89_c_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_8_d0 = grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_d0;
    end else begin
        temp_8_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        temp_8_we0 = grp_mp_mul_3_fu_89_c_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_8_we0 = grp_fp2sqr503_mont_40_Pipeline_3_fu_64_temp_8_we0;
    end else begin
        temp_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        temp_address0 = grp_rdc_mont_88_fu_134_ma_address0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        temp_address0 = grp_mp_mul_97_fu_126_c_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_address0 = grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_address0;
    end else begin
        temp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        temp_ce0 = grp_rdc_mont_88_fu_134_ma_ce0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        temp_ce0 = grp_mp_mul_97_fu_126_c_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_ce0 = grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_ce0;
    end else begin
        temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        temp_d0 = grp_mp_mul_97_fu_126_c_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_d0 = grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_d0;
    end else begin
        temp_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        temp_we0 = grp_mp_mul_97_fu_126_c_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp_we0 = grp_fp2sqr503_mont_40_Pipeline_4_fu_70_temp_we0;
    end else begin
        temp_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((1'b0 == ap_block_state26_on_subcall_done) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((1'b0 == ap_block_state28_on_subcall_done) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((grp_rdc_mont_88_fu_134_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state9 = ap_NS_fsm[32'd8];

always @ (*) begin
    ap_block_state26_on_subcall_done = ((grp_mp_mul_3_fu_89_ap_done == 1'b0) | (grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state28_on_subcall_done = ((grp_mp_mul_97_fu_126_ap_done == 1'b0) | (grp_rdc_mont_86220_fu_103_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_done == 1'b0) | (grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_done == 1'b0) | (grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_done == 1'b0));
end

assign grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start = grp_fp2sqr503_mont_40_Pipeline_3_fu_64_ap_start_reg;

assign grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start = grp_fp2sqr503_mont_40_Pipeline_4_fu_70_ap_start_reg;

assign grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_157_fu_82_ap_start_reg;

assign grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start = grp_fp2sqr503_mont_40_Pipeline_VITIS_LOOP_370_1_fu_56_ap_start_reg;

assign grp_fpsub503_95_fu_76_ap_start = grp_fpsub503_95_fu_76_ap_start_reg;

assign grp_mp_mul_3_fu_89_ap_start = grp_mp_mul_3_fu_89_ap_start_reg;

assign grp_mp_mul_97_fu_126_ap_start = grp_mp_mul_97_fu_126_ap_start_reg;

assign grp_rdc_mont_86220_fu_103_ap_start = grp_rdc_mont_86220_fu_103_ap_start_reg;

assign grp_rdc_mont_88_fu_134_ap_start = grp_rdc_mont_88_fu_134_ap_start_reg;

endmodule //sikep503_kem_enc_hw_fp2sqr503_mont_40
