#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("a_0", 64, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("a_1", 64, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("a_2", 64, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("a_3", 64, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("b_0", 64, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("b_1", 64, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("b_2", 64, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("b_3", 64, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("c_0", 64, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("c_0_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("c_1", 64, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("c_1_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("c_2", 64, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("c_2_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("c_3", 64, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("c_3_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
	Port_Property("mod_0", 64, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("mod_1", 64, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("mod_2", 64, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("mod_3", 64, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("mprime", 64, hls_in, 16, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "mont_mul_fios_csa_true_pipe2";
