set SynModuleInfo {
  {SRCNAME mul_Pipeline_VITIS_LOOP_151_1 MODELNAME mul_Pipeline_VITIS_LOOP_151_1 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_151_1
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_flow_control_loop_pipe_sequential_init RTLNAME test_mul_karatsuba_configurable_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME test_mul_karatsuba_configurable_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_157_2 MODELNAME mul_Pipeline_VITIS_LOOP_157_2 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_157_2}
  {SRCNAME mul_Pipeline_VITIS_LOOP_151_11 MODELNAME mul_Pipeline_VITIS_LOOP_151_11 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_151_11}
  {SRCNAME mul_Pipeline_VITIS_LOOP_157_22 MODELNAME mul_Pipeline_VITIS_LOOP_157_22 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_157_22}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_2 MODELNAME mul_Pipeline_VITIS_LOOP_81_2 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_2
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_partselect_64ns_128ns_32ns_64_1_1 RTLNAME test_mul_karatsuba_configurable_partselect_64ns_128ns_32ns_64_1_1 BINDTYPE op TYPE partselect IMPL auto}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_23 MODELNAME mul_Pipeline_VITIS_LOOP_81_23 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_23}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_1 MODELNAME mul_Pipeline_VITIS_LOOP_74_1 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_1}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_24 MODELNAME mul_Pipeline_VITIS_LOOP_81_24 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_24}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_1 MODELNAME mul_Pipeline_VITIS_LOOP_97_1 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_1}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_2 MODELNAME mul_Pipeline_VITIS_LOOP_103_2 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_2
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_sparsemux_9_2_64_1_1 RTLNAME test_mul_karatsuba_configurable_sparsemux_9_2_64_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_3 MODELNAME mul_Pipeline_VITIS_LOOP_113_3 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_3
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_partselect_64ns_1056s_32ns_64_1_1 RTLNAME test_mul_karatsuba_configurable_partselect_64ns_1056s_32ns_64_1_1 BINDTYPE op TYPE partselect IMPL auto}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_25 MODELNAME mul_Pipeline_VITIS_LOOP_81_25 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_25}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_26 MODELNAME mul_Pipeline_VITIS_LOOP_81_26 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_26}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_17 MODELNAME mul_Pipeline_VITIS_LOOP_74_17 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_17}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_28 MODELNAME mul_Pipeline_VITIS_LOOP_81_28 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_28}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_19 MODELNAME mul_Pipeline_VITIS_LOOP_97_19 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_19}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_210 MODELNAME mul_Pipeline_VITIS_LOOP_103_210 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_210}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_311 MODELNAME mul_Pipeline_VITIS_LOOP_113_311 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_311}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_1 MODELNAME mul_Pipeline_VITIS_LOOP_56_1 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_1}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_112 MODELNAME mul_Pipeline_VITIS_LOOP_56_112 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_112}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_213 MODELNAME mul_Pipeline_VITIS_LOOP_81_213 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_213}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_114 MODELNAME mul_Pipeline_VITIS_LOOP_74_114 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_114}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_215 MODELNAME mul_Pipeline_VITIS_LOOP_81_215 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_215}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_116 MODELNAME mul_Pipeline_VITIS_LOOP_56_116 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_116}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_117 MODELNAME mul_Pipeline_VITIS_LOOP_56_117 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_117}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_118 MODELNAME mul_Pipeline_VITIS_LOOP_74_118 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_118}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_219 MODELNAME mul_Pipeline_VITIS_LOOP_81_219 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_219}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_120 MODELNAME mul_Pipeline_VITIS_LOOP_97_120 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_120}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_221 MODELNAME mul_Pipeline_VITIS_LOOP_103_221 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_221}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_322 MODELNAME mul_Pipeline_VITIS_LOOP_113_322 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_322}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_123 MODELNAME mul_Pipeline_VITIS_LOOP_97_123 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_123}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_224 MODELNAME mul_Pipeline_VITIS_LOOP_103_224 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_224}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_325 MODELNAME mul_Pipeline_VITIS_LOOP_113_325 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_325}
  {SRCNAME mul_Pipeline_VITIS_LOOP_151_126 MODELNAME mul_Pipeline_VITIS_LOOP_151_126 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_151_126}
  {SRCNAME mul_Pipeline_VITIS_LOOP_157_227 MODELNAME mul_Pipeline_VITIS_LOOP_157_227 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_157_227}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_228 MODELNAME mul_Pipeline_VITIS_LOOP_81_228 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_228}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_229 MODELNAME mul_Pipeline_VITIS_LOOP_81_229 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_229}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_130 MODELNAME mul_Pipeline_VITIS_LOOP_74_130 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_130}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_231 MODELNAME mul_Pipeline_VITIS_LOOP_81_231 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_231}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_132 MODELNAME mul_Pipeline_VITIS_LOOP_97_132 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_132}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_233 MODELNAME mul_Pipeline_VITIS_LOOP_103_233 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_233}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_334 MODELNAME mul_Pipeline_VITIS_LOOP_113_334 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_334}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_235 MODELNAME mul_Pipeline_VITIS_LOOP_81_235 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_235}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_236 MODELNAME mul_Pipeline_VITIS_LOOP_81_236 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_236}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_137 MODELNAME mul_Pipeline_VITIS_LOOP_74_137 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_137}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_238 MODELNAME mul_Pipeline_VITIS_LOOP_81_238 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_238}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_139 MODELNAME mul_Pipeline_VITIS_LOOP_97_139 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_139}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_240 MODELNAME mul_Pipeline_VITIS_LOOP_103_240 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_240}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_341 MODELNAME mul_Pipeline_VITIS_LOOP_113_341 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_341}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_142 MODELNAME mul_Pipeline_VITIS_LOOP_56_142 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_142}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_143 MODELNAME mul_Pipeline_VITIS_LOOP_56_143 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_143}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_244 MODELNAME mul_Pipeline_VITIS_LOOP_81_244 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_244}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_145 MODELNAME mul_Pipeline_VITIS_LOOP_74_145 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_145}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_246 MODELNAME mul_Pipeline_VITIS_LOOP_81_246 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_246}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_147 MODELNAME mul_Pipeline_VITIS_LOOP_56_147 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_147}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_148 MODELNAME mul_Pipeline_VITIS_LOOP_56_148 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_148}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_149 MODELNAME mul_Pipeline_VITIS_LOOP_74_149 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_149}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_250 MODELNAME mul_Pipeline_VITIS_LOOP_81_250 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_250}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_151 MODELNAME mul_Pipeline_VITIS_LOOP_97_151 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_151}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_252 MODELNAME mul_Pipeline_VITIS_LOOP_103_252 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_252}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_353 MODELNAME mul_Pipeline_VITIS_LOOP_113_353 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_353}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_154 MODELNAME mul_Pipeline_VITIS_LOOP_97_154 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_154}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_255 MODELNAME mul_Pipeline_VITIS_LOOP_103_255 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_255}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_356 MODELNAME mul_Pipeline_VITIS_LOOP_113_356 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_356}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_157 MODELNAME mul_Pipeline_VITIS_LOOP_56_157 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_157}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_158 MODELNAME mul_Pipeline_VITIS_LOOP_56_158 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_158}
  {SRCNAME mul_Pipeline_VITIS_LOOP_151_159 MODELNAME mul_Pipeline_VITIS_LOOP_151_159 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_151_159}
  {SRCNAME mul_Pipeline_VITIS_LOOP_157_260 MODELNAME mul_Pipeline_VITIS_LOOP_157_260 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_157_260
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_sparsemux_7_2_64_1_1 RTLNAME test_mul_karatsuba_configurable_sparsemux_7_2_64_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_261 MODELNAME mul_Pipeline_VITIS_LOOP_81_261 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_261}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_262 MODELNAME mul_Pipeline_VITIS_LOOP_81_262 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_262}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_163 MODELNAME mul_Pipeline_VITIS_LOOP_74_163 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_163}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_264 MODELNAME mul_Pipeline_VITIS_LOOP_81_264 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_264}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_165 MODELNAME mul_Pipeline_VITIS_LOOP_97_165 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_165}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_266 MODELNAME mul_Pipeline_VITIS_LOOP_103_266 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_266}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_367 MODELNAME mul_Pipeline_VITIS_LOOP_113_367 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_367}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_168 MODELNAME mul_Pipeline_VITIS_LOOP_74_168 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_168}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_269 MODELNAME mul_Pipeline_VITIS_LOOP_81_269 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_269}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_170 MODELNAME mul_Pipeline_VITIS_LOOP_74_170 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_170}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_271 MODELNAME mul_Pipeline_VITIS_LOOP_81_271 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_271}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_172 MODELNAME mul_Pipeline_VITIS_LOOP_56_172 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_172}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_173 MODELNAME mul_Pipeline_VITIS_LOOP_56_173 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_173}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_174 MODELNAME mul_Pipeline_VITIS_LOOP_74_174 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_174}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_275 MODELNAME mul_Pipeline_VITIS_LOOP_81_275 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_275}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_176 MODELNAME mul_Pipeline_VITIS_LOOP_97_176 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_176}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_277 MODELNAME mul_Pipeline_VITIS_LOOP_103_277 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_277}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_378 MODELNAME mul_Pipeline_VITIS_LOOP_113_378 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_378
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_partselect_64ns_1056ns_32ns_64_1_1 RTLNAME test_mul_karatsuba_configurable_partselect_64ns_1056ns_32ns_64_1_1 BINDTYPE op TYPE partselect IMPL auto}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_179 MODELNAME mul_Pipeline_VITIS_LOOP_56_179 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_179}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_180 MODELNAME mul_Pipeline_VITIS_LOOP_56_180 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_180}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_181 MODELNAME mul_Pipeline_VITIS_LOOP_74_181 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_181}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_282 MODELNAME mul_Pipeline_VITIS_LOOP_81_282 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_282}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_183 MODELNAME mul_Pipeline_VITIS_LOOP_74_183 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_183
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_partset_64ns_64ns_64ns_32ns_64_1_1 RTLNAME test_mul_karatsuba_configurable_partset_64ns_64ns_64ns_32ns_64_1_1 BINDTYPE op TYPE partset IMPL auto}
    }
  }
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_284 MODELNAME mul_Pipeline_VITIS_LOOP_81_284 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_284}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_185 MODELNAME mul_Pipeline_VITIS_LOOP_56_185 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_185}
  {SRCNAME mul_Pipeline_VITIS_LOOP_56_186 MODELNAME mul_Pipeline_VITIS_LOOP_56_186 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_56_186}
  {SRCNAME mul_Pipeline_VITIS_LOOP_74_187 MODELNAME mul_Pipeline_VITIS_LOOP_74_187 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_74_187}
  {SRCNAME mul_Pipeline_VITIS_LOOP_81_288 MODELNAME mul_Pipeline_VITIS_LOOP_81_288 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_81_288}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_189 MODELNAME mul_Pipeline_VITIS_LOOP_97_189 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_189}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_290 MODELNAME mul_Pipeline_VITIS_LOOP_103_290 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_290}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_391 MODELNAME mul_Pipeline_VITIS_LOOP_113_391 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_391}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_192 MODELNAME mul_Pipeline_VITIS_LOOP_97_192 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_192}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_293 MODELNAME mul_Pipeline_VITIS_LOOP_103_293 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_293}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_394 MODELNAME mul_Pipeline_VITIS_LOOP_113_394 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_394}
  {SRCNAME mul_Pipeline_VITIS_LOOP_97_195 MODELNAME mul_Pipeline_VITIS_LOOP_97_195 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_97_195}
  {SRCNAME mul_Pipeline_VITIS_LOOP_103_296 MODELNAME mul_Pipeline_VITIS_LOOP_103_296 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_103_296}
  {SRCNAME mul_Pipeline_VITIS_LOOP_113_397 MODELNAME mul_Pipeline_VITIS_LOOP_113_397 RTLNAME test_mul_karatsuba_configurable_mul_Pipeline_VITIS_LOOP_113_397}
  {SRCNAME mul MODELNAME mul RTLNAME test_mul_karatsuba_configurable_mul
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_mul_64ns_64ns_128_1_1 RTLNAME test_mul_karatsuba_configurable_mul_64ns_64ns_128_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME test_mul_karatsuba_configurable_sparsemux_7_3_64_1_1 RTLNAME test_mul_karatsuba_configurable_sparsemux_7_3_64_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME test_mul_karatsuba_configurable_mul_z1_1_RAM_AUTO_1R1W RTLNAME test_mul_karatsuba_configurable_mul_z1_1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME test_mul_karatsuba_configurable_mul_z0_RAM_AUTO_1R1W RTLNAME test_mul_karatsuba_configurable_mul_z0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME test_mul_karatsuba_configurable_mul_z1_17_RAM_AUTO_1R1W RTLNAME test_mul_karatsuba_configurable_mul_z1_17_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME mul.1 MODELNAME mul_1 RTLNAME test_mul_karatsuba_configurable_mul_1}
  {SRCNAME test_mul_karatsuba_configurable MODELNAME test_mul_karatsuba_configurable RTLNAME test_mul_karatsuba_configurable IS_TOP 1
    SUBMODULES {
      {MODELNAME test_mul_karatsuba_configurable_control_s_axi RTLNAME test_mul_karatsuba_configurable_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
